### ISSUE TITLE
Problem build on Platformio

### ISSUE THREAD

**Issue by Bighoneypot** [tobiasschuerg/InfluxDB-Client-for-Arduino#100]
I have this error to build firmware with Platformio

identifier "configTzTime" is undefined
'configTzTime' was not declared in this scope

{
	"resource": "/c:/Users/IoT/Documents/PlatformIO/Projects/InfluxdbEsp8266/.pio/libdeps/nodemcuv2/ESP8266 Influxdb/src/util/helpers.cpp",
	"owner": "C/C++6",
	"severity": 8,
	"message": "identifier \"configTzTime\" is undefined",
	"startLineNumber": 32,
	"startColumn": 3,
	"endLineNumber": 32,
	"endColumn": 15
}

{
	"resource": "/c:/Users/IoT/Documents/PlatformIO/Projects/InfluxdbEsp8266/.pio/libdeps/nodemcuv2/ESP8266 Influxdb/src/util/helpers.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'configTzTime' was not declared in this scope",
	"startLineNumber": 32,
	"startColumn": 57,
	"endLineNumber": 32,
	"endColumn": 57
}

**Comment by vlastahajek** [comment]
@Bighoneypot, you, most probably, have an old version of ESP8266 SDK

**Comment by Bighoneypot** [comment]
@vlastahajek thank you. I'm update SDK on Arduino IDE and now work for me.
Can you help me to updata SDK on Platformio?

Thank you!!!!

**Comment by vlastahajek** [comment]
@Bighoneypot, unfortunatelly I can't help you with PlatformIO. I don't have any experience with it yet.

**Comment by Bighoneypot** [comment]
@vlastahajek thank you!!!
