### ISSUE TITLE
Request for Help: Dealing with timestamp timezone

### ISSUE THREAD

**Issue by prys** [tobiasschuerg/InfluxDB-Client-for-Arduino#102]
Hi,

I'm struggling to understand how I can adjust the timestamp returned from my flux query to reflect my current timezone. I successfully get the timestamp via: -

`FluxDateTime time = myResult.getValueByName("_time").getDateTime();`

...but this give me the a GMT timestamp, whereas my local time is currently BST - i.e. +1 hour.

I am using...

`timeSync("GMT0BST,M3.4.0/1,M10.4.0", "0.uk.pool.ntp.org", "1.uk.pool.ntp.org");`

...in the code for both writing and query actions, but I can see from my influxdb data that the timestamp is GMT.

Any help much appreciated.

**Comment by vlastahajek** [comment]
@prys,  it depends on what do you want to achieve.  If just printing, default `format` method uses [strftime](http://www.cplusplus.com/reference/ctime/strftime/) internally, which prints time in local timezone.
For other cases, you can use [localtime](http://www.cplusplus.com/reference/ctime/localtime/) to get tm in local TZ:
```cpp
      FluxDateTime time = result.getValueByName("_time").getDateTime();
      time_t absTime = mktime(&time.value);
      tm *localTime = localtime(&absTime);
```

**Comment by prys** [comment]
Ah thank you @vlastahajek. In fact, I couldn't find the correct `format` specifier to print local time, but never mind, what I needed was `mktime` which applies the correct zone information and using the [tm](http://www.cplusplus.com/reference/ctime/tm/) structure helps me with comparison etc.

Many thanks.
