### ISSUE TITLE
BasicWrite example sketch write errors w/ "InfluxDB write failed: 405: Method Not Allowed" after successful connection

### ISSUE THREAD

**Issue by iannecj** [tobiasschuerg/InfluxDB-Client-for-Arduino#106]
I am using this with a local influx instance created by home assistant addon for influx db.  I believe this uses an influx version 1.8.x.

I notice if I change parameters (e.g. INFLUXDB_URL, INFLUXDB_DB_NAME, USER) I don't get successful connect.
However, password can be changed in code and serial monitor output describing connection seems unchanged whereas I would have though an incorrect password would fail to connect.  One might think password is incorrect but I have reverified.  I have also tried turning authentication off on influx from home assistant addon but no joy.

Any ideas?  Thanks for looking at this!

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Connecting to WiFi

192.168.1.47
Connected to InfluxDB: http://192.168.1.74:8123/a0d7b954_influxdb
Writing: wifi_status,device=ESP32,SSID=redacted rssi=-32i
InfluxDB write failed: 405: Method Not Allowed
Wait 10s
Writing: wifi_status,device=ESP32,SSID=redacted rssi=-35i
InfluxDB write failed: 405: Method Not Allowed
Wait 10s
```

```
#if defined(ESP32)
#include <WiFiMulti.h>
WiFiMulti wifiMulti;
#define DEVICE "ESP32"
#elif defined(ESP8266)
#include <ESP8266WiFiMulti.h>
ESP8266WiFiMulti wifiMulti;
#define DEVICE "ESP8266"
#endif

#include <InfluxDbClient.h>

// WiFi AP SSID
#define WIFI_SSID "redacted"
// WiFi password
#define WIFI_PASSWORD "redacted"
// InfluxDB  server url. Don't use localhost, always server name or ip address.
// E.g. http://192.168.1.48:8086 (In InfluxDB 2 UI -> Load Data -> Client Libraries), 
#define INFLUXDB_URL "http://192.168.1.74:8123/a0d7b954_influxdb"
// InfluxDB 2 server or cloud API authentication token (Use: InfluxDB UI -> Load Data -> Tokens -> <select token>)
//#define INFLUXDB_TOKEN "toked-id"
// InfluxDB 2 organization id (Use: InfluxDB UI -> Settings -> Profile -> <name under tile> )
//#define INFLUXDB_ORG "org"
// InfluxDB 2 bucket name (Use: InfluxDB UI -> Load Data -> Buckets)
//#define INFLUXDB_BUCKET "bucket"
// InfluxDB v1 database name 
#define INFLUXDB_DB_NAME "raptor"

// InfluxDB client instance
//InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN);
// InfluxDB client instance for InfluxDB 1
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);

// Data point
Point sensor("wifi_status");

void setup() {
  Serial.begin(115200);

  // Connect WiFi
  Serial.println("Connecting to WiFi");
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);
  while (wifiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(100);
  }
  Serial.println();
  Serial.println(WiFi.localIP());

  // Set InfluxDB 1 authentication params
  client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME,"raptor","raptorX");

  // Add constant tags - only once
  sensor.addTag("device", DEVICE);
  sensor.addTag("SSID", WiFi.SSID());

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  } else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }
}

void loop() {
  // Store measured value into point
  sensor.clearFields();
  // Report RSSI of currently connected network
  sensor.addField("rssi", WiFi.RSSI());
  // Print what are we exactly writing
  Serial.print("Writing: ");
  Serial.println(sensor.toLineProtocol());
  // If no Wifi signal, try to reconnect it
  if ((WiFi.RSSI() == 0) && (wifiMulti.run() != WL_CONNECTED))
    Serial.println("Wifi connection lost");
  // Write point
  if (!client.writePoint(sensor)) {
    Serial.print("InfluxDB write failed: ");
    Serial.println(client.getLastErrorMessage());
  }

  //Wait 10s
  Serial.println("Wait 10s");
  delay(10000);
}
```

**Comment by iannecj** [comment]
Now with debug active:

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Connecting to WiFi

192.168.1.47
Init
  Server url: http://192.168.1.74:8123/a0d7b954_influxdb
  Org: 
  Bucket: raptor
  Token: 
  DB version: 1
setUrls
  writeUrl: http://192.168.1.74:8123/a0d7b954_influxdb/write?db=raptor&u=raptor&p=raptorX
  queryUrl: http://192.168.1.74:8123/a0d7b954_influxdb/api/v2/query?&u=raptor&p=raptorX
[D] Validating connection to http://192.168.1.74:8123/a0d7b954_influxdb/ping?verbose=true
[D] HTTP status code - 200
Connected to InfluxDB: http://192.168.1.74:8123/a0d7b954_influxdb
Writing: wifi_status,device=ESP32,SSID=redacted rssi=-33i
[D] writeRecord: bufferPointer: 0, batchPointer: 0
[D] Flushing buffer: is oversized true, is timeout false, is buffer full false
[D] Writing batch, batchpointer: 0, size 1
[D] Writing to http://192.168.1.74:8123/a0d7b954_influxdb/write?db=raptor&u=raptor&p=raptorX
[D] Sending:
wifi_status,device=ESP32,SSID=redacted rssi=-33i

[D] HTTP status code - 405
[D] Response:
405: Method Not Allowed
[D] Droped batch, batchpointer: 1
InfluxDB write failed: 405: Method Not Allowed
Wait 10s

```

**Comment by vlastahajek** [comment]
@iannecj , could you, please, share what home assistant addon do you have? 
Are you sure the /write endpoint is allowed? Are you able to post data from another computer?
E.g. `curl  'http://192.168.1.74:8123/a0d7b954_influxdb/write?db=raptor&u=raptor&p=raptorX' --data-raw 'wifi_status,device=ESP32,SSID=redacted rssi=-33i`

**Comment by iannecj** [comment]
Startup log from homeassistant addon for influx


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 3.7.7
 You are running the latest version of this add-on.
 System: HassOS 4.15  (armv7 / raspberrypi4)
 Home Assistant Core: 0.116.4
 Home Assistant Supervisor: 249
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] create-users.sh: executing... 
[cont-init.d] create-users.sh: exited 0.
[cont-init.d] influxdb.sh: executing... 
[cont-init.d] influxdb.sh: exited 0.
[cont-init.d] kapacitor.sh: executing... 
[cont-init.d] kapacitor.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[09:37:35] DEBUG: Requested API resource: http://supervisor/dns/info
[09:37:35] DEBUG: Request method: GET
[09:37:35] DEBUG: Request data: {}
[09:37:35] DEBUG: API HTTP Response code: 200
[09:37:35] DEBUG: API Response: {"result": "ok", "data": {"version": "2020.10.0", "version_latest": "2020.10.0", "host": "172.30.32.3", "servers": [], "locals": ["dns://192.168.1.1"]}}
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:37:35] INFO: Chronograf is waiting until InfluxDB is available...
[09:37:35] INFO: Kapacitor is waiting until InfluxDB is available...
[09:37:35] INFO: Starting the InfluxDB...
[09:38:06] INFO: Starting the Kapacitor
[09:38:06] INFO: Starting Chronograf...
'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
2020/10/26 09:38:08 Using configuration at: /etc/kapacitor/kapacitor.conf
time="2020-10-26T09:38:26-04:00" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
time="2020-10-26T09:38:26-04:00" level=info msg="Serving chronograf at http://127.0.0.1:8889" component=server
[09:38:26] INFO: Starting NGinx...
time="2020-10-26T09:38:29-04:00" level=debug msg=Request component=server method=GET remote_addr="127.0.0.1:60602" url=/api/hassio_ingress/jr3n9Y43gGgPb3XEnsM7_35wVwPT9RBZoPOnc52dBhc/chronograf/v1/me
time="2020-10-26T09:38:29-04:00" level=info msg="Response: OK" component=server method=GET remote_addr="127.0.0.1:60602" response_time="538.155µs" status=200
[26/Oct/2020:09:38:29 -0400] 200 127.0.0.1, 172.30.32.1(172.30.32.2) GET /chronograf/v1/me HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36)

**Comment by iannecj** [comment]
@vlastahajek forgive this newbie question but from windows how would I go about testing the write as you show with curl?  command line doesnt recognize

**Comment by vlastahajek** [comment]
@iannecjm I don't see log messages from InfluxDB, however, I see Nginx there. It could mean that it doesn't allow POST, etc. Check its config, please. 

You have to download a curl build for Windows or try using a Power shell command for HTTP POST. However, as this library mostly works OK, I expect you will the same error.

**Comment by iannecj** [comment]
@vlastahajek   Looks like this issue was with db url.

http://192.168.1.74:8123/a0d7b954_influxdb

should have been

http://192.168.1.74:8086

Home assisatnt has influx in a container mapped to port 8086.

Had nothing to do with NGINX or writes being disallowed as no changes in those things were needed even though I tried them based on your note.

**Comment by vlastahajek** [comment]
@iannecj, you have found the solution yourselves, good work!
As this is a packaged solution, I expected it will hide internal services behind the Nginx, but it leaves them open.
