### ISSUE TITLE
fatal error: core_version.h: No such file or directory

### ISSUE THREAD

**Issue by shanisma** [tobiasschuerg/InfluxDB-Client-for-Arduino#112]
Hello,

I just tried to import <InfluxDbClient.h> ... it think core_version.h and core_version.cpp are missing ..

__Steps to reproduce:__

1. Open empty project in arduino IDE, add library ESP8266 Influxdb version 3.5.0
2. add #include <InfluxDbClient.h> in .ino file
3. Compile

__Expected behavior:__
Compilation done.

__Actual behavior:__

/Users/shanisma/Documents/Arduino/libraries/ESP8266_Influxdb/src/InfluxDbClient.cpp:28:26: fatal error: core_version.h: No such file or directory

__Specifications:__
 - Library Version: 3.5
 - InfluxDB Version: just testing for line protocol 
 - Board chip: ESP32

**Comment by vlastahajek** [comment]
@shanisma, what version of ESP32 Arduino SDK do you have?
