### ISSUE TITLE
password with spaces is not handled correctly

### ISSUE THREAD

**Issue by tomhub** [tobiasschuerg/InfluxDB-Client-for-Arduino#116]
Using library for ESP32 to post data to InfluxDB v1.8.3, esp32 does not catch (all) unexpected results and restarts. Connecting to InfluxDB via http (unsecured), with username and password. Password contains spaces. 

Tested the same configuration, but with different username and password which doesn't contain spaces: works as expected.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use BasicWrite example
2. Test write to InfluxDB 1.8 using username and password and password to contain spaces.
3. ESP32 reboots (not always, but in random cases)

__Expected behavior:__
Expected InfluxDBClient to handle password with spaces (and possibly other special characters).

__Actual behavior:__
In most case, return of 400 Bad Request as shown here:
15:54:16.762 -> Writing: wifi_status,device=ESP32,SSID=MYWIFI rssi=-68i
15:54:16.762 -> 125.448 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
15:54:16.762 -> 125.449 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
15:54:16.762 -> 125.456 [D] Writing batch, batchpointer: 0, size 1
15:54:16.762 -> 125.461 [D] Writing to http://influxdbhost:8086/write?db=dump&u=influxdbwriter&p=send me some data using this secret word
15:54:16.795 -> [D][HTTPClient.cpp:276] beginInternal(): host: influxdbhost port: 8086 url: /write?db=dump&u=influxdbwriter&p=send me some data using this secret word
15:54:16.795 -> 125.479 [D] Sending:
15:54:16.795 -> wifi_status,device=ESP32,SSID=MYWIFI rssi=-68i
15:54:16.795 -> 
15:54:16.828 -> [D][HTTPClient.cpp:1025] connect():  connected to influxdbhost:8086
15:54:16.828 -> [D][HTTPClient.cpp:1158] handleHeaderResponse(): code: 400
15:54:16.828 -> 125.539 [D] HTTP status code - 400
15:54:16.861 -> [D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, ERR: 128
15:54:16.861 -> [D][HTTPClient.cpp:1295] writeToStreamDataBlock(): connection closed or file end (written: 15).
15:54:16.861 -> [D][HTTPClient.cpp:383] disconnect(): tcp is closed
15:54:16.861 -> 
15:54:16.861 -> 125.555 [D] Response:
15:54:16.861 -> 400 Bad Request
15:54:16.861 -> [D][HTTPClient.cpp:383] disconnect(): tcp is closed
15:54:16.861 -> 
15:54:16.861 -> 125.563 [D] Droped batch, batchpointer: 1
15:54:16.894 -> 125.567 [D] Success: 0, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0
15:54:16.894 -> 125.575 [D] Buffer empty
15:54:16.894 -> InfluxDB write failed: 400 Bad Request
15:54:16.894 -> Wait 10s

In some cases, it is:
15:56:20.236 -> Writing: wifi_status,device=ESP32,SSID=MYWIFI rssi=-67i
15:56:20.236 -> 248.926 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
15:56:20.236 -> 248.927 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
15:56:20.236 -> 248.934 [D] Writing batch, batchpointer: 0, size 1
15:56:20.269 -> 248.939 [D] Writing to http://influxdbhost:8086/write?db=dump&u=influxdbwriter&p=send me some data using this secret word
15:56:20.269 -> [D][HTTPClient.cpp:276] beginInternal(): host: influxdbhost port: 8086 url: /write?db=dump&u=influxdbwriter&p=send me some data using this secret word
15:56:20.269 -> 248.957 [D] Sending:
15:56:20.269 -> wifi_status,device=ESP32,SSID=MYWIFI rssi=-67i
15:56:20.269 -> 
15:56:20.269 -> [D][HTTPClient.cpp:1025] connect():  connected to influxdbhost:8086
15:56:20.302 -> [E][WiFiClient.cpp:436] read(): fail on fd 59, errno: 104, "Connection reset by peer"
15:56:20.302 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
15:56:20.302 -> Core 1 register dump:
15:56:20.336 -> PC      : 0x400d2230  PS      : 0x00060830  A0      : 0x800d263d  A1      : 0x3ffb1ca0  
15:56:20.336 -> A2      : 0x00000000  A3      : 0x3ffb1cff  A4      : 0x00000001  A5      : 0x00000001  
15:56:20.336 -> A6      : 0x3ffc1648  A7      : 0x00000068  A8      : 0x00000000  A9      : 0x00000000  
15:56:20.336 -> A10     : 0x0bfffffc  A11     : 0x40084f34  A12     : 0x00000050  A13     : 0x00000000  
15:56:20.336 -> A14     : 0x0bfffffc  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
15:56:20.369 -> EXCVADDR: 0x00000008  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
15:56:20.369 -> 
15:56:20.369 -> Backtrace: 0x400d2230:0x3ffb1ca0 0x400d263a:0x3ffb1cc0 0x401601ea:0x3ffb1cf0 0x400d91e9:0x3ffb1d20 0x400d9281:0x3ffb1d40 0x400d6bdd:0x3ffb1d60 0x400d76b7:0x3ffb1e00 0x400d7723:0x3ffb1e40 0x400d5311:0x3ffb1e60 0x400d54af:0x3ffb1eb0 0x400d578d:0x3ffb1ee0 0x400d58fe:0x3ffb1f00 0x400d597d:0x3ffb1f30 0x400d1ef5:0x3ffb1f70 0x400da261:0x3ffb1fb0 0x40088b9d:0x3ffb1fd0
15:56:20.402 -> 
15:56:20.402 -> Rebooting...

__Specifications:__
 - Library Version: 3.5.0
 - InfluxDB Version: 1.8.3
 - Board/ESP chip: ESP32 DEVKIT V1 (ESP-WROOM-32)

**Comment by vlastahajek** [comment]
@tomhub, thanks for the issue. I confirm, that there is no URL escaping yet. 
What is the ESP32 SDK version?
Regarding crashing, could you, please, use [EspExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder) and paste here the stack trace?

**Comment by tomhub** [comment]
Using ESP object:
v3.2.3-14-gd3e562907
Using lower level function:
v3.2.3-14-gd3e562907

EspExceptionDecoder says: Decode Failed.

**Comment by vlastahajek** [comment]
> Using ESP object:
> v3.2.3-14-gd3e562907
> Using lower level function:
> v3.2.3-14-gd3e562907

This is the version of the underlying ESP IDF SDK. 
Sorry for the confusion, I meant a version of ESP32 Arduino SDK.

> EspExceptionDecoder says: Decode Failed.

Did you paste exception lines without timestamps?
```
Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC : 0x400d2230 PS : 0x00060830 A0 : 0x800d263d A1 : 0x3ffb1ca0
A2 : 0x00000000 A3 : 0x3ffb1cff A4 : 0x00000001 A5 : 0x00000001
A6 : 0x3ffc1648 A7 : 0x00000068 A8 : 0x00000000 A9 : 0x00000000
A10 : 0x0bfffffc A11 : 0x40084f34 A12 : 0x00000050 A13 : 0x00000000
A14 : 0x0bfffffc A15 : 0x00000000 SAR : 0x0000000a EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000008 LBEG : 0x4000c2e0 LEND : 0x4000c2f6 LCOUNT : 0xffffffff

Backtrace: 0x400d2230:0x3ffb1ca0 0x400d263a:0x3ffb1cc0 0x401601ea:0x3ffb1cf0 0x400d91e9:0x3ffb1d20 0x400d9281:0x3ffb1d40 0x400d6bdd:0x3ffb1d60 0x400d76b7:0x3ffb1e00 0x400d7723:0x3ffb1e40 0x400d5311:0x3ffb1e60 0x400d54af:0x3ffb1eb0 0x400d578d:0x3ffb1ee0 0x400d58fe:0x3ffb1f00 0x400d597d:0x3ffb1f30 0x400d1ef5:0x3ffb1f70 0x400da261:0x3ffb1fb0 0x40088b9d:0x3ffb1fd0
```

**Comment by tomhub** [comment]
Yes, I did paste without timestamp. But since I found the culprit of these reboots, my ESP32 is already installed and sending data to influxdb. I just don't have any spare esp32 to debug with at the moment, more to order soon.

**Comment by vlastahajek** [comment]
Yes, this is the version you have in Boards Manager.
I will try to reproduce the crash..

**Comment by vlastahajek** [comment]
I reproduced the crash:
```
PC: 0x400d9654: WiFiClientRxBuffer::read(unsigned char*, unsigned int) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src\WiFiClient.cpp line 107
EXCVADDR: 0x00000008

Decoding stack results
0x400d9654: WiFiClientRxBuffer::read(unsigned char*, unsigned int) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src\WiFiClient.cpp line 107
0x400d9725: WiFiClient::read(unsigned char*, unsigned int) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src\WiFiClient.cpp line 434
0x40167a56: WiFiClient::read() at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src\WiFiClient.cpp line 345
0x400db5a9: Stream::timedRead() at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32\Stream.cpp line 36
0x400db641: Stream::readStringUntil(char) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32\Stream.cpp line 287
0x400d8831: HTTPClient::handleHeaderResponse() at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\HTTPClient\src\HTTPClient.cpp line 1118
0x400d904b: HTTPClient::sendRequest(char const*, unsigned char*, unsigned int) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\HTTPClient\src\HTTPClient.cpp line 573
0x400d90b3: HTTPClient::POST(unsigned char*, unsigned int) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\HTTPClient\src\HTTPClient.cpp line 493
0x400d4c95: InfluxDBClient::postData(char const*) at C:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\src\InfluxDbClient.cpp line 579
0x400d4e33: InfluxDBClient::flushBufferInternal(bool) at C:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\src\InfluxDbClient.cpp line 462
0x400d5111: InfluxDBClient::checkBuffer() at C:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\src\InfluxDbClient.cpp line 419
0x400d5282: InfluxDBClient::writeRecord(String&) at C:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\src\InfluxDbClient.cpp line 408
0x400d52eb: InfluxDBClient::writePoint(Point&) at C:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\src\InfluxDbClient.cpp line 345
0x400d2471: Test::testV1() at c:\tmp\_ArduinoOutput\influxdbclientarduino\sketch\Test.cpp line 1105
0x400d2dda: Test::run() at c:\tmp\_ArduinoOutput\influxdbclientarduino\sketch\Test.cpp line 90
0x400d36a4: loop() at c:\Users\vlast\OneDrive\Dokumenty\Arduino\libraries\Influx_db_client_arduino\test/test.ino line 54
0x400dc861: loopTask(void*) at C:\Users\vlast\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32\main.cpp line 19
0x40088b9d: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143
```
This is a problem in the WiFiClient. I will open an issue in the ESP32 Arduino repo.
