### ISSUE TITLE
secure batch write (float array) no error on terminal but no data on influxdb

### ISSUE THREAD

**Issue by kmf909** [tobiasschuerg/InfluxDB-Client-for-Arduino#119]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. use adxl362 to sent x-axis data in float char to local influxdb server

__Expected behavior:__
Describe what you expected to happen.
a batch of x-axis data can be view using chronograf/grafana

__Actual behavior:__
use chronograf to view the data but the query checker stated that no data available

__Specifications:__
 - Library Version: 3.6.0
 - InfluxDB Version: 1.8.3
 - Board/ESP chip: ESP32
 - Device Arduino SDK version:1.8.10

**Comment by vlastahajek** [comment]
@kmf909, what is the data format you used to add as a field? 
What do you mean by `float char array`? If it is a string, you have to select table view to view such data.

**Comment by kmf909** [comment]
hi @vlastahajek 

the data format is float array.
![image](https://user-images.githubusercontent.com/20061425/99485264-15f64f00-299d-11eb-9d11-4a257e970b08.png)




. below is the example code (secure batch write) snapshot that i edited. there is no error on arduino serial so im not sure how to troubleshoot .

`for (int i = 0; i < networks; i++) {
      storeADXL357(Ndata, Vibra_axis);
     //      xaxis = String(adxlbuff[i]);
      Point sensorNetworks("batch-adxl357-v3");
      sensorNetworks.addTag("device", DEVICE);
      sensorNetworks.addTag("SSID", WiFi.SSID(i));
      sensorNetworks.addTag("channel", String(WiFi.channel(i)));
      sensorNetworks.addTag("open", String(WiFi.encryptionType(i) == WIFI_AUTH_OPEN));
      sensorNetworks.addField("rssi",adxlbuff[i]);
      //sensorNetworks.addField("rssi", WiFi.RSSI(i));
      sensorNetworks.setTime(tnow);  //set the time

      // Print what are we exactly writing
      Serial.print("Writing: ");
      Serial.println(sensorNetworks.toLineProtocol());

      // Write point into buffer - low priority measures
      client.writePoint(sensorNetworks);
    }`

**Comment by vlastahajek** [comment]
the `client.writePoint(sensorNetworks);` line is the only write call functions or is there a call to `client.flushBuffer()` with result check?
Is there successful time sync?
What query do you have in Chronograf?

**Comment by kmf909** [comment]
1. **the client.writePoint(sensorNetworks); line is the only write call functions or is there a call to client.flushBuffer() with result check?.**

there are client.flushBuffer() with result check. if i comment line below, the serial print "Wifi networks reporting skipped due to communication issues"

`if (!client.flushBuffer()) {
    Serial.print("InfluxDB flush failed: ");
    Serial.println(client.getLastErrorMessage());
    Serial.print("Full buffer: ");
    Serial.println(client.isBufferFull() ? "Yes" : "No");
  }`

2. **Is there successful time sync?**
yes the time is sync
![image](https://user-images.githubusercontent.com/20061425/99786405-6a462e00-2b59-11eb-995f-71a50ee8e2bb.png)


3. **What query do you have in Chronograf?**
below is the query
`SELECT mean("x-axis") AS "mean_x-axis" FROM "dev1"."autogen"."BATCH-1.22" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)`

**Comment by vlastahajek** [comment]
Do you query the right data?
I see several measurements in your posts. For example, your example code shows that you store data into measurement `batch-adxl357-v3` with field name `rssi` , but you query data from  `BATCH-1.22` measurement and field `x-axis`.

**Comment by kmf909** [comment]
i test several code iteration and wrongly copy the query but i already test the on the same code as previous (batch-adxl357-v3) . the code run when i change write precision as below, but when i change to millisecond (MS) chronograf only view 1 data point. i try to verify the data receive on the database using CLI and the data is there. maybe there is issue on chronograf side. the code is running now but i have another issue, the interval on every batch send is 5 second. 

`#define WRITE_PRECISION WritePrecision::S'

 the code is running now but i have another issue, the interval on every batch send is 5 second. i already comment wifi check and flush buffer but it still send every 5 second. how can i speed up the send interval to every second.

`  // If no Wifi signal, try to reconnect it
//  if ((WiFi.RSSI() == 0) && (wifiMulti.run() != WL_CONNECTED))
//    Serial.println("Wifi connection lost");

  // End of the iteration - force write of all the values into InfluxDB as single transaction
//  Serial.println("Flushing data into InfluxDB");
//  if (!client.flushBuffer()) {
//    Serial.print("InfluxDB flush failed: ");
//    Serial.println(client.getLastErrorMessage());
//    Serial.print("Full buffer: ");
//    Serial.println(client.isBufferFull() ? "Yes" : "No");
//  }`

do i need to create another issue or we can just continue here?.

**Comment by vlastahajek** [comment]
Regarding query: `SELECT mean("x-axis") AS "mean_x-axis" FROM "dev1"."autogen"."BATCH-1.22" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)`.
Chronograf by default groups data by a time interval and aggregates data using some function. If you want to see all points, just edit query and remove aggregation and grouping.:
`SELECT x-axis FROM "dev1"."autogen"."BATCH-1.22" WHERE time > :dashboardTime: AND time < :upperDashboardTime:`

Regarding delay: You can send data at whatever speed you need. For speed higher than batch/5s I would recommend setting reusing connection to true: e.g. `client.setHTTPOptions(HTTPOptions().connectionReuse(true));`

**Comment by kmf909** [comment]
thanks for the chronograf solution. regarding delay, where actually i need to add the line.

**Comment by vlastahajek** [comment]
The `setup` method is the best place for configuring the client.

**Comment by kmf909** [comment]
ok i just add the line under void setup. below is the serial output. it still send every 5 second. 

![image](https://user-images.githubusercontent.com/20061425/100207146-33e62580-2f42-11eb-874e-acfcccf654c1.png)

**Comment by vlastahajek** [comment]
What is your delay in the end of loop?

**Comment by kmf909** [comment]
100ms delay at the end of the loop.

**Comment by vlastahajek** [comment]
Do you have a local server or InfluxDB Cloud? 
Enable debug messages by uncommenting the define on line 44 in the library sources, file `src/InfluxDBClient.cpp`, upload your sketch, and past here the redacted serial log, please.

**Comment by kmf909** [comment]
below is the debug output

`19:10:11.339 -> Connecting to wifi
19:10:16.846 -> Syncing time.
19:10:17.377 -> Synchronized time: Wed Nov 25 19:10:17 2020
19:10:17.377 -> 
19:10:17.377 -> 6.160 Init
19:10:17.377 -> 6.160   Library version: 3.6.0
19:10:17.377 -> 6.161   Server url: http://192.168.xxx.xxx:8086
19:10:17.377 -> 6.161   Org: 
19:10:17.377 -> 6.162   Bucket: dev1
19:10:17.377 -> 6.164   Token: 
19:10:17.377 -> 6.165   DB version: 1
19:10:17.377 -> 6.167 setUrls
19:10:17.377 -> 6.168   writeUrl: http://192.168.xxx.xxx:8086/write?db=dev1
19:10:17.377 -> 6.173   queryUrl: http://192.168.xxx.xxx:8086/api/v2/query
19:10:17.377 -> 6.178 [D] Validating connection to http://192.168.xxx.xxx:8086/ping?verbose=true
19:10:18.936 -> Connected to InfluxDB: http://192.168.xxx.xxx:8086
19:10:18.936 -> 7.704 setUrls
19:10:18.936 -> 7.704   writeUrl: http://192.168.xxx.xxx:8086/write?db=dev1
19:10:18.936 -> 7.704   queryUrl: http://192.168.xxx.xxx:8086/api/v2/query
19:10:18.936 -> 7.708   writeUrl: http://192.168.xxx.xxx:8086/write?db=dev1&precision=ms
19:10:18.936 -> 7.715 [D] Changing buffer size to 100
19:10:18.936 -> 7.718 Reset buffer: writeBuffSize: 2
19:10:19.936 -> Start Demo: Simple Read
19:10:24.847 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1171.00
19:10:24.847 -> 13.646 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.847 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1171.00
19:10:24.847 -> 13.651 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.880 -> BATCH-1.43 x-axis=-64.00,y-axis=-1.00,z-axis=1174.00
19:10:24.880 -> 13.662 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.880 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1180.00
19:10:24.880 -> 13.673 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.926 -> BATCH-1.43 x-axis=-73.00,y-axis=4.00,z-axis=1176.00
19:10:24.926 -> 13.685 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.926 -> BATCH-1.43 x-axis=-65.00,y-axis=-4.00,z-axis=1180.00
19:10:24.926 -> 13.696 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.926 -> BATCH-1.43 x-axis=-57.00,y-axis=-1.00,z-axis=1172.00
19:10:24.926 -> 13.707 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.926 -> BATCH-1.43 x-axis=-69.00,y-axis=7.00,z-axis=1174.00
19:10:24.926 -> 13.719 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.946 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1180.00
19:10:24.946 -> 13.730 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.946 -> BATCH-1.43 x-axis=-72.00,y-axis=-5.00,z-axis=1179.00
19:10:24.946 -> 13.741 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.980 -> BATCH-1.43 x-axis=-74.00,y-axis=3.00,z-axis=1179.00
19:10:24.980 -> 13.753 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.980 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1171.00
19:10:24.980 -> 13.764 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.980 -> BATCH-1.43 x-axis=-69.00,y-axis=1.00,z-axis=1171.00
19:10:24.980 -> 13.775 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:24.980 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1176.00
19:10:24.980 -> 13.787 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.013 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1175.00
19:10:25.013 -> 13.798 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.013 -> BATCH-1.43 x-axis=-77.00,y-axis=7.00,z-axis=1174.00
19:10:25.013 -> 13.809 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.046 -> BATCH-1.43 x-axis=-77.00,y-axis=-1.00,z-axis=1174.00
19:10:25.046 -> 13.820 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.046 -> BATCH-1.43 x-axis=-72.00,y-axis=3.00,z-axis=1176.00
19:10:25.046 -> 13.832 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.046 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1174.00
19:10:25.046 -> 13.843 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.046 -> BATCH-1.43 x-axis=-68.00,y-axis=1.00,z-axis=1176.00
19:10:25.046 -> 13.854 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.079 -> BATCH-1.43 x-axis=-68.00,y-axis=1.00,z-axis=1177.00
19:10:25.079 -> 13.866 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.079 -> BATCH-1.43 x-axis=-74.00,y-axis=-2.00,z-axis=1180.00
19:10:25.079 -> 13.877 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.113 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1180.00
19:10:25.113 -> 13.888 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.113 -> BATCH-1.43 x-axis=-68.00,y-axis=-1.00,z-axis=1176.00
19:10:25.113 -> 13.900 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.113 -> BATCH-1.43 x-axis=-74.00,y-axis=6.00,z-axis=1177.00
19:10:25.113 -> 13.911 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.113 -> BATCH-1.43 x-axis=-71.00,y-axis=-5.00,z-axis=1176.00
19:10:25.113 -> 13.922 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.146 -> BATCH-1.43 x-axis=-69.00,y-axis=0.00,z-axis=1171.00
19:10:25.146 -> 13.934 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.146 -> BATCH-1.43 x-axis=-82.00,y-axis=7.00,z-axis=1182.00
19:10:25.146 -> 13.945 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.179 -> BATCH-1.43 x-axis=-79.00,y-axis=7.00,z-axis=1176.00
19:10:25.179 -> 13.956 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.179 -> BATCH-1.43 x-axis=-74.00,y-axis=1.00,z-axis=1175.00
19:10:25.179 -> 13.968 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.212 -> BATCH-1.43 x-axis=-77.00,y-axis=6.00,z-axis=1180.00
19:10:25.212 -> 13.979 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.212 -> BATCH-1.43 x-axis=-74.00,y-axis=7.00,z-axis=1177.00
19:10:25.212 -> 13.990 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.212 -> BATCH-1.43 x-axis=-72.00,y-axis=3.00,z-axis=1176.00
19:10:25.212 -> 14.001 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.212 -> BATCH-1.43 x-axis=-77.00,y-axis=4.00,z-axis=1171.00
19:10:25.245 -> 14.013 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.245 -> BATCH-1.43 x-axis=-72.00,y-axis=4.00,z-axis=1179.00
19:10:25.245 -> 14.024 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.245 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1169.00
19:10:25.279 -> 14.035 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.279 -> BATCH-1.43 x-axis=-68.00,y-axis=4.00,z-axis=1174.00
19:10:25.279 -> 14.046 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.279 -> BATCH-1.43 x-axis=-68.00,y-axis=-1.00,z-axis=1171.00
19:10:25.279 -> 14.058 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.279 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1176.00
19:10:25.279 -> 14.069 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.279 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1176.00
19:10:25.312 -> 14.080 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.312 -> BATCH-1.43 x-axis=-74.00,y-axis=7.00,z-axis=1176.00
19:10:25.312 -> 14.092 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.312 -> BATCH-1.43 x-axis=-73.00,y-axis=-2.00,z-axis=1183.00
19:10:25.346 -> 14.103 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.346 -> BATCH-1.43 x-axis=-74.00,y-axis=-1.00,z-axis=1177.00
19:10:25.346 -> 14.114 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.346 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1180.00
19:10:25.346 -> 14.126 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.346 -> BATCH-1.43 x-axis=-73.00,y-axis=1.00,z-axis=1176.00
19:10:25.346 -> 14.137 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.346 -> BATCH-1.43 x-axis=-72.00,y-axis=1.00,z-axis=1175.00
19:10:25.378 -> 14.148 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.378 -> BATCH-1.43 x-axis=-71.00,y-axis=0.00,z-axis=1168.00
19:10:25.378 -> 14.160 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.378 -> BATCH-1.43 x-axis=-74.00,y-axis=4.00,z-axis=1177.00
19:10:25.411 -> 14.171 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.411 -> BATCH-1.43 x-axis=-77.00,y-axis=6.00,z-axis=1180.00
19:10:25.411 -> 14.182 [D] writeRecord: bufferPointer: 0, batchPointer: 0, _bufferCeiling: 0
19:10:25.411 -> BATCH-1.43 x-axis=-72.00,y-axis=7.00,z-axis=1174.00
19:10:25.411 -> 14.193 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
19:10:25.411 -> 14.200 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
19:10:25.411 -> 14.209 [D] Writing batch, batchpointer: 0, size 50
19:10:25.411 -> 14.212 [D] Writing to http://192.168.8.155:8086/write?db=dev1&precision=ms
19:10:25.444 -> 14.219 [D] Sending:
19:10:25.444 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1171.00 1606302624897
19:10:25.444 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1171.00 1606302624902
19:10:25.444 -> BATCH-1.43 x-axis=-64.00,y-axis=-1.00,z-axis=1174.00 1606302624913
19:10:25.478 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1180.00 1606302624924
19:10:25.478 -> BATCH-1.43 x-axis=-73.00,y-axis=4.00,z-axis=1176.00 1606302624936
19:10:25.478 -> BATCH-1.43 x-axis=-65.00,y-axis=-4.00,z-axis=1180.00 1606302624947
19:10:25.478 -> BATCH-1.43 x-axis=-57.00,y-axis=-1.00,z-axis=1172.00 1606302624958
19:10:25.478 -> BATCH-1.43 x-axis=-69.00,y-axis=7.00,z-axis=1174.00 1606302624970
19:10:25.478 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1180.00 1606302624981
19:10:25.478 -> BATCH-1.43 x-axis=-72.00,y-axis=-5.00,z-axis=1179.00 1606302624992
19:10:25.478 -> BATCH-1.43 x-axis=-74.00,y-axis=3.00,z-axis=1179.00 1606302625004
19:10:25.511 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1171.00 1606302625015
19:10:25.511 -> BATCH-1.43 x-axis=-69.00,y-axis=1.00,z-axis=1171.00 1606302625026
19:10:25.511 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1176.00 1606302625038
19:10:25.511 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1175.00 1606302625049
19:10:25.544 -> BATCH-1.43 x-axis=-77.00,y-axis=7.00,z-axis=1174.00 1606302625060
19:10:25.544 -> BATCH-1.43 x-axis=-77.00,y-axis=-1.00,z-axis=1174.00 1606302625072
19:10:25.544 -> BATCH-1.43 x-axis=-72.00,y-axis=3.00,z-axis=1176.00 1606302625083
19:10:25.544 -> BATCH-1.43 x-axis=-72.00,y-axis=-1.00,z-axis=1174.00 1606302625094
19:10:25.544 -> BATCH-1.43 x-axis=-68.00,y-axis=1.00,z-axis=1176.00 1606302625106
19:10:25.544 -> BATCH-1.43 x-axis=-68.00,y-axis=1.00,z-axis=1177.00 1606302625117
19:10:25.544 -> BATCH-1.43 x-axis=-74.00,y-axis=-2.00,z-axis=1180.00 1606302625128
19:10:25.577 -> BATCH-1.43 x-axis=-73.00,y-axis=3.00,z-axis=1180.00 1606302625139
19:10:25.577 -> BATCH-1.43 x-axis=-68.00,y-axis=-1.00,z-axis=1176.00 1606302625151
19:10:25.577 -> BATCH-1.43 x-axis=-74.00,y-axis=6.00,z-axis=1177.00 1606302625162
19:10:25.577 -> BATCH-1.43 x-axis=-71.00,y-axis=-5.00,z-axis=1176.00 1606302625174
19:10:25.611 -> BATCH-1.43 x-axis=-69.00,y-axis=0.00,z-axis=1171.00 1606302625185
19:10:25.611 -> BATCH-1.43 x-axis=-82.00,y-axis=7.00,z-axis=1182.00 1606302625196
19:10:25.611 -> BATCH-1.43 x-axis=-79.00,y-axis=7.00,z-axis=1176.00 1606302625207
19:10:25.611 -> BATCH-1.43 x-axis=-74.00,y-axis=1.00,z-axis=1175.00 1606302625219
19:10:25.611 -> BATCH-1.43 x-axis=-77.00,y-axis=6.00,z-axis=1180.00 1606302625230
19:10:25.611 -> BATCH-1.43 x-axis=-74.00,y-axis=7.00,z-axis=1177.00 1606302625241
19:10:25.611 -> BATCH-1.43 x-axis=-72.00,y-axis=3.00,z-axis=1176.00 1606302625253
19:10:25.611 -> BATCH-1.43 x-axis=-77.00,y-axis=4.00,z-axis=1171.00 1606302625264
19:10:25.644 -> BATCH-1.43 x-axis=-72.00,y-axis=4.00,z-axis=1179.00 1606302625275
19:10:25.644 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1169.00 1606302625286
19:10:25.644 -> BATCH-1.43 x-axis=-68.00,y-axis=4.00,z-axis=1174.00 1606302625298
19:10:25.644 -> BATCH-1.43 x-axis=-68.00,y-axis=-1.00,z-axis=1171.00 1606302625309
19:10:25.677 -> BATCH-1.43 x-axis=-69.00,y-axis=3.00,z-axis=1176.00 1606302625320
19:10:25.677 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1176.00 1606302625332
19:10:25.677 -> BATCH-1.43 x-axis=-74.00,y-axis=7.00,z-axis=1176.00 1606302625343
19:10:25.677 -> BATCH-1.43 x-axis=-73.00,y-axis=-2.00,z-axis=1183.00 1606302625354
19:10:25.677 -> BATCH-1.43 x-axis=-74.00,y-axis=-1.00,z-axis=1177.00 1606302625366
19:10:25.677 -> BATCH-1.43 x-axis=-72.00,y-axis=6.00,z-axis=1180.00 1606302625377
19:10:25.677 -> BATCH-1.43 x-axis=-73.00,y-axis=1.00,z-axis=1176.00 1606302625388
19:10:25.710 -> BATCH-1.43 x-axis=-72.00,y-axis=1.00,z-axis=1175.00 1606302625399
19:10:25.710 -> BATCH-1.43 x-axis=-71.00,y-axis=0.00,z-axis=1168.00 1606302625411
19:10:25.710 -> BATCH-1.43 x-axis=-74.00,y-axis=4.00,z-axis=1177.00 1606302625422
19:10:25.710 -> BATCH-1.43 x-axis=-77.00,y-axis=6.00,z-axis=1180.00 1606302625433
19:10:25.710 -> BATCH-1.43 x-axis=-72.00,y-axis=7.00,z-axis=1174.00 1606302625445
19:10:25.710 -> 
19:10:25.777 -> 14.575 [D] HTTP status code - 204
19:10:25.777 -> 14.576 [D] Dropped batch, batchpointer: 1
19:10:25.777 -> 14.576 [D] Success: 1, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0
19:10:25.777 -> 14.579 [D] Buffer empty
19:10:25.777 -> Wait 10s
`


[test_101.zip](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/files/5597169/test_101.zip)

**Comment by vlastahajek** [comment]
Thanks for the detailed info. Write is done in ~300ms. 
I see the line `float networks = WiFi.scanNetworks();`, which probably delays the loop. 
When removed, if it is still slow, try to measure time it takes to get 50 measurements from sensor, but this shouldn't be problem.

**Comment by kmf909** [comment]
is 300ms can be improve? after comment the `float networks = WiFi.scanNetworks();`, i manage to send 40-48 data on each batch send,  but due to send the data taking 300ms-500ms the data stored every second is varied around 40-48 data/second. how can i send data every 10 second with total data point 500. do i need to adjust the timestamp to manual.

**Comment by vlastahajek** [comment]
The lag 300-500ms is the time it takes to process data by ESP network layer + network latency+ processing time on the server. This library cannot improve this.
You can play with batch size to see what will be most efficient setting. Just acquire data  and write it to the client in the loop. Implicit batching of client will take care of  sending data when the batch is full, as in the example bellow :
```cpp
void loop() {
    xl.readXYZTData(XValue, YValue, ZValue, Temperature);
    xaxis=float(XValue);
    yaxis=float(YValue);
    zaxis=float(ZValue);
    Point sensorNetworks("BATCH-1.43");
    sensorNetworks.addField("x-axis", xaxis);
    sensorNetworks.addField("y-axis", yaxis);
    sensorNetworks.addField("z-axis", zaxis);
    if (!client.writePoint(sensorNetworks)) {
        Serial.print("InfluxDB write failed: "); 
        Serial.println(client.getLastErrorMessage()); 
    } 
}
```

**Comment by vlastahajek** [comment]
Also, it will be better to comment again enabling debug output in the InfluxDBClient.cpp, serial prints also slow down processing.
