### ISSUE TITLE
configTzTime is not compatible with ESP8266

### ISSUE THREAD

**Issue by ignis-silver** [tobiasschuerg/InfluxDB-Client-for-Arduino#126]
Hi,

configTzTime function used in the helpers.h timeSync is not compatible with the ESP8266 module. This will work only on the ESP32 module.

In the current situation, every compilation with the ESP8266 will produce compiling error:

> Arduino\libraries\ESP8266_Influxdb\src\util\helpers.cpp:32:57: error: 'configTzTime' was not declared in this scope
>    configTzTime(tzInfo,ntpServer1, ntpServer2, ntpServer3);
>                                                          ^
> exit status 1

I replaced part of the code with an older solution (in the helper.cpp), which allowed to compile and run on ESP8266 module.
```
configTime(0, 0, ntpServer1, ntpServer2);
  setenv("TZ", tzInfo, 1);
```
After applying this quick fix, I managed to upload the data to the InfluxDB database version 2.0.2 with my ESP8266 module.

Here are the links of the time functions on the ESP8266:
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/time.cpp#L114

And ESP32:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-time.c#L65

**Comment by vlastahajek** [comment]
@ignis-silver, you haven't provided info about ESP8266 SDK version, but you most probably have an obsolete version. This library requires ESP8266 Arduino SDK >=2.7.0.

**Comment by drf5n** [comment]
You could try this format per 

https://github.com/esp8266/Arduino/blob/732db594929965c7d298b6257fa74cfbd1be0398/cores/esp8266/time.cpp#L219

```
  // TZ string setup
  // TZ string information:
  // https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
  const char *TZstr = "CST+6CDT,M3.2.0/2,M11.1.0/2";
  configTzTime(TZstr, "pool.ntp.org");

```




> https://github.com/esp8266/Arduino/blob/master/cores/esp8266/time.cpp#L114

Did you try this format:
