### ISSUE TITLE
Connection refused ESP32

### ISSUE THREAD

**Issue by mlyngsoe** [tobiasschuerg/InfluxDB-Client-for-Arduino#128]
Hi

I'm trying to use the basic example to send RSSI to influxdb. I keep getting "connection refused" error.
I have double checked that all input (bucket, token etc are correct). I'm using company ID and not name.

I uncommented line 44 in the InfluxDBClient.cpp file and received this error message

```
Writing: wifi_status,device=ESP32,SSID=MogM rssi=-77i
76.807 [D] writeRecord: bufferPointer: 3, batchPointer: 3, _bufferCeiling: 5
76.808 [D] Flushing buffer: is oversized true, is timeout false, is buffer full true
76.815 [D] Writing batch, batchpointer: 3, size 1
76.819 [D] Writing to https://westeurope-1.azure.cloud2.influxdata.com/api/v2/write?org=1deaf2b10314767f&bucket=home
76.829 [D] Sending:
wifi_status,device=ESP32,SSID=MogM rssi=-84i

76.952 [D] HTTP status code - -1
76.953 [E] Error - connection refused
76.953 [D] Leaving data in buffer for retry, retryInterval: 0
76.953 [D] Success: 0, _bufferPointer: 3, _batchPointer: 3, _writeBuffer[_bufferPointer]_0x3ffcdbc0
InfluxDB write failed: connection refused
Wait 10s
```

Is there something I'm missing?
Thanks in advance, Martin 

Specs:
 - Library Version: 3.6.1
 - Board/ESP chip: ESP32 - WROOM-32, DOIT

**Comment by vlastahajek** [comment]
@mlyngsoe, this could be a problem with establishing the TLS connection.  However, AFAIK, ESP32 doesn't validate server certificates. 
What is your ESP 32 Board SDK version?
To know more, enable SSL debug in board configuration, reflash, and paste the output here, please
Also, use the triple backquotes for entering preformatted multiple lines text, when possible.

**Comment by mlyngsoe** [comment]
SDK version is: v3.2.3-14-gd3e562907

I'm not sure how to enable SSL debug. Is it something that can be done with Arduino IDE?

**Comment by vlastahajek** [comment]
ESP32 SDK Arduino has latest stable version 1.0.4. You are probably referring to underlying ESP-IDF SDK. From it I can guess, you have 1.0.4.
I was confused by large set of board debug options for ESP8266. ESP32 has only the ability to set debug level. 
So, set it to Debug, please. 
I would also recommend to start from the [SecureWrite example](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/examples/SecureWrite/SecureWrite.ino), as it is better example for secured connections.

![image](https://user-images.githubusercontent.com/29980246/102528265-9ee8cf00-409e-11eb-9d1b-7231696a4be7.png)

**Comment by mlyngsoe** [comment]
I ran again with the debugger enabled and this is what I got
I will also try to have a look at the example you suggested

`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
v3.2.3-14-gd3e562907
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 2 - STA_START
[I][WiFiMulti.cpp:84] addAP(): [WIFI][APlistAdd] add SSID: MogM
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 1 - SCAN_DONE
[I][WiFiMulti.cpp:114] run(): [WIFI] scan done
[I][WiFiMulti.cpp:119] run(): [WIFI] 5 networks found
[D][WiFiMulti.cpp:149] run():  --->   0: [11][98:DE:D0:71:35:0D] MogM (-74) *
[D][WiFiMulti.cpp:151] run():        1: [1][A0:8E:78:6E:D8:D8] CableBox-D8D3 (-86) *
[D][WiFiMulti.cpp:151] run():        2: [1][54:64:D9:C2:E7:B6] HomeBox-E7B0_2.4G (-90) *
[D][WiFiMulti.cpp:151] run():        3: [11][88:41:FC:B8:D0:BD] Waoo4920_4R79 (-91) *
[D][WiFiMulti.cpp:151] run():        4: [1][A4:B1:E9:AF:04:2F] TelenorAF042F (-92) *
[I][WiFiMulti.cpp:160] run(): [WIFI] Connecting BSSID: 98:DE:D0:71:35:0D SSID: MogM Channal: 11 (-74)
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 4 - STA_CONNECTED
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 7 - STA_GOT_IP
[D][WiFiGeneric.cpp:381] _eventCallback(): STA IP: 192.168.1.33, MASK: 255.255.255.0, GW: 192.168.1.1
[I][WiFiMulti.cpp:174] run(): [WIFI] Connecting done.
[D][WiFiMulti.cpp:175] run(): [WIFI] SSID: MogM
[D][WiFiMulti.cpp:176] run(): [WIFI] IP: 192.168.1.33
[D][WiFiMulti.cpp:177] run(): [WIFI] MAC: 98:DE:D0:71:35:0D
[D][WiFiMulti.cpp:178] run(): [WIFI] Channel: 11
Syncing time.
Synchronized time: Thu Dec 17 19:54:18 2020

2.814 [D] Init
2.814 [D]  Library version: 3.6.1
2.814 [D]  Server url: https://westeurope-1.azure.cloud2.influxdata.com
2.817 [D]  Org: 1deaf2b10314767f
2.820 [D]  Bucket: home
2.822 [D]  Token: Yl9mQKH7xi3VPFoaCAsc6S1DkSmQbsNDbztMLaM6fvKSvOvVtyhefQ7A2jfPUwNc0t6Bc-QiOYUBzWqMx3wbjA==
2.831 [D]  DB version: 2
2.833 [D]  Connection reuse: false
2.837 [D] setUrls
2.838 [D]  writeUrl: https://westeurope-1.azure.cloud2.influxdata.com/api/v2/write?org=1deaf2b10314767f&bucket=home
2.848 [D]  queryUrl: https://westeurope-1.azure.cloud2.influxdata.com/api/v2/query?org=1deaf2b10314767f
2.858 [D] Validating connection to https://westeurope-1.azure.cloud2.influxdata.com/health
[D][HTTPClient.cpp:276] beginInternal(): host: westeurope-1.azure.cloud2.influxdata.com port: 443 url: /health
[E][ssl_client.cpp:33] _handle_error(): [start_ssl_client():199]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -9984
[D][HTTPClient.cpp:1018] connect(): failed connect to westeurope-1.azure.cloud2.influxdata.com:443
[W][HTTPClient.cpp:1318] returnError(): error(-1): connection refused
3.018 [E] Error - connection refused
[D][HTTPClient.cpp:383] disconnect(): tcp is closed


Writing: wifi_status,device=ESP32,SSID=MogM rssi=-69i
3.031 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
3.038 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
3.045 [D] Writing batch, batchpointer: 0, size 1
3.049 [D] Writing to https://westeurope-1.azure.cloud2.influxdata.com/api/v2/write?org=1deaf2b10314767f&bucket=home
[D][HTTPClient.cpp:276] beginInternal(): host: westeurope-1.azure.cloud2.influxdata.com port: 443 url: /api/v2/write?org=1deaf2b10314767f&bucket=home
3.073 [D] Sending:
wifi_status,device=ESP32,SSID=MogM rssi=-69i

[E][ssl_client.cpp:33] _handle_error(): [start_ssl_client():199]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -9984
[D][HTTPClient.cpp:1018] connect(): failed connect to westeurope-1.azure.cloud2.influxdata.com:443
[W][HTTPClient.cpp:1318] returnError(): error(-1): connection refused
3.213 [D] HTTP status code - -1
3.216 [E] Error - connection refused
[D][HTTPClient.cpp:383] disconnect(): tcp is closed

[D] Leaving data in buffer for retry, retryInterval: 0
3.229 [D] Success: 0, _bufferPointer: 1, _batchPointer: 0, _writeBuffer[_bufferPointer]_0x0
InfluxDB write failed: connection refused
Wait 10s
Writing: wifi_status,device=ESP32,SSID=MogM rssi=-65i
13.242 [D] writeRecord: bufferPointer: 2, batchPointer: 0, _bufferCeiling: 2
13.242 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
13.250 [D] Writing batch, batchpointer: 0, size 1
13.254 [D] Writing to https://westeurope-1.azure.cloud2.influxdata.com/api/v2/write?org=1deaf2b10314767f&bucket=home
[D][HTTPClient.cpp:276] beginInternal(): host: westeurope-1.azure.cloud2.influxdata.com port: 443 url: /api/v2/write?org=1deaf2b10314767f&bucket=home
13.277 [D] Sending:
wifi_status,device=ESP32,SSID=MogM rssi=-69i

[E][ssl_client.cpp:33] _handle_error(): [start_ssl_client():199]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -9984
[D][HTTPClient.cpp:1018] connect(): failed connect to westeurope-1.azure.cloud2.influxdata.com:443
[W][HTTPClient.cpp:1318] returnError(): error(-1): connection refused
13.408 [D] HTTP status code - -1
13.411 [E] Error - connection refused
[D][HTTPClient.cpp:383] disconnect(): tcp is closed

[D] Leaving data in buffer for retry, retryInterval: 0
13.424 [D] Success: 0, _bufferPointer: 2, _batchPointer: 0, _writeBuffer[_bufferPointer]_0x0
InfluxDB write failed: connection refused
Wait 10s
`

**Comment by mlyngsoe** [comment]
Just a follow up on the secure-write example. That is in fact the one I'm using and have only changed input for wifi and influxDB token etc.

**Comment by vlastahajek** [comment]
Problem is that Azure cloud uses a different CA than AWS cloud, which CA certificate is part of this library.
As ESP32 doesn't need to verify the server certificate, an easy workaround is to omit the certificate in the constructor.
Just replace
```cpp
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN, InfluxDbCloud2CACert);
``` 
with
```cpp
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN);
```

**Comment by mlyngsoe** [comment]
Fantastic, that did the trick :) thanks for the quick support :)
