### ISSUE TITLE
HTTPS write without certificate

### ISSUE THREAD

**Issue by mbc99** [tobiasschuerg/InfluxDB-Client-for-Arduino#130]
Hi there,

I'm trying to upload measurments into a INFLUXDB which I know is working (it's 100% the fault of my code).

The uploads are done via https but without certificates. To put it in prespective here's how I have configured that same server on Node-Red:
![image](https://user-images.githubusercontent.com/44815501/102996932-409b7080-4524-11eb-9376-3ae909743172.png)
As you can see no password and no certificate. This works perfectly.

So in the code I have set it up like this:
```
#define INFLUXDB_HOST "https://XD.duckdns.org:8086"
#define INFLUXDB_DATABASE "CO2"
#define INFLUXDB_USER ""
#define INFLUXDB_PASS ""
#define DEVICE_NAME "esp"
```
```
Sending data...
60.000 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
60.001 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
60.004 [D] Writing batch, batchpointer: 0, size 1
60.009 [D] Init
60.010 [D]  Library version: 3.6.1
60.013 [D]  Server url: https://XD.duckdns.org:8086
60.018 [D]  Org: 
60.019 [D]  Bucket: CO2
60.022 [D]  Token:
60.023 [D]  DB version: 1
60.026 [D]  Connection reuse: false
60.029 [D] setUrls
60.030 [D]  writeUrl: https://XD.duckdns.org:8086/write?db=CO2
60.036 [D]  queryUrl: https://XD.duckdns.org:8086/api/v2/query
60.043 [D] probeMaxFragmentLength to caleino.duckdns.org:8086
60.323 [D]  MFLN:no
60.324 [D] Writing to https://XD.duckdns.org:8086/write?db=CO2
60.325 [D] Sending:
esp CO2=888i,Temperature=29i

60.435 [D] HTTP status code - -1
60.436 [E] Error - connection failed
60.436 [D] Leaving data in buffer for retry, retryInterval: 0
60.437 [D] Success: 0, _bufferPointer: 1, _batchPointer: 0, _writeBuffer[_bufferPointer]_0
InfluxDB write failed: connection failed
```

Do I have to use the secure write even though I'm ussing InfluxDB v1 and no certificate on the client side?

**Comment by vlastahajek** [comment]
@mbc99, you need to configure trust for the server certificate. I guess you use ESP8266. You have to either specify the server certificate or its SHA1 fingerprint and synchronize time (both shown in the SecureWrite example), or you can simply call `client.setInsecure(true)`.

**Comment by mbc99** [comment]
> @mbc99, you need to configure trust for the server certificate. I guess you use ESP8266. You have to either specify the server certificate or its SHA1 fingerprint and synchronize time (both shown in the SecureWrite example), or you can simply call `client.setInsecure(true)`.

Using influx.setInsecure(true); change the error message but it still doesn't work:
```
Sending data...
60.000 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
60.001 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
60.004 [D] Writing batch, batchpointer: 0, size 1
60.009 [D] Init
60.010 [D]  Library version: 3.6.1
60.013 [D]  Server url: https://caleino.duckdns.org:8086
60.018 [D]  Org:
60.020 [D]  Bucket: CO2
60.022 [D]  Token: 
60.023 [D]  DB version: 1
60.026 [D]  Connection reuse: false
60.029 [D] setUrls
60.031 [D]  writeUrl: https://caleino.duckdns.org:8086/write?db=CO2
60.036 [D]  queryUrl: https://caleino.duckdns.org:8086/api/v2/query
60.043 [D] probeMaxFragmentLength to caleino.duckdns.org:8086
60.260 [D]  MFLN:no
60.262 [D] Writing to https://caleino.duckdns.org:8086/write?db=CO2
60.262 [D] Sending:
esp CO2=1613i,Temperature=24i

61.645 [D] HTTP status code - 204
61.647 [D] Dropped batch, batchpointer: 1
61.647 [D] Success: 1, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0
61.649 [D] Buffer empty
```

Will take a look at the SecureWrite example. But I don't understand why I need the certificate in this case while NodeRed doesn't have a problem with not giving a certificate.

**Comment by vlastahajek** [comment]
> Using influx.setInsecure(true); change the error message but it still doesn't work:

What error do you mean? I see the response code 204 in your log, which means success:

> 60.262 [D] Sending:
> esp CO2=1613i,Temperature=24i
> 
> 61.645 [D] HTTP status code - 204

> Will take a look at the SecureWrite example. But I don't understand why I need the certificate in this case while NodeRed doesn't have a problem with not giving a certificate.

Different platforms have different security environments. Your server has a certificate signed by a well-known authority, which is trusted by most platforms. However, ESPs have low memory available, so it cannot have a trusted certificates folder and you have to configure trust manually.
