### ISSUE TITLE
Update CA Certificate

### ISSUE THREAD

**Issue by kARTechnology** [tobiasschuerg/InfluxDB-Client-for-Arduino#131]
From 25 Dec 2020 the connection is failing due to invalid CA Certificate.

After setting up a custom certificate with updated version from https://us-central1-1.gcp.cloud2.influxdata.com, issue is solved.

`
const char InfluxDbCloud2CACertUpdated[] PROGMEM =  R"EOF(
-----BEGIN CERTIFICATE-----
MIIFUzCCBDugAwIBAgISBBlo+DzzLIOcoOorJTtZI2xdMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMDEyMjUwMzUwNDVaFw0yMTAzMjUwMzUwNDVaMDIxMDAuBgNVBAMT
J3VzLWNlbnRyYWwxLTEuZ2NwLmNsb3VkMi5pbmZsdXhkYXRhLmNvbTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBALrlUjMzOF2cQ+Uj2Im6ACnvfzAXgMxC
rZqCvxdP3S0qurAIZGtK3XCLNERDnhR8vTlmKcVh4pjT+5AjscOrRsEaKC6hQ3L+
h1vyJMQWc+mPCd4Yb6jd7J54miPKIEml86W859HtnvEfzkr1bcp+We22AwOTzc/v
KsoomHWmrWuxnYoj9H+uU1rvl86IJ595he/4VU+oiIozUPO9kMSxvkKv92JnpWFv
JHZG7MMgU/2hGIQVpci+7RJTHyKQOk/gZVqfLwkn8ei0vfQ9rpUKYvUa/5UMdp7S
638YdOY++PjkL3lULZbS2BSCacsi50dOHMBDrtoIc+bSwdYMyKTkP58CAwEAAaOC
AmEwggJdMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUAivaVJw2Uax1pNVK2OHSvAjt
lfkwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEE
STBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUH
MAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wMgYDVR0RBCswKYIndXMtY2VudHJh
bDEtMS5nY3AuY2xvdWQyLmluZmx1eGRhdGEuY29tMEwGA1UdIARFMEMwCAYGZ4EM
AQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0
c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHUAlCC8Ho7VjWyI
cx+CiyIsDdHaTV5sT5Q9YdtOL1hNosIAAAF2mDwepwAABAMARjBEAiAEWdBO3zGU
dYzVhVoueSmbaI5Df6ic3KwDRlzE/T8KgQIgU16ZxXcfbwREuqThKAYJzAMCCyUm
+UC+RblUqeP4Y20AdgD2XJQv0XcwIhRUGAgwlFaO400TGTO/3wwvIAvMTvFk4wAA
AXaYPB6dAAAEAwBHMEUCIB3XbqedhuzC6qGW3TL72E+OEToOuy8zrSTQPbxGDuCY
AiEAukJWgcJainrdPkzwxjhedjgZY2/JpLEpm7/+BXcO9t8wDQYJKoZIhvcNAQEL
BQADggEBAF5W0d0AGxTJOga4Wj1SMGAPMLpy7IYCVXg0KJpmg9dUR5nN5fGH53L3
SRzyonc8Sl3BeEPdkHxo00naUOdEC8xUOhIaWdtDs3j/njQTj0WKaimBWxIvHvvZ
kiUzC0750I3as1pgUxMOVywX75tGlq7Xwz/7uENQka/b2YP3mclzB7P68AJjA0HZ
ZNjQ5yt8OIis4rZOmM5DARmfYsxt7u+p0yFewQgEFM6NM/+tS6gx8Oi4G13v2LI4
JdRm1qNpb+2j+y0LBbZWBVdmOrWp9lFuSok2VBt8PinNgoyV8pHXGOF2VMQ+v5OO
MqLwG7z2UiAeUGlN8KbSFHUEuKSrk3A=
-----END CERTIFICATE-----
)EOF";`

**Comment by vlastahajek** [comment]
[Version 3.7.0](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/tag/3.7.0) brought an updated  InluxDB 2 Cloud root CA certificate that should set trust for all cloud providers till Sep 2021. 
Using just a server certificate for validation is not feasible cause it has only 3 months validation period.
In fact, on ESPs,  you don't have to validate the certificate at all. ESP32 doesn't verify the certificate if no certificate for validation is provided. For ESP8266, there is the method `InfluxDBClient::setInsecure(bool)` to skip certificate validation.

**Comment by kARTechnology** [comment]
@vlastahajek i hope the wiki is updated with this insecure option for esp8266 devices. Thanks.
