### ISSUE TITLE
Problem to write in InfluxDB

### ISSUE THREAD

**Issue by Maggi80** [tobiasschuerg/InfluxDB-Client-for-Arduino#133]
Hello,
i have a InfluxDB running on Raspberry PI3B. Installed for collecting Data from OpenHAB to Visualize it in Grafana. 
This is running well.
With my Accountdata in the Arduino Scetch i get an connection refused. Here are the Lines from Serial Monitor with Debug.

Can anyone see what the Problem is?

> 15:44:49.563 -> 5.208 [D] Init
> 15:44:49.563 -> 5.209 [D]  Library version: 3.7.0
> 15:44:49.563 -> 5.209 [D]  Device : ESP8266
> 15:44:49.601 -> 5.209 [D]  SDK version: 2.7.0
> 15:44:49.601 -> 5.211 [D]  Server url: http://192.168.170.30:8086
> 15:44:49.601 -> 5.215 [D]  Org: 
> 15:44:49.601 -> 5.216 [D]  Bucket: openhab_db
> 15:44:49.601 -> 5.219 [D]  Token: 
> 15:44:49.601 -> 5.221 [D]  DB version: 1
> 15:44:49.601 -> 5.223 [D]  Connection reuse: false
> 15:44:49.601 -> 5.226 [D] setUrls
> 15:44:49.601 -> 5.228 [D]  writeUrl: http://192.168.170.30:8086/write?db=openhab_db&u=openhab&p=openhab
> 15:44:49.601 -> 5.235 [D]  queryUrl: http://192.168.170.30:8086/api/v2/query?&u=openhab&p=openhab
> 15:44:49.601 -> 5.243 [D] Validating connection to http://192.168.170.30:8086/ping?verbose=true&u=openhab&p=openhab
> 15:44:49.632 -> :ref 1
> 15:44:49.632 -> :er -14 0x00000000
> 15:44:49.632 -> :cabrt
> 15:44:49.632 -> :ur 1
> 15:44:49.632 -> :dsrcv 0
> 15:44:49.632 -> :del
> 15:44:49.632 -> 5.276 [E] Error - connection refused
> 15:44:49.632 -> InfluxDB connection failed: connection refused
> 15:44:49.632 -> 5.277 [D] setUrls
> 15:44:49.632 -> 5.277 [D]  writeUrl: http://192.168.170.30:8086/write?db=openhab_db&u=openhab&p=openhab
> 15:44:49.666 -> 5.282 [D]  queryUrl: http://192.168.170.30:8086/api/v2/query?&u=openhab&p=openhab
> 15:44:49.666 -> 5.289 [D]  writeUrl: http://192.168.170.30:8086/write?db=openhab_db&u=openhab&p=openhab&precision=s
> 15:44:49.666 -> 5.298 [D] Reset buffer: writeBuffSize: 3
> 15:44:58.577 -> pm open,type:2 0

**Comment by vlastahajek** [comment]
@Maggi80, thanks for the detailed log.
 - Is OpenHAB running on the same RPI?
- Are you able to connect to the InfluxDB server from a different host, eg. from your computer by entering `http://192.168.170.30:8086/ping?verbose=true&u=openhab&p=openhab` into the web browser?  You should get a simple JSON with the server version number.

**Comment by Maggi80** [comment]
HI vlastahajek,
thanks for your response. I am not a Linux or Raspberry expert, so i am happy with my Installation is running very stable without knowing everything in detail.
I tried to connect the URL you wrote via browser from another desktop PC without success. So i googled about Port and Firewall configuration and found the following commands and tried to scan the port 8086 on the IP and the localhost from the SSH console with different results.
Do i have to change anything?
Thank you!

> [11:19:00] openhabian@openHABianPi:~$ nmap -p 8086 192.168.170.30
> 
> Starting Nmap 7.40 ( https://nmap.org ) at 2021-01-07 11:19 CET
> Nmap scan report for 192.168.170.30
> Host is up (0.00035s latency).
> PORT     STATE  SERVICE
> 8086/tcp closed d-s-n
> 
> Nmap done: 1 IP address (1 host up) scanned in 5.76 seconds
> [11:19:18] openhabian@openHABianPi:~$ nmap -p 8086 localhost
> 
> Starting Nmap 7.40 ( https://nmap.org ) at 2021-01-07 11:19 CET
> Nmap scan report for localhost (127.0.0.1)
> Host is up (0.00052s latency).
> Other addresses for localhost (not scanned): ::1
> PORT     STATE SERVICE
> 8086/tcp open  d-s-n

**Comment by vlastahajek** [comment]
@Maggi80, please, locate the InfluxDB configuration file, usually placed at `/etc/influxdb/influxdb.conf` and check parameter `bind-address`.  If it is different from `::8086` (probably you have `127.0.0.1:8086`, or similar), back it up and open it for editing: `sudo nano /etc/influxdb/influxdb.conf`, and change the value to `::8086`.

**Comment by Maggi80** [comment]
@vlastahajek , thank you that helps me a lot.
I found the file and changed the line in influxdb.conf from:

> bind-address = "localhost:8086"
to
> bind-address = ":8086"

Now i get back a connection with my browser from desktop PC with the URL 

> http://192.168.170.30:8086/ping?verbose=true&u=openhab&p=openhab

> {"version":"1.8.3"}

My RPI 3B runs with OpenHAB 2.5, PIhole, Influxdb, grafana and mosquitto Server on the same RPI without Problems.

Now i will try to connect the ESP8226 again and will give a feedback later.

**Comment by Maggi80** [comment]
Everything is fine. Now i can write into the influxdb. Thx
