### ISSUE TITLE
Missing documentation on how to connect ESP8266 modul to Arduino for this library

### ISSUE THREAD

**Issue by horejsek** [tobiasschuerg/InfluxDB-Client-for-Arduino#135]
I have Arduino Nano and ESP8266 ESP-01 module. I want to use InfluxDB client library but it cannot connect. I did not figure out to which pins I should mount the module, or where I should define it in the code. Whatever I try, I get `esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header`.

**Comment by vlastahajek** [comment]
@horejsek, this library is intended for use when programming directly ESP devices with their Arduino SDKs ([Arduino core for the ESP32](https://github.com/espressif/arduino-esp32) and [Arduino core for ESP8266 WiFi chip](https://github.com/esp8266/Arduino).

Using an ESP device as a WiFi peripheral device is not currently supported.

However, writing to the InfluxDB server is easy.  For writing data to local server you just need to send a single HTTP POST request. See https://docs.influxdata.com/influxdb/v1.8/guides/write_data/ for more details You will probably find many examples how to construct HTTP POST request when using an ESP as a peripheral device.

**Comment by horejsek** [comment]
I see, thanks! Maybe it would be good to make it clear in readme.
