### ISSUE TITLE
Can't query data from server 1.7 without password and no device

### ISSUE THREAD

**Issue by haldi4803** [tobiasschuerg/InfluxDB-Client-for-Arduino#136]
I have a InfluxDB Server 1.7 in a docker without password. So i've modified the connection Client to this:
`InfluxDBClient client("http://192.168.1.2:8086", "ESP");
`
and modified the query:
`  String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"Haldi\" and r._field == \"Temperature\"";
  query += " and r.device == \)";
  query += "|> " + selectorFunction + "()";`

But.... i don't have an r.device field. 

using PC and curl i can easily get my value:
`C:\Users\Haldi>curl -G "http://192.168.1.2:8086/query?pretty=true" --data-urlencode "db=ESP" --data-urlencode "q=SELECT \"Temperature\" FROM \"Haldi\" ORDER by time Desc Limit 1 "
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "Haldi",
                    "columns": [
                        "time",
                        "Temperature"
                    ],
                    "values": [
                        [
                            "2021-02-05T01:11:57.705589234Z",
                            26.9
                        ]
                    ]
                }
            ]
        }
    ]
}
`

So i tought removing the .rdevice query would do the trick...
But asking for:
`  String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"Haldi\" and r._field == \"Temperature\"";
  query += "|> " + selectorFunction + "()";
`
results in:
`03:59:18.692 -> ==== max ====
03:59:18.692 -> Querying with: from(bucket: "ESP") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature"|> max()
03:59:18.692 -> Query result error: {"error":"loc 1:45-1:126: expected RPAREN, got EOF"}
03:59:18.692 -> 
03:59:18.692 -> ==== mean ====
03:59:18.692 -> Querying with: from(bucket: "ESP") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature"|> mean()
03:59:18.739 -> Query result error: {"error":"loc 1:45-1:127: expected RPAREN, got EOF"}
03:59:18.739 -> 
03:59:18.739 -> ==== min ====
03:59:18.739 -> Querying with: from(bucket: "ESP") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature"|> min()
03:59:20.013 -> Query result error: {"error":"loc 1:45-1:126: expected RPAREN, got EOF"}
03:59:20.013 -> 
03:59:20.013 -> Wait 10s
`
I've been at this for over 3 hours and even tried some older scripts but i just can't get it to ready the values i want....
I simply need the last temperature value posted... nothing more... but it just doesn't want to work. I'm certain it's just some configuration error on my side but i just can't see where.

**Comment by vlastahajek** [comment]
@haldi4803, There is a syntax error in your Flux query: missing closing parenthesis after the field filter:
`String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"Haldi\" and r._field == \"Temperature\")"; 
query += "|> " + selectorFunction + "()";`

**Comment by haldi4803** [comment]
Ohhhhh......
So that was the closing parenthesis of ` filter(fn: ` which comes after the` and r.device == \""  DEVICE  "\")";`
Arduino is one of the worst editors. I really should think about switching to platformio.

Uhm... I can't really find much about "Query result error: Parsing error, row has different number of columns than table: 8 vs 0"

`17:01:46.569 -> Connecting to wifi
17:01:48.643 -> Syncing time.
17:01:49.162 -> Synchronized time: Fri Feb  5 17:01:47 2021
17:01:49.162 -> 
17:01:49.162 -> Connected to InfluxDB: http://192.168.1.2:8086
17:01:49.162 -> ==== max ====
17:01:49.162 -> Querying with: from(bucket: "ESP") |> range(start: -10h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature")|> max()
17:01:49.258 -> SSID '' with RSSI 0 at 1900-01-00 00:00:00
17:01:49.258 -> SSID '' with RSSI 0 at 1900-01-00 00:00:00
17:01:49.258 -> Query result error: Parsing error, row has different number of columns than table: 8 vs 0
17:01:49.258 -> ==== mean ====
17:01:49.258 -> Querying with: from(bucket: "ESP") |> range(start: -10h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature")|> mean()
17:01:49.353 -> SSID '' with RSSI 0.0
17:01:49.353 -> SSID '' with RSSI 0.0
17:01:49.353 -> Query result error: Parsing error, row has different number of columns than table: 7 vs 0
17:01:49.353 -> ==== min ====
17:01:49.353 -> Querying with: from(bucket: "ESP") |> range(start: -10h) |> filter(fn: (r) => r._measurement == "Haldi" and r._field == "Temperature")|> min()
17:01:49.399 -> SSID '' with RSSI 0 at 1900-01-00 00:00:00
17:01:49.399 -> SSID '' with RSSI 0 at 1900-01-00 00:00:00
17:01:49.399 -> Query result error: Parsing error, row has different number of columns than table: 8 vs 0
17:01:49.399 -> Wait 10s
`
i don't see where there is a table defined, and i don't get how there can be 8 columns.

**Comment by vlastahajek** [comment]
Can you, please, copy here the Flux query result? 
Either by enabling debug in this library sources in `src\query\HttpStreamScanner.cpp` by uncommenting line  30 and paste the console output with it.
Or you can run query using curl: `curl -v  " http://192.168.1.2:8086/api/v2/query" --data-raw "{""dialect"":{""annotations"":[""datatype""],""dateTimeFormat"":""RFC3339Nano"",""delimiter"":"","",""header"":true},""query"":""from(bucket: \\\""ESP\\\"") |> range(start: -10h) |> filter(fn: (r) => r._measurement == \\\""Haldi\\\"") |> max()""}"`

**Comment by haldi4803** [comment]
23:03:31.220 -> Connecting to wifi
23:03:34.040 -> Syncing time.
23:03:34.556 -> Synchronized time: Sun Feb  7 23:03:34 2021
23:03:34.556 -> 
23:03:34.886 -> Connected to InfluxDB: http://192.168.1.2:8086
23:03:34.886 -> Querying with: from(bucket: "ESP") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "Haldi" and (r._field == "Temperature")) |> bottom(n:1)
23:03:34.980 -> 3.867 [D] HttpStreamScanner: chunked: true, size: -1
23:03:34.980 -> 3.867 [D] HttpStreamScanner: line: 163
23:03:34.980 -> 3.867 [D] HttpStreamScanner chunk len: 355
23:03:34.980 -> 3.868 [D] HttpStreamScanner: line: #datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string
23:03:34.980 -> 3.881 [D] HttpStreamScanner: line: #group,false,false,true,true,false,false,true,true
23:03:34.980 -> 0.00
23:03:34.980 -> 3.887 [D] HttpStreamScanner: line: #default,_result,,,,,,,
23:03:34.980 -> 0.00
23:03:34.980 -> 3.893 [D] HttpStreamScanner: line: ,result,table,_start,_stop,_time,_value,_field,_measurement
23:03:34.980 -> Query result error: Parsing error, row has different number of columns than table: 8 vs 0
23:03:34.980 -> Wait 10s

**Comment by vlastahajek** [comment]
Thanks for providing the details. 1.7 sends undesired annotations and it caused problems. I've fixed it in master, so until release,  you can download it manually.
Another way to overcome this is to upgrade InfluxDB to 1.8 (latest 1.8.4), which sends annotations correctly.

**Comment by haldi4803** [comment]
14:53:34.570 -> Syncing time.
14:53:35.090 -> Synchronized time: Mon Feb  8 14:53:32 2021
14:53:35.090 -> 
14:53:35.137 -> Connected to InfluxDB: http://192.168.1.2:8086
14:53:35.137 -> Querying with: from(bucket: "ESP") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "Haldi" and (r._field == "Temperature")) |> bottom(n:1)
14:53:35.231 -> 27.30
14:53:35.231 -> Wait 10s


Thanks a lot!
I was actually waiting with the update until there is a fully working 2.0 Docker for InfluxDB.
