### ISSUE TITLE
PointToLineProtocol should output also additionaly set tags

### ISSUE THREAD

**Issue by pxlfrk** [tobiasschuerg/InfluxDB-Client-for-Arduino#139]
__Proposal:__
I'm using the InfluxDB-Client Library on a ESP8266 in addition with an Telegram-Bot to interact with the device. By sending a request-message to the telegram-bot `/values`, it should pass the sensor-values connected to the esp to the bot.

I have four different data points in my configuration with each 2 tag sets. There isn't any (non-deprecated) way to create a String of a data point including all tag sets right now.

__Current behavior:__
The data point class supports the method `toLineProtocol` and includes the optionally added tags - that's my desired behaviour - but it's deprecated :/

https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/44f4b11fe65d048a10e19687b4a909506f05e16e/src/Point.h#L71-L72

The (regarding to the author) prefered method in the client-class only adds the default-tags, not the optionall added tags for each data point.
https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/5b51bdbbce55c6e11953e74561341ab32191dce0/src/InfluxDbClient.cpp#L538-L540

__Desired behavior:__
Include the optionally configured tag sets.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Serial Output or (in my case) identify different dara points when forwarding their `pointToLineProtocol`-String to a Bot.

Kind regards,
Achim / pxlfrk

**Comment by pxlfrk** [comment]
Any updates?

**Comment by vlastahajek** [comment]
@pxlfrk, do I understand correctly, you are creating a line protocol with custom tags, that are not sent to an InfluxDB server via this library? 
This a use case I didn't expect. :)

**Comment by pxlfrk** [comment]
@vlastahajek Yes and No. I am creating a line protocol string for a number of data points which i hav assigned custom tags. These Custom tags aren't added to the line string. i am using the created line string for logging purposes.

Would be great if they are added of if there is another option to achieve the same result. Hope you get my point!

**Comment by vlastahajek** [comment]
PR #157 removed deprecation of `String Point::toLineProtocol(String includeTags = "")`
