### ISSUE TITLE
Support to https and pass username and password into encripty body

### ISSUE THREAD

**Issue by lets00** [tobiasschuerg/InfluxDB-Client-for-Arduino#14]
Pass username, password and database into URL is dangerous (because this information is not encrypted). Influxdb HTTP API supports usage body to pass username, password and database (see https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/).

Maybe change this lines and add https support can be resolve this issue
https://github.com/tobiasschuerg/ESP8266_Influx_DB/blob/5cd2dcf7bf60e1533dceb9d37b0a33f5c9f2fd01/InfluxDb.cpp#L42

**Comment by tobiasschuerg** [comment]
That's true. However, I'm currently onyl using it in my local network and don't have much time to work on this library. @lets00 feel free to create a pull request.

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
