### ISSUE TITLE
ESP32 SSL connection with error connect(): start_ssl_client: -1

### ISSUE THREAD

**Issue by maxdd** [tobiasschuerg/InfluxDB-Client-for-Arduino#141]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/examples/SecureWrite/SecureWrite.ino
2. Set client.setInsecure(true);
3. Set an InfluxDB server with SSL connection

__Expected behavior:__
Serial should report Serial.print("Connected to InfluxDB: ");

__Actual behavior:__
Serial is reporting Serial.print("InfluxDB connection failed: ");

```
3.758 [D] Validating connection to https://192.168.1.23:8086/health
[V][HTTPClient.cpp:239] beginInternal(): url: https://192.168.1.23:8086/health
[D][HTTPClient.cpp:287] beginInternal(): host: 192.168.1.23 port: 8086 url: /health
[D][HTTPClient.cpp:573] sendRequest(): request type: 'GET' redirCount: 0

[V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 277628
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
[V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
[D][HTTPClient.cpp:1112] connect(): failed connect to 192.168.1.23:8086
[W][HTTPClient.cpp:1411] returnError(): error(-1): connection refused
3.815 [E] Error - connection refused
[D][HTTPClient.cpp:394] disconnect(): tcp is closed

connection refused
```

__Specifications:__
 - Library Version: last on github
 - InfluxDB Version: 2 (latest as of today)
 - Board/ESP chip: ESP32 DevKit C
 - Device Arduino SDK version: Platformio 3.1.0 bundle

What im noticing is that WiFiClientSecure::setInsecure() is not called which might lead start_ssl_client(...) to return -1 due to NULLs condition.

EDIT:
There seems to be an issue with INIT_MODE=setup and TLS certificates which is not starting up the influxdb server.
This could be the reason why i'm getting the error above.
I'll check in few days to report any update

**Comment by maxdd** [comment]
According to https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientInsecure/WiFiClientInsecure.ino

` client.setInsecure();//skip verification`

shall be called.
But looking at https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/commit/6cc2a321737f17502c1b4c94e839f91f843a6603 you're doing it only for ESP8266

**Comment by codegrue** [comment]
How did you get HTTPClient to display the extra internal logs such as this one?

[V][HTTPClient.cpp:239] beginInternal(): url: https://192.168.1.23:8086/health
