### ISSUE TITLE
Request to influxdb to show x values of x columns 

### ISSUE THREAD

**Issue by NewbieMakerLearning** [tobiasschuerg/InfluxDB-Client-for-Arduino#142]
Hello!
Thank you for your library.
I'm using 1.8.4 Influxdb version, a Raspberry pi and a ESP8266 for make querying.
I have the next measurement:

`name: Datos
time                Hic   Hume SSID    Temp device    rssi`
----                ---   ---- ----    ---- ------    ----
`1615279300662009999 17.16 66.8 RedWifi 17.6 esp_DHT22 -34`

I would like to take the Hic, Hume, Temp, rssi  values to use them in my code separately.

I've tryied with that:

`String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -10s) |> filter(fn: (r) => r._measurement == \"Datos\""; 
 query += " and r._field == \"Hume\"";
 query += " and r.device == \""  DEVICE  "\")";`

`Serial.println("==== Listando resultados ====");`
 
  `// Print composed query`
  `Serial.print("Petición con: ");`
  `Serial.println(query);`

  `// Send query to the server and get result`
  `FluxQueryResult result = client.query(query);`

  `// Iterate over rows. Even there is just one row, next() must be called at least once.
  while (result.next())` 
 `{`
    `String ssid_sign = result.getValueByName("SSID").getString();  //Guardamos el valor del SSID en una variable.
    Serial.print ("El SSID es: ");
    Serial.println (ssid_sign);`
    
    `double humed = result.getValueByName("_value").getDouble();
    Serial.print ("La humedad es: ");
    Serial.print (humed);
   Serial.println ("%");`
   
    `double Tempe = result.getValueByName("_value").getDouble();
    Serial.print ("La temperatura es: ");
    Serial.print (Tempe);
    Serial.println ("ºC");`

    `double Hic_ = result.getValueByName("_value").getDouble();
    Serial.print ("El índice de calor es: ");
    Serial.print (Hic_);
    Serial.println ("ºC");`

    `long rssi_sign = result.getValueByName("_value").getLong();
    Serial.print ("La RSSI es: ");
    Serial.print (rssi_sign);
    Serial.println ("dBm");`

And serial monitor show:

 `==== Listando resultados ====
Petición con: from(bucket: "DHT22") |> range(start: -10s) |> filter(fn: (r) => r._measurement == "Datos" and r._field == "Hume" and r.device == "esp_DHT22")
El SSID es: RedWifi
La humedad es: 62.80%
La temperatura es: 62.80ºC
El índice de calor es: 62.80ºC 
La RSSI es: 0dBm
La fecha de la medición es: 2021-03-10 13:12:02
Espera 10s`

I thought was normal because when I write

`result.get.ValueByName("_value").getDouble();`

I'm using the same variable "_value" to Tempe, Humed, Hic_, rssi. I was looking in FluxParser.cpp and I must to replace "_value" for "String columnName" in my case, Temp, Hume, Hic....etc. 

Result  in monitor serial:

`==== Listando resultados ====
Petición con: from(bucket: "DHT22") |> range(start: -10s) |> filter(fn: (r) => r._measurement == "Datos" and r._field == "Hume" and r.device == "esp_DHT22")
El SSID es: RedWifi
La humedad es: 0.00%
La temperatura es: 0.00ºC
El índice de calor es: 0.00ºC
La RSSI es: 0dBm
La fecha de la medición es: 2021-03-10 13:13:02
Espera 10s`

If I change de sketch like that:

`String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -10s)";`

and put "_value" in

'result.get.ValueByName("_value").getDouble();' 

for each variable that I want to take, Tempe, Humed, Hic_, rssi.... Monitor serie show that:

![Captura](https://user-images.githubusercontent.com/79079312/110637944-3f3a2580-81ae-11eb-8b41-d27257ea0329.JPG)

 
I don't know how to get it to show me the measurements in one time.
Can you help me?
Sorry for my bad writing in English.

Thank you for your time.

**Comment by vlastahajek** [comment]
@NewbieMakerLearning, thanks for using this library.

The query result is returned in tabular format. `getValueByName()` simply retrieves any column value by its name.

If you would like to get a value for column `Temp`, you simply call `getValueByName("Temp)`. Zero value means either the column is not in the result set or you asking different type.

The special column name `_value` is presented only if there is just a single field column, i.e. when you filter the specific field in the query, as it is in the original example.

You can modify your query to return all fields:
` from(bucket: "DHT22") |> range(start: -10s) |> filter(fn: (r) => r._measurement == "Datos" and r.device == "esp_DHT22")`

You can also select multiple fields:
` from(bucket: "DHT22") |> range(start: -10s) |> filter(fn: (r) => r._measurement == "Datos" and r.device == "esp_DHT22")
|> filter(fn: (r) =>  r._field == "Hic" or r._field == "Temp" or r._field == "rssi")`


Then you can retrieve your values:
```cpp
double Tempe = result.getValueByName("Temp").getDouble();
Serial.print ("La temperatura es: ");
Serial.print (Tempe);
Serial.println ("ºC");`

double Hic_ = result.getValueByName("Hic").getDouble();
Serial.print ("El índice de calor es: ");
Serial.print (Hic_);
Serial.println ("ºC");`

long rssi_sign = result.getValueByName("rssi").getLong();
Serial.print ("La RSSI es: ");
Serial.print (rssi_sign);
Serial.println ("dBm");
```

I would strongly advise you to install also Chronograf. It allows easily construct and test queries and see your data.
When you tune your query and see its tabular output, you will understand what columns are there. 
Make sure you switch to the `Flux` type in the query builder.

**Comment by NewbieMakerLearning** [comment]
Thank you for reply. I'm going to try.

**Comment by NewbieMakerLearning** [comment]
Hello! I thing what is the problem. Thank you for advise I installed Chronograf, it's useful. I run a script in Chronograf:
`from(bucket: "DHT22/autogen")
  |> range(start: -10s)
  |> filter(fn: (r) => r._measurement == "Datos" and (r._field == "Hic" or r._field == "Hume" or r._field == "Temp" or r._field == "rssi"))`

and Platformio IDE
`String query = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -10s) |> filter(fn: (r) => r._measurement == \"Datos\" and (r._field == \"Hume\") or r._field == \"Temp\" or r._field == \"rssi\" or r._field == \"Hic\")";`

View raw data in Chronograf I see that

![tabla](https://user-images.githubusercontent.com/79079312/110809096-e7222280-8284-11eb-92e7-05ec04792633.JPG)

I thing the problem is the _value column , in all tables is the same, them when I write:
 
    'double humed = result.getValueByName("Hume").getDouble();    
    Serial.print ("La humedad es: ");
    Serial.print (humed);
    Serial.println ("%"); 
    
     double Hic_ = result.getValueByName("Hic").getDouble();
    Serial.print ("El índice de calor es: ");
    Serial.print (Hic_);
    Serial.println ("ºC");

    double Tempe = result.getValueByName("Temp").getDouble();
    Serial.print ("La temperatura es: ");
    Serial.print (Tempe);
    Serial.println ("ºC");

    long rssi_sign = result.getValueByName("rssi").getLong();
    Serial.print ("La RSSI es: ");
    Serial.print (rssi_sign);
    Serial.println ("dBm");`
 
I can't take the value of rssi, Temp, Hume, Hic because is the name of a field and is no a value, is it possible?

If that is true, I must to change the _value column name and I don't know because in my Raspberry I can' see it. 
I wrote:
`show field keys`
`Hic      float`
`Hume     float`
`Temp     float`
`rssi     integer`

`show tag keys from Datos`
`SSID
device`

`show series`

`Datos,SSID=RedWifi,device=esp_DHT22`

But _value column its'n.

> The special column name _value is presented only if there is just a single field column, i.e. when you filter the specific field in the query, as it is in the original example.

If I filter with all fields, should work fine? I thing I've done it with result zero.

I don't know what I'm doing wrong.

**Comment by vlastahajek** [comment]
Ok. I almost forgot about the default behavior. As you can see, Flux returns a single field per row by default.
To read the next value you need to advance to the next row.

However, there is a solution to have fields in the one row. Just add [pivot()](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/) transformation to the end of the flux script:
`from(bucket: "DHT22/autogen") |> range(start: -10s) |> filter(fn: (r) => r._measurement == "Datos" and (r._field == "Hic" or r._field == "Hume" or r._field == "Temp" or r._field == "rssi")) |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")`

**Comment by NewbieMakerLearning** [comment]
Hello!!! 
I'm sorry for the delay in answering. I just  tried with pivot () and....
....
....
THIS WORKS!!!!!!
hahahaha.
Thank you for take time for answering. When I finish my little project, I will share and mention you.
Big hug!!!
