### ISSUE TITLE
Connection refused ESP32

### ISSUE THREAD

**Issue by Bezzeb** [tobiasschuerg/InfluxDB-Client-for-Arduino#144]
Hi

I'm trying to use the basic example to send to influxdb v2. I keep getting "connection refused" error.
I have double checked that all input (bucket, token etc are correct)
After enabling the debug function, I saw that the port 8086 was closed
After enabling the port through the firewall, I got another error

` Writing: wifi_status,device=ESP32,SSID=UPC52DB*** rssi=-51i
[D][HTTPClient.cpp:276] beginInternal(): host: 192.168.0.45 port: 8086 url: /api/v2/write?org=Lodz&bucket=1
[D][HTTPClient.cpp:1025] connect():  connected to 192.168.0.45:8086
[D][HTTPClient.cpp:1158] handleHeaderResponse(): code: 204
[D][WiFiClient.cpp:509] connected(): Disconnected: RES: 0, **ERR: 128**
[D][HTTPClient.cpp:383] disconnect(): **tcp is closed**

  `
I used the code from the library and the second from influxbd

`#include <InfluxDbClient.h>
#include <InfluxDbCloud.h>

// WiFi AP SSID
#define WIFI_SSID "UPC52DB***"
// WiFi password
#define WIFI_PASSWORD "*********"
// InfluxDB v2 server url, e.g. https://eu-central-1-1.aws.cloud2.influxdata.com (Use: InfluxDB UI -> Load Data -> Client Libraries)
#define INFLUXDB_URL "http://192.168.0.45:8086"
// InfluxDB v2 server or cloud API authentication token (Use: InfluxDB UI -> Data -> Tokens -> <select token>)
#define INFLUXDB_TOKEN "wjA49RsXVMa4KU9sGqoo6e68XKPFBKlbkygUvcceEjJ97FEjsEPVpgdFDnd6DGESqW1hQEb1h7noe09PtmvYzw=="
// InfluxDB v2 organization id (Use: InfluxDB UI -> User -> About -> Common Ids )
#define INFLUXDB_ORG "Lodz"
// InfluxDB v2 bucket name (Use: InfluxDB UI ->  Data -> Buckets)
#define INFLUXDB_BUCKET "1"

// Set timezone string according to https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
// Examples:
//  Pacific Time: "PST8PDT"
//  Eastern: "EST5EDT"
//  Japanesse: "JST-9"
//  Central Europe: "CET-1CEST,M3.5.0,M10.5.0/3"
#define TZ_INFO "CET-1CEST,M3.5.0,M10.5.0/3"

// InfluxDB client instance with preconfigured InfluxCloud certificate
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN);

// Data point
Point sensor("wifi_status");

void setup() {
  Serial.begin(115200);

  // Setup wifi
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);

  Serial.print("Connecting to wifi");
  while (wifiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(100);
  }
  Serial.println();

  // Add tags
  sensor.addTag("device", DEVICE);
  sensor.addTag("SSID", WiFi.SSID());

  // Accurate time is necessary for certificate validation and writing in batches
  // For the fastest time sync find NTP servers in your area: https://www.pool.ntp.org/zone/
  // Syncing progress and the time will be printed to Serial.
  timeSync(TZ_INFO, "pool.ntp.org", "time.nis.gov");

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  } else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }
}

void loop() {
  // Clear fields for reusing the point. Tags will remain untouched
  sensor.clearFields();

  // Store measured value into point
  // Report RSSI of currently connected network
  sensor.addField("rssi", WiFi.RSSI());

  // Print what are we exactly writing
  Serial.print("Writing: ");
  Serial.println(sensor.toLineProtocol());

  // If no Wifi signal, try to reconnect it
  if ((WiFi.RSSI() == 0) && (wifiMulti.run() != WL_CONNECTED)) {
    Serial.println("Wifi connection lost");
  }

  // Write point
  if (!client.writePoint(sensor)) {
    Serial.print("InfluxDB write failed: ");
    Serial.println(client.getLastErrorMessage());
  }

  //Wait 10s
  Serial.println("Wait 10s");
  delay(10000);
}`

Tell me what could be the problem?

**Comment by Bezzeb** [comment]
Esp32-Wroom
Arduino-IDE 1.8.5
Red Hat  8.2
Influxdb 2.0.4

**Comment by vlastahajek** [comment]
@Bezzeb, there is nothing wrong. The server replied with the status code 204, which means successful write. The rest are just debugging messages about closed connection because the connection is not retained by default.

**Comment by Bezzeb** [comment]
but i am not getting data in data explore influxdb

**Comment by vlastahajek** [comment]
Do you see the `wifi_status` measurement`?

What is your query to check the data?

**Comment by Bezzeb** [comment]
I see the wi-fi status only in the esp32 log
i installed influxdb
entered name, organization, database name and entered the gui influx
opened the tab "data explore" and there selected my bucket "1"
while there is no data flow

**Comment by vlastahajek** [comment]
You mean that Query Builder in Data Explorer doesn't offer filtering on `wifi_status` measurement? 
If yes, try switching to Raw data view, if there is sth.

**Comment by Bezzeb** [comment]
Thank you very much for your help.
the problem was in the router

**Comment by vlastahajek** [comment]
Interesting, can you share more info? It looked as the server was getting the data.
