### ISSUE TITLE
How to query for a float?

### ISSUE THREAD

**Issue by BernH4** [tobiasschuerg/InfluxDB-Client-for-Arduino#148]
__Expected behavior:__
I have values stored in datatype "float64", i only get 0 back as an result trying with the "QueryAggregated" example.
Why is there no "get" option for float or integer?
I tried with long and double but that doesnt work:
    ```double value = result.getValueByName("value").getDouble();```
Most certainly because of the wrong datatype.

Then it tried to convert to string into a query like that:
Query (split to multiple lines here for readability):
```cpp
String query1 = "from(bucket: \"" INFLUXDB_BUCKET "\") |> range(start: -1h)
|> filter(fn: (r) => r._measurement == \"heizung/pufferspeicher/temp\" and r._field == \"value\")
|> bottom(n:1) 
|> toString()";

String value1 = result1.getValueByIndex("value").getString();

```
That gave me an empty result.

I didnt provide any version info as im sure its an issue of my understanding how this library works but im happy to add them if needed.

**Comment by vlastahajek** [comment]
@BernH4, does the query get results in the Data Explorer/Chronograf? What is the exact dataformat for the `value` column? It will show that if you switch view to raw data.

**Comment by BernH4** [comment]
Thanks you @vlastahajek for your quick reply.
I used grafana data explorer to get my information which did output "value" as the name and "float64" as datatype which i know now is wrong.

I installed chronograf  and through their data explorer i know now the name is "_value" and datatype is "double".

**Comment by vlastahajek** [comment]
And with the correct column name `_value` and verified datatype `double` everything is now working well for you?

**Comment by BernH4** [comment]
Yes, thanks for the awesome library!
