### ISSUE TITLE
Use a gloabl flag to enable/disable debug output

### ISSUE THREAD

**Issue by fake-name** [tobiasschuerg/InfluxDB-Client-for-Arduino#15]
I'm trying to log data at ~50hz, and the serial debugging that is on and not possible to disable is a major performance issue.

Why is it a thing at all?

In general, libraries should never print at all, unless a debug flag is explicitly set.

**Comment by tobiasschuerg** [comment]
Yes, you're right, debug output should be enabled by a flag.

Feel free to submit a pull request.
