### ISSUE TITLE
timeSync() syncs to Jan, 01-1970, if NTP-Server fails

### ISSUE THREAD

**Issue by Prescaler** [tobiasschuerg/InfluxDB-Client-for-Arduino#154]
**Issue**
Hi Tobias,
I'm logging data with an ESP32 and pass them to InfluxDB, by wifi.secure. If timesync to NTP fails, because of the NTP-server not responding, time gets synced to Jan, 01-1970.

**Reason:**
`while (time(nullptr) < 1000000000l && i < 40) {`
The while loop in helpers.cpp, line 37, terminates if GMT: Sunday, 9. September 2001 01:46:40 is reached, or 40 loops have run, whichever occures first.
After NTP-sync failure, tnow in line 45 syncs time to Jan 01.-1970 and reports "Synchronized time:" 2 lines later.
I now have some data in InfluxDB at 1970, which I saved today though. I think, this is not as intended.

Is there any reason for this behavior? Any ideas how to change this?

Regards, Rainer
```
void timeSync(const char *tzInfo, const char* ntpServer1, const char* ntpServer2, const char* ntpServer3) {
  // Accurate time is necessary for certificate validion

  configTzTime(tzInfo,ntpServer1, ntpServer2, ntpServer3);

  // Wait till time is synced
  Serial.print("Syncing time");
  int i = 0;
  while (time(nullptr) < 1000000000l && i < 40) {
    Serial.print(".");
    delay(500);
    i++;
  }
  Serial.println();

  // Show time
  time_t tnow = time(nullptr);
  Serial.print("Synchronized time: ");
  Serial.println(ctime(&tnow));
}
```

**Comment by vlastahajek** [comment]
@Prescaler, `timeSync` is a convenient helper function for time synchronization.  It doesn't guarantee that time is synced.
Mostly, it takes only a few seconds to sync time. You have to choose an NTP server close to your location: https://www.pool.ntp.org/zone/
