### ISSUE TITLE
Not connecting to InfluxDB

### ISSUE THREAD

**Issue by tibmeister** [tobiasschuerg/InfluxDB-Client-for-Arduino#155]
- Library Version: 3.8.0
 - InfluxDB Version: 1.8.4
 - Board/ESP chip: ESP8266
 - Device Arduino SDK version: 3.0.2

Cannot get this device to connect to my InfluxDB.  Lot's of other things are connecting, but this is my first attempt at connecting a ESP8266.  Using Postman and a GET request to http://10.27.200.50:8186/ping?verbose=true returns 200 OK and the proper response.

Serial Debug Output
5.313 [D] Init
5.314 [D]  Library version: 3.8.0
5.314 [D]  Device : ESP8266
5.314 [D]  SDK version: 3.0.2
5.315 [D]  Server url: 10.27.20.50:8186
5.318 [D]  Org: 
5.320 [D]  Bucket: environmental
5.323 [D]  Token: 
5.324 [D]  DB version: 1
5.326 [D]  Connection reuse: false
5.330 [D] setUrls
5.331 [D]  writeUrl: 10.27.20.50:8186/write?db=environmental
5.336 [D]  queryUrl: 10.27.20.50:8186/api/v2/query
5.341 [D] Validating connection to 10.27.20.50:8186/ping?verbose=true
5.347 [E] begin failed
InfluxDB connection failed:

Return from client.validateConnection() is 0

Looking through the code, not sure why this is failing since the ping returns a 200.

When running the loop
`
//Get the data into a point for upload to Influx
  sensor.clearFields();
  sensor.setTime(time(nullptr));
  sensor.addField("tempC",ts.readCelsius());

  //Write the point to the client
  client.writePoint(sensor);

  //Flush the data into influxdb
  Serial.println("Flushing data into InfluxDB");
  if (!client.flushBuffer()) {
    Serial.print("InfluxDB flush failed: ");
    Serial.println(client.getLastErrorMessage());
    Serial.print("Full buffer: ");
    Serial.println(client.isBufferFull() ? "Yes" : "No");
  }
`
This is the debug I get

35.416 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
35.417 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
35.423 [D] Writing batch, batchpointer: 0, size 1
35.425 [D] Writing to 10.27.20.50:8186/write?db=environmental
35.430 [E] Begin failed
35.432 [D] Dropped batch, batchpointer: 1
35.436 [D] Success: 0, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0
35.443 [D] Buffer empty
Flushing data into InfluxDB
35.448 [D] Success: 1, _bufferPointer: 0, _batchPointer: 0, _writeBuffer[_bufferPointer]_0
35.456 [D] Buffer empty

Thoughts?

**Comment by vlastahajek** [comment]
You have to specify the  server URL for the client: `http://10.27.20.50:8186`.

**Comment by tibmeister** [comment]
Well I feel pretty dumb about now, that was the key staring me right in the face. Thank you.
