### ISSUE TITLE
Doesn't work with Arduino Uno WiFi rev2 radio chip (NINA)

### ISSUE THREAD

**Issue by StathisKap** [tobiasschuerg/InfluxDB-Client-for-Arduino#158]
I tried verifying one of the examples given but I got an error that says that the library currently supports only ESP chips.

I really don't wanna buy a new WiFi chip to plug into my already WiFi board so is could this be a feature?
Or is there any other work around

**Comment by vlastahajek** [comment]
WiFiNINA devices are not supported yet. See #66
