### ISSUE TITLE
Speeding up writing thousands of points at once.

### ISSUE THREAD

**Issue by elggem** [tobiasschuerg/InfluxDB-Client-for-Arduino#159]
Hi, and thanks for your work. 

I have an Influx 1.6 DB and everything is working except for batch writing. It seems every datapoint is written out sequentially which is very slow. I initialize with the following code: 

```
#define WRITE_PRECISION WritePrecision::S
#define MAX_BATCH_SIZE 10
#define WRITE_BUFFER_SIZE 30

...

//Set InfluxDB 1 authentication params
client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME, INFLUXDB_USER, INFLUXDB_PASSWORD);
// Set time precision batching and retry buffer
client.setWriteOptions(WriteOptions().writePrecision(WRITE_PRECISION).batchSize(MAX_BATCH_SIZE).bufferSize(WRITE_BUFFER_SIZE));  
```

I tried various combinations of batch and buffer size but nothing seems to be working. Any idea how I could debug this? Thanks!

**Comment by elggem** [comment]
Oh my, seems like it's another problem, batching is indeed working. Sorry!

**Comment by elggem** [comment]
OK Sorry for the spam nevermind, I think this is an issue with ESP-Logger....

**Comment by vlastahajek** [comment]
@elggem, if you experience another problem you can enable debug messages by uncommenting line 32 in `src/InfluxDBClient.cpp` in the library folder.

**Comment by elggem** [comment]
Thanks! Actually it was working all along, I was having an issue with ESP-Logger in combination with the library. Now it seems to be working. In case anyone else is interested I have a work-in-progress version at

https://github.com/elggem/watchy-gsr/blob/main/logger-influxdb-test/logger-influxdb-test.ino
