### ISSUE TITLE
Flush interval doesn't flush buffer if it is not full

### ISSUE THREAD

**Issue by Dim0N22** [tobiasschuerg/InfluxDB-Client-for-Arduino#160]
The doc for `_flushInterval` says:
>   // Maximum number of seconds points can be held in buffer before are written to the db. 
>   // Buffer is flushed when it reaches batch size or when flush interval runs out. 
>   uint16_t _flushInterval;

However, it seems that due to passing `true` to `InfluxDBClient::flushBufferInternal(bool flashOnlyFull)`, `flushBufferInternal` will actually do nothing even when it's time to flush.

I think we need to change this line
https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/eaee8e379eaa6b1ec816a907e0341e261a8f62d2/src/InfluxDbClient.cpp#L366
to
```cpp
return flushBufferInternal(false);
```

---

I also would be happy to cut a PR, but I don't know how to setup the environment for testing and run unit tests and unfortunately README doesn't help a lot (I use PlatformIO and consume the library from my project).

**Comment by vlastahajek** [comment]
@Dim0N22, thanks for raising issues regarding flash timeout.  
The suggested fix above cannot be done this way because when flushing all batches after connection error occurs, flushed are only full buffers.
