### ISSUE TITLE
ESP32C3 support.

### ISSUE THREAD

**Issue by roberbike** [tobiasschuerg/InfluxDB-Client-for-Arduino#169]
I have an error when compile the sckech for a esp32c3 .
I have this lines in platformio.ini:

[env:ESP32C3]
extends = oled_common
board = esp32c3
platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master
platform_packages = 
	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.2
	platformio/tool-esptoolpy @ https://github.com/tasmota/esptool/releases/download/v3.2/esptool-v3.2.zip 

**And I have this error when compile:**

In file included from .pio/libdeps/ESP32C3/ESP8266 Influxdb/src/HTTPService.cpp:3:
.pio/libdeps/ESP32C3/ESP8266 Influxdb/src/Platform.h:4:10: fatal error: core_version.h: No such file or directory

**********************************************************************
* Looking for core_version.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:core_version.h"
* Web  > https://platformio.org/lib/search?query=header:core_version.h
*
**********************************************************************

 #include <core_version.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\ESP32C3\lib617\ESP8266 Influxdb\HTTPService.cpp.o] Error 1

**Comment by vlastahajek** [comment]
There must be a problem with your IDE or configuration or SDK. I can successfully compile a sketch with this library for ESP32C3 using Arduino IDE and [Arduino core for ESP32 2.0.2](https://github.com/espressif/arduino-esp32)

**Comment by vlastahajek** [comment]
@roberbike, anything new?

**Comment by roberbike** [comment]
> 

Sorru for my late answer. The library , is compiling now with this ini file. Thanks.
[platformio]
default_envs = TTGO_TDISPLAY

[common]
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2/platform-tasmota-espressif32-2.0.2.zip
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
version = 0.5.0
revision = 877
target = prod
monitor_filters = time
extra_scripts = pre:prebuild.py
build_flags =
  -D CORE_DEBUG_LEVEL=0   # Disable debug messages
  -D MAIN_HW_EN_PIN=27    # enable the main hardware pin (main sensor)
  -D EMOTICONS  			    # enable emoticons on OLED version
lib_deps =
	bblanchon/ArduinoJson @ 6.18.5
	tobiasschuerg/ESP8266 Influxdb @ 3.9.0
	chrisjoyce911/esp32FOTA @ 0.1.5
	hpsaturn/CanAirIO Air Quality Sensors Library @ 0.4.2
	https://github.com/256dpi/arduino-mqtt.git

[esp32_common]
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2/platform-tasmota-espressif32-2.0.2.zip
board = lolin32
framework = ${common.framework}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}
monitor_filters = ${common.monitor_filters}
extra_scripts = ${common.extra_scripts}
board_build.partitions = min_spiffs.csv

[oled_common]
extends = esp32_common
lib_ignore = gui-utils-tft
lib_deps =
	${common.lib_deps}
	U8g2 @ ^2.28.8

[env:TTGO_T7]
extends = oled_common

[env:TTGO_T7_OTA]
extends = oled_common
upload_protocol = espota
upload_port = 'CanAirIO.local'
upload_flags =
	--port=3232
	--auth=CanAirIO

[env:WEMOSOLED]
extends = oled_common
upload_speed = 921600

[env:HELTEC]
extends = oled_common

[env:TTGO_TQ]
extends = oled_common

[env:ESP32DEVKIT]
extends = oled_common
upload_speed = 921600

[tft_common]
extends = esp32_common
lib_deps =
	${common.lib_deps}
	bodmer/TFT_eSPI @ 2.3.85

[env:TTGO_TDISPLAY]
extends = tft_common
board = esp32dev
lib_ldf_mode = deep
lib_ignore = gui-utils-oled
build_flags =
	${common.build_flags}
	-Os
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DENABLE_TFT=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DCGRAM_OFFSET=1
	-DTFT_MOSI=19
	-DTFT_SCLK=18
	-DTFT_CS=5
	-DTFT_DC=16
	-DTFT_RST=23
	-DTFT_BL=4
	-DTFT_BACKLIGHT_ON=1
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=6000000

[env:M5STICKCPLUS]
extends = tft_common
board = esp32dev
lib_ldf_mode = deep
lib_deps =
	${common.lib_deps}
	M5StickCPlus
lib_ignore = gui-utils-oled

[env:ESP32C3]
extends = oled_common
board = esp32-c3-devkitm-1
