### ISSUE TITLE
Tag value with spaces

### ISSUE THREAD

**Issue by mirino75** [tobiasschuerg/InfluxDB-Client-for-Arduino#17]
How to write in the code when I need spaces in tag values?

\. Backslash charactersdoes not work.

thx, Miro

Escaping Characters
If a measurement, tag key, tag value, or field key contains a space , comma ,, or an equals sign = it must be escaped using the backslash character \. Backslash characters do not need to be escaped.

**Comment by tobiasschuerg** [comment]
Didn't test ist, but you probably need to escape the backslash in c++ as well:

=> `foo\\ bar`

**Comment by mirino75** [comment]
### **2xbackslash**

InfluxData row1("water_level");
  row1.addTag("device_type", "microcontroller");
  row1.addTag("city", "New\\\ York");
  row1.addValue("distance", vzdalenost);
  row1.addValue("temperature_in", sensors.getTempCByIndex(0));

Result:  sucessfully write to DB, but with one backslash

--> writing to telegraf:
water_level,device_type=microcontroller,city=New\ York distance=72.00,temperature_in=30.50
 <-- Response: 204 ""

--------------------------------------------------------

### **1xbackslash**
InfluxData row1("water_level");
  row1.addTag("device_type", "microcontroller");
  row1.addTag("city", "New\ York");
  row1.addValue("distance", vzdalenost);
  row1.addValue("temperature_in", sensors.getTempCByIndex(0));

Result:  
--> writing to telegraf:
water_level,device_type=microcontroller,city=New York distance=72.00,temperature_in=30.50
 **<-- Response: 400 "{"error":"unable to parse 'water_level,device_type=microcontroller,city=New York distance=72.00,temperature_in=30.50': invalid field format"}**

**Comment by mirino75** [comment]
Hi Tobias,
Why is the thread closed? Problem is not solved ...

**2xbackslash**
If the tag value is written in the program code with **2xbackslash**  "New\\\ York" then write to database is ok BUT tag value is not with space but with one backslash.

**1xbackslash**
If the tag value is written in the program code with **1xbackslash**  "New\ York" then write to database is NOT ok BUT space is added. The influx database recognizes this gap as the end of tags and the beginning of keys values.

Miro

**Comment by tobiasschuerg** [comment]
Sorry, wasn't clear to me that it was not resolved.

Still, this seems to be an escaping issue. Maybe also ask on stackoverflow or influxdb.
Not sure what to do here. From the docs I would say `\ ` should work.

**Comment by mirino75** [comment]
Ok, escaping charcter is OK. The problem is in recognizing the section where the field key starts.

**Test over HTTP API, command line**

![image](https://user-images.githubusercontent.com/24975570/59347184-46e84400-8d14-11e9-8787-60bcf653fcb4.png)

![image](https://user-images.githubusercontent.com/24975570/59347304-9464b100-8d14-11e9-98f1-1bfb0e63eaf1.png)

**Writing a tag value with a space in your program**
![image](https://user-images.githubusercontent.com/24975570/59347438-e86f9580-8d14-11e9-891b-94bac7c20048.png)

![image](https://user-images.githubusercontent.com/24975570/59348505-98de9900-8d17-11e9-9073-54cb2afeeef3.png)

**Comment by Bolukan** [comment]
Could double-quotes be used?
row1.addTag("city", "\"New York\"");

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
