### ISSUE TITLE
Update library to 3.10.0 generate compiling error on ESP32

### ISSUE THREAD

**Issue by hpsaturn** [tobiasschuerg/InfluxDB-Client-for-Arduino#175]
## Overview

__Actual behavior:__

Compiling error:

```cpp
Compiling .pio/build/TTGO_T7/lib074/Update/HttpsOTAUpdate.cpp.o
In file included from .pio/libdeps/TTGO_T7/ESP8266 Influxdb/src/query/FluxTypes.cpp:28:0:
.pio/libdeps/TTGO_T7/ESP8266 Influxdb/src/query/FluxTypes.h: In constructor 'FluxString::FluxString(String, String, const char*)':
.pio/libdeps/TTGO_T7/ESP8266 Influxdb/src/query/FluxTypes.h:131:12: error: 'FluxString::value' will be initialized after [-Werror=reorder]
     String value;
            ^
.pio/libdeps/TTGO_T7/ESP8266 Influxdb/src/query/FluxTypes.h:127:17: error:   'const char* FluxString::_type' [-Werror=reorder]
     const char *_type;
                 ^
.pio/libdeps/TTGO_T7/ESP8266 Influxdb/src/query/FluxTypes.cpp:147:1: error:   when initialized here [-Werror=reorder]
 FluxString::FluxString(String rawValue, String value, const char *type):FluxBase(rawValue),value(value),_type(type)
 ^
Compiling .pio/build/TTGO_T7/lib074/Update/Updater.cpp.o
Compiling .pio/build/TTGO_T7/libc61/FS/FS.cpp.o
```

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Updated dependencie from 3.9.0 to 3.10.0
2. Compiling over ESP32 Arduino Framework using PlatformIO

__Expected behavior:__

Backward compatibility

__Specifications:__
 - Library Version: 3.10.0
 - InfluxDB Version: NA
 - Board/ESP chip: ESP32 (lolin32) 
 - Device Arduino SDK version: Espressif 32 3.4.0

**Comment by vlastahajek** [comment]
Thanks for the issue. I don't use PlatformIO.  Arduino core for ESPs has only one compiler option to treat a specific warning as an error. I've pushed a fix that clears all warnings, so it should work for you.

Could you, please, add the full command line for compiling projects used by PlatformIO?

**Comment by hpsaturn** [comment]
The current changes fixed the issue. Thanks.

Also I want say that PlatformIO is better than Arduino CLi and Arduino IDE, you should be consider that, and it is more easy too.

Proof of that, I did a pull request that test the complete library over ESP32 and ESP8266 using continous integration workflow with PlatformIO and Github workflow. #177
