### ISSUE TITLE
core_version.h doesn't exists

### ISSUE THREAD

**Issue by juanitomaille** [tobiasschuerg/InfluxDB-Client-for-Arduino#183]
My platformio.ini :

**[env:esp32Makerfabs]
platform = espressif32
board = esp32dev
framework = arduino
board_build.mcu = esp32s2
upload_protocol = esptool
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.0-alpha1
	platformio/tool-esptoolpy @ ~1.30100
src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<main_sensor.cpp*> -<main_ihm.cpp*> -<main_ihm_ili9486.cpp*>
build_flags = -DLV_CONF_INCLUDE_SIMPLE -DLV_DEMO_CONF_INCLUDE_SIMPLE -Iinclude -Iinclude/logos
lib_deps = 
	lovyan03/LovyanGFX@^0.4.11
	lvgl/lvgl@^8.1.0
	tobiasschuerg/ESP8266 Influxdb@^3.11.0**

I had to comment #include "Platform.h" in influxDbClient.cpp and HTTPService.cpp
and delete references in line 3 of HTTPService.cpp :+1: 
`static const char UserAgent[] PROGMEM = "influxdb-client-arduino/" INFLUXDB_CLIENT_VERSION " (**[DELETED CONTENT]**)";`

I think it's ok now, I will test.

**Comment by juanitomaille** [comment]
I've just tried 2.0.2 version. Same error.
...but compilation also breaks because of ESP32**S2**.
I return in 2.0.0-alpha1 advised by my board provider.
It's not a big problem for me, your library seems to work great with those modifications.

Thanks.

**Comment by vlastahajek** [comment]
The problem must be in the toolchain. In #169, there was a similar issue.

**Comment by juanitomaille** [comment]
Ah OK, I didn't see that before.

I will try to find the problem, thanks


Le mer. 9 mars 2022, 22:10, Vlasta Hajek ***@***.***> a
écrit :

**Comment by cmoscicada** [comment]
![2022-04-21_14-59-36](https://user-images.githubusercontent.com/59960674/164384554-3ed61dbd-e50e-4d96-b902-47056133165b.png)

**Comment by gasagna** [comment]
@vlastahajek: I wonder if this issue should really be closed. 

I am also affected by this bug, as the board SDK I [use](https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series) does not ship with a `core_version.h` header file. Actually, this file appears to be generated before a release by a bash script (as seen [here](https://github.com/espressif/arduino-esp32/blob/e881d11bdb6cebc80fed531ea99046d3c00f0cd1/.github/scripts/on-release.sh#L214) in the main arduino-ep32 repo) and it defines variables for the release version (e.g. `ARDUINO_ESP32_GIT_DESC `). These variables are then used in `Platform.h` in this repo.

On the other hand, the header file "esp_arduino_version.h" (also mentioned just above here by @cmoscicada ) defines similar variables and is not generated automatically on release, but is part of the arduino-esp32 repo. Can we include this file instead in `Platform.h` and define the variable `INFLUXDB_CLIENT_PLATFORM_VERSION` from its content?

**Comment by gasagna** [comment]
The modified `Platform.h` might look like this (untested)

```c++
#ifndef _PLATFORM_H_
#define _PLATFORM_H_

#define STRHELPER(x) #x
#define STR(x) STRHELPER(x) // stringifier

// form version string
#define VERSION_STR(MAJOR, MINOR, PATCH) STR(MAJOR) "." STR(MINOR) "." STR(PATCH)

#if defined(ESP8266)
# include <core_version.h>
# define INFLUXDB_CLIENT_PLATFORM "ESP8266"
# define INFLUXDB_CLIENT_PLATFORM_VERSION  STR(ARDUINO_ESP8266_GIT_DESC)
#elif defined(ESP32)
# include <esp_arduino_version.h>
# define INFLUXDB_CLIENT_PLATFORM "ESP32"
# define INFLUXDB_CLIENT_PLATFORM_VERSION VERSION_STR(ESP_ARDUINO_VERSION_MAJOR, ESP_ARDUINO_VERSION_MINOR, ESP_ARDUINO_VERSION_PATCH)
#endif

#endif //_PLATFORM_H_
```

Note that the esp8266 arduino core uses the header `core_version.h` (see [here](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_version.h)).

**Comment by gasagna** [comment]
I have tested the code above and I managed to compile my sketch using the incomplete board definition I am using. Is this change something that would be accepted? I can make a pull request.
