### ISSUE TITLE
Connection refused to InfluxDB

### ISSUE THREAD

**Issue by thewackyseal** [tobiasschuerg/InfluxDB-Client-for-Arduino#187]
Hi, I'm unable to connect to InfluxDB from my esp32 board and not sure what to do as I am new to this. Please advise, thank you.

This is the error log:
![image](https://user-images.githubusercontent.com/72852103/168019201-ed55693f-f814-46ea-abb8-5ad7a0a2ebdf.png)

**Comment by vlastahajek** [comment]
@thewackyseal, thanks for the log. The log shows that you have set the host as `localhost`. `Localhost` means **the same device**. You need to provide the name or IP of the computer running the InfluxDB server, or the URL for InfluxDB Cloud if it is the case.

**Comment by thewackyseal** [comment]
Thank you, it connects now, however I'm facing this new issue:

![image](https://user-images.githubusercontent.com/72852103/168193037-bebf456d-6fac-4b49-96cf-cfaa0f9f417b.png)

**Comment by vlastahajek** [comment]
What is the issue with your app? Did the client report an error? The above log message doesn't mean there is sth wrong.

**Comment by thewackyseal** [comment]
I managed to get it working, thank you for the help!
