### ISSUE TITLE
Extend library for simplified read of database

### ISSUE THREAD

**Issue by Stoobiedoo** [tobiasschuerg/InfluxDB-Client-for-Arduino#19]
Can you add a function to use the same influx object, but send a query and output the result? 

The code works great for writing my values to the database, but I am struggling because I want to use information in the last entry to modify the query to a different webpage. If a new function is not appropriate, can you direct me to a standalone Arduino example of submitting a query to an InfluxDB? Thank you

**Comment by tobiasschuerg** [comment]
This library uses the [InfluxDB line protocol](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/) to write data to the database.

As far as I can see, querying data is only possible via the [InfluxDb Api](https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/) which will return a JSON that needs to be parsed. Of course you can parse that result `InfluxData.h` but (json) parsing is a lot of overhead.

If you always only need the last value, I would store this last value on the device itself.

**Comment by Darktidelulz** [comment]
> This library uses the [InfluxDB line protocol](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/) to write data to the database.

Querrying data via line protocol is no problem.

HW Wong has this implemented, lines 74 to 127
https://github.com/hwwong/ESP8266Influxdb/blob/master/ESP8266Influxdb.cpp

`        // This will send the request to the server

        print(String("GET ") + url + " HTTP/1.1\r\n" + "Host: " + _host + ":" + _port + "\r\n" +"Connection: close\r\n\r\n");`

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
