### ISSUE TITLE
ESP8266_Influxdb/src/InfluxDbClient.h:210:21: error: 'virtual int InfluxDBClient::BatchStreamer::availableForWrite()' marked override, but does not override

### ISSUE THREAD

**Issue by cbrassel** [tobiasschuerg/InfluxDB-Client-for-Arduino#190]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install fresh InfluxDB Library2. 
Setup default code from influxDB Load Data / Arduino Example project
3. Compile code 
__Expected behavior:__
Code compiling ?

__Actual behavior:__
The Error : In file included from /Users/xxxx/Arduino/sketch_aug08b/sketch_aug08b.ino:11:0:
/Users/xxxx/Arduino/libraries/ESP8266_Influxdb/src/InfluxDbClient.h:210:21: error: 'virtual int InfluxDBClient::BatchStreamer::availableForWrite()' marked override, but does not override
         virtual int availableForWrite() override;
                     ^
/Users/xxxx/Arduino/libraries/ESP8266_Influxdb/src/InfluxDbClient.h:214:21: error: 'virtual int InfluxDBClient::BatchStreamer::read(uint8_t*, size_t)' marked override, but does not override
         virtual int read(uint8_t* buffer, size_t len) override;
                     ^
exit status 1
Erreur de compilation pour la carte Generic ESP8266 Module

__Specifications:__
 - Library Version: 3.12.0
 - InfluxDB Version: 2.3.0
 - Board/ESP chip: ESP-01
 - Device Arduino SDK version: 1.8.19

**Comment by vlastahajek** [comment]
@cbrassel, you probably have an old ESP8266 Arduino Core, I guess 2.7.4. Please upgrade it to a recent one (3.0.3) using Arduino IDE, menu Tools->Board-> Board Manager, and select `Updatable`.

**Comment by cbrassel** [comment]
yes ! you are right .. I forget to update this one.

Thank you
