### ISSUE TITLE
Influxdb data sending with sim800l 

### ISSUE THREAD

**Issue by ilcnet** [tobiasschuerg/InfluxDB-Client-for-Arduino#192]
Hello dear friends I have a problem with data sending to influxdb server by 2g Internet sim800l, my esp32 received data with lora and i need to send it to influxdb server with 2g sim800l module, anybody can help me to solve this issue, regard

**Comment by vlastahajek** [comment]
@ilcnet, there is already started issue about this: #140. 
Such a feature might be added at the end of the year.
