### ISSUE TITLE
ESP8266_Influxdb 3.12.1 error 'virtual int InfluxDBClient::BatchStreamer::availableForWrite()' marked 'override', but does not override

### ISSUE THREAD

**Issue by 3Dnerd** [tobiasschuerg/InfluxDB-Client-for-Arduino#196]
__Steps to reproduce::

1. Using sloeber I created a simplke arduino project for my ESP32 FireBeetle.
2. I added following code  as my *.ino file:

`/**
 * Basic Write Example code for InfluxDBClient library for Arduino
 * Data can be immediately seen in a InfluxDB UI: wifi_status measurement
 * Enter WiFi and InfluxDB parameters below
 *
 * Measures signal level of the actually connected WiFi network
 * This example supports only InfluxDB running from unsecure (http://...)
 * For secure (https://...) or Influx Cloud 2 use SecureWrite example
 **/

#include <WiFiMulti.h>
#include <InfluxDbClient.h>

WiFiMulti wifiMulti;

#define DEVICE "ESP32"
#define WIFI_SSID "mySSID"
#define WIFI_PASSWORD "mypassword"
#define INFLUXDB_URL "192.168.178:49"
#define INFLUXDB_TOKEN "WRITE_YOUR_API_TOKEN"
#define INFLUXDB_ORG "WRITE_YOUR_ORG"
#define INFLUXDB_BUCKET "WRITE_YOUR_BUCKET"

// InfluxDB client instance
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN);
// InfluxDB client instance for InfluxDB 1
//InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);

// Data point
Point sensor("wifi_status");

void setup() {
  Serial.begin(115200);

  // Connect WiFi
  Serial.println("Connecting to WiFi");
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);
  while (wifiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println();

  // Set InfluxDB 1 authentication params
  //client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME, INFLUXDB_USER, INFLUXDB_PASSWORD);

  // Add constant tags - only once
  sensor.addTag("device", DEVICE);
  sensor.addTag("SSID", WiFi.SSID());

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  } else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }
}

void loop() {
  // Store measured value into point
  sensor.clearFields();
  // Report RSSI of currently connected network
  sensor.addField("rssi", WiFi.RSSI());
  // Print what are we exactly writing
  Serial.print("Writing: ");
  Serial.println(client.pointToLineProtocol(sensor));
  // If no Wifi signal, try to reconnect it
  if (wifiMulti.run() != WL_CONNECTED) {
    Serial.println("Wifi connection lost");
  }
  // Write point
  if (!client.writePoint(sensor)) {
    Serial.print("InfluxDB write failed: ");
    Serial.println(client.getLastErrorMessage());
  }

  //Wait 10s
  Serial.println("Wait 10s");
  delay(10000);
}
`
__Expected behavior:__
I expect to compile without errors

__Actual behavior:__
I get this compile error:

> C:\Sloeber\arduinoPlugin\libraries\ESP8266_Influxdb\3.12.1\src\InfluxDbClient.h:211:21: error: 'virtual int InfluxDBClient::BatchStreamer::availableForWrite()' marked 'override', but does not override virtual int availableForWrite() override;

__Specifications:__
 - Library Version: 3.12.1
 - InfluxDB Version: latest
 - Board/ESP chip: ESP32 FireBeetle
 - Device Arduino SDK version: Sloeber

**Comment by 3Dnerd** [comment]
Can someone help please?

**Comment by vlastahajek** [comment]
> Device Arduino SDK version: Sloeber

Sloeber is IDE. You haven't specified what is your ESP32 Arduino Core version, but most probably you have  an 1.x.x, like in #182
Try upgrading, please.

**Comment by roelofvredeveld** [comment]
I am using a Beetle ESP32 (DFR0575). It appears that DFRobot is using another core (0.1.1) for this board.
Only entering "#include <InfluxDbClient.h>" already results in the error 3Dnert is describing.  (..) marked override, but does not override. 
Any thoughts on how to solve this would be appriciated.

Library Version: 3.12.2
Board/ESP chip: ESP32 Beetle (DFR0575)
Arduino IDE version 1.8.19

**Comment by vlastahajek** [comment]
@roelofvredeveld, do you mean you have installed a different Arduino Core, than the normal ESP32 Arduino Core? Could you, please, show here what is your board selected in the Arduino IDE, like this:
![image](https://user-images.githubusercontent.com/29980246/194835164-fd01792f-2261-4e8c-9717-56b7d07efa0d.png)

**Comment by roelofvredeveld** [comment]
@vlastahajek, I am quite sure that I have installed a differnt Arduino Core. My IDE interface looks completely different. see below.
I have been using the IDE developer environment package, provided by DFRobot: http://download.dfrobot.top/FireBeetle/package_esp32_index.json

![Schermafbeelding 2022-10-10 140330](https://user-images.githubusercontent.com/115373490/194862300-23923281-b514-4ee4-af80-e936c609c8f6.jpg)

**Comment by vlastahajek** [comment]
I will change the code to avoid such compilation problems.

However, @roelofvredeveld, your DF Robot Arduino Core is edited original ESP32 Arduino Core stripped to only one board - Fire Beetle. However, this core is based on the ancient 1.0.4. ESP32 Arduino Core! 
I strongly recommend you to change to the latest official ESP32 Arduino Core. There have been many improvements and fixes in the ESP32 runtime and libraries. Even if you will not find the exact board in the boards list, you can use the universal ESP32 dev module board.

**Comment by vlastahajek** [comment]
I guess, it is the same problem for @3Dnerd

**Comment by roelofvredeveld** [comment]
Hi, it appears that in the default ESP32 Core (v2.0.5), there is also a board definition for FireBeetle-ESP32 with an almost identical pins_arduino.h. That compiles without errors. 
Have to download and test it, but for now I do not see any issues with @vlastahajek's InfluxDBClient code.

**Comment by roelofvredeveld** [comment]
@vlastahajek : thanks for your advise on this!!
