### ISSUE TITLE
ESPAsyncTCP support

### ISSUE THREAD

**Issue by Trickx** [tobiasschuerg/InfluxDB-Client-for-Arduino#2]
I like the way your lib provides access to the features of InfluxDB, especially the support of multiple values/tags of a measurement.
I'm working on a ESPurna based gateway from Jeelink compatible temperature sensor towards MQTT and Influx. I'm using your lib.
Basically it is working, but from time to time I experience the system to stop.
I wonder if this is caused by some timing and race conditions.

Is it possible to add [ESPAsyncTCP](https://github.com/me-no-dev/ESPAsyncTCP) support?

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
