### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by LaurentZuijdwijk** [tobiasschuerg/InfluxDB-Client-for-Arduino#20]
The v2 branch doesn't work without https support.

**Comment by cail** [comment]
See https://github.com/tobiasschuerg/ESP8266_Influx_DB/pull/23

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
