### ISSUE TITLE
Class Point also used in other libraries

### ISSUE THREAD

**Issue by walserchr** [tobiasschuerg/InfluxDB-Client-for-Arduino#205]
Hi

This is a great library and I really like it. Only thing I want to mention and suggest as an improvement is, that the class Point in the Point.h file is already used in other libraries, e.g. "M5core.h" -> "PointAndZone.h". This makes it very difficult to use in combination with the M5core2, which is a pitty.

Would be nice if this can be improved in a next version :)

Thanks anyway for this library. Great job!

**Comment by Dewaeq** [comment]
There's no need to go and rename classes, instead include them inside a namespace, e.g.

```cpp
namespace foo {
    #include "M5Score.h"
}
```

and then use it like this:

```cpp
foo::yourClass;
```

**Comment by vlastahajek** [comment]
Thank you for the hint, @Dewaeq.

@walserchr, in my defense, this library's Point seems to be older than the one from the M5Core repo. 

The term `Point` has been chosen to comply with the API of other InfluxDB clients.

There is no viable solution for renaming or namespacing the class name to not break compilability with existing code. 
As this occurs very rarely (you are the first one reporting it), the [workaround by Dewaeq](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/issues/205#issuecomment-1372210475) is the best solution.
