### ISSUE TITLE
useServerTimestamp does not work with non-default precisions

### ISSUE THREAD

**Issue by szerwi** [tobiasschuerg/InfluxDB-Client-for-Arduino#206]
It seems that useServerTimestamp does not work with precisions other than default.

List the minimal actions needed to reproduce the behavior.

1. Set `useServerTimestamp(true)` and `writePrecision(WritePrecision::S)`
2. Send point

__Expected behavior:__
Timestamp from server should be used

__Actual behavior:__
Timestamp is invalid - point is placed with 01-01-1970 timestamp

__Specifications:__
 - Library Version: 3.13.0
 - InfluxDB Version: 2.6.1
 - Board/ESP chip: ESP32 Dev Module
 - Device Arduino SDK version: arduino-esp32 2.0.6

**Comment by vlastahajek** [comment]
@szerwi, How do you set those options exactly?

**Comment by szerwi** [comment]
@vlastahajek Here is my setup:
```
influxdb.setWriteOptions(WriteOptions()
  .writePrecision(WritePrecision::S)
  .useServerTimestamp(true)
  .batchSize(1)
  .bufferSize(2)
  .flushInterval(30)
  .retryInterval(1)
  .maxRetryInterval(2)
  .maxRetryAttempts(0)
  );
influxdb.setHTTPOptions(HTTPOptions().httpReadTimeout(6000).connectionReuse(true));
influxdb.setConnectionParams(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN);
influxdb.setInsecure(true);

if (influxdb.validateConnection()) {
  Serial.print("Connected to InfluxDB: ");
  Serial.println(influxdb.getServerUrl());
} else {
  Serial.print("InfluxDB connection failed: ");
  Serial.println(influxdb.getLastErrorMessage());
}
```

**Comment by vlastahajek** [comment]
This is absolutely correct and it shouldn't cause sending a zero timestamp. That could happen only when using deprecated  `bool setWriteOptions(WritePrecision precision, uint16_t batchSize = 1, uint16_t bufferSize = 5, uint16_t flushInterval = 60, bool preserveConnection = true)`
Could you, please, enable the debug output in the `src/util/debug.h` and check the sent data if it really sends 0?

**Comment by szerwi** [comment]
@vlastahajek Sorry for the late reply.

I can confirm that timestamp is being sent when I set `writePrecision(WritePrecision::S)` together with `useServerTimestamp(true)`. It sends  the timestamp in seconds. My ESP is not connected to NTP, so it starts counting the timestamp from 0.

Debug output with `writePrecision(WritePrecision::S)` and `useServerTimestamp(true)`:
```
30.000 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
30.011 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
30.011 [D] Writing batch, batchpointer: 0, size 1
30.021 [D] Writing to https://xxx:55555/api/v2/write?org=xxx&bucket=xxx&precision=s
30.032 [D] Sending:
snow_depth snow_depth_mean=5.0,snow_depth_median=5.0 30

30.032 [D] POST request - https://xxx:55555/api/v2/write?org=xxx&bucket=xxx&precision=s, data: 56bytes, type text/plain
31.283 [D] HTTP status code - 204
31.285 [D] Dropped batch, batchpointer: 1
31.285 [D] Success: 1, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0x0
31.295 [D] Buffer empty
```

Debug output with only  `useServerTimestamp(true)`:
```
15.000 [D] writeRecord: bufferPointer: 1, batchPointer: 0, _bufferCeiling: 1
15.011 [D] Flushing buffer: is oversized true, is timeout false, is buffer full false
15.011 [D] Writing batch, batchpointer: 0, size 1
15.021 [D] Writing to https://xxx:55555/api/v2/write?org=xxx&bucket=xxx
15.021 [D] Sending:
snow_depth snow_depth_mean=5.0,snow_depth_median=5.0

15.032 [D] POST request - https://xxx:55555/api/v2/write?org=xxx&bucket=xxx, data: 53bytes, type text/plain
16.287 [D] HTTP status code - 204
16.289 [D] Dropped batch, batchpointer: 1
16.289 [D] Success: 1, _bufferPointer: 1, _batchPointer: 1, _writeBuffer[_bufferPointer]_0x0
16.300 [D] Buffer empty
```

**Comment by vlastahajek** [comment]
Thanks, @szerwi, for the details, and sorry for the late reply. Supporting this library was part of my previous job and I have now trouble finding time for this.
The core problem of this issue is that if connection params are not set in the constructor (which is the way most often used to set it), it must be set before any options are set, because setting of options initializes internals and this requires a valid server URL.
You will notice a problem by checking the return values of options setters.

I admit this is not much intuitive and I will fix this.
