### ISSUE TITLE
imported (unzipped) library in Arduino/libraries folder but doesn't show in "include library"

### ISSUE THREAD

**Issue by K1WIZ** [tobiasschuerg/InfluxDB-Client-for-Arduino#207]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Library Version:
 - InfluxDB Version:
 - Board/ESP chip:
 - Device Arduino SDK version:

**Comment by vlastahajek** [comment]
@K1WIZ, please, describe exactly what you did. The issue title is too general.

**Comment by vlastahajek** [comment]
If you manually cloned/copied a library, you need to restart Arduino IDE. Then it is found under name `ESP8266 InfluxDb`, which is the original, unchangeable name of the library.
![image](https://user-images.githubusercontent.com/29980246/221859844-967de8d0-3def-41f4-a89b-b4fa95146660.png)
