### ISSUE TITLE
Flux Types Do Not Match Flux Specs

### ISSUE THREAD

**Issue by imasonaz** [tobiasschuerg/InfluxDB-Client-for-Arduino#208]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.
1. Try to query for an Int
2. Fail

__Expected behavior:__
Support Flux support data types: https://docs.influxdata.com/flux/v0.x/spec/types/

__Actual behavior:__
```
x = result.getValueByName("_value").getInt();
```
```
Compilation error: 'class FluxValue' has no member named 'getInt'; did you mean 'getLong'?
```

Without getting into the weeds about supported decimal types, InfluxDB versions, etc. I believe that a library such as this should be able to match having integer support pretty easily.

__Specifications:__
 - Library Version: 3.13.0
 - InfluxDB Version: Cloud2
 - Board/ESP chip: ESP32-WROOM
 - Device Arduino SDK version: 2.0.0

**Comment by vlastahajek** [comment]
@imasonaz, Flux types, available in the Flux scripts, and the types sent in the Flux query result set are different. 
Check types in the Flux result set: https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/#data-types.
You can read mapping in this library in https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino#querying.

**Comment by imasonaz** [comment]
The link https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/#data-types does seem to muddy things in that it says results of type long are represented in Flux as an Int, and goes against docs like https://docs.influxdata.com/influxdb/cloud/reference/key-concepts/data-elements/#field-value saying a field value can be `strings, floats, integers, or booleans` and also against https://docs.influxdata.com/influxdb/cloud/reference/glossary/#data-type which lists the data type as integer but an alias of int and long. The argument that long should be removed in favor of int is also strengthened by line protocol only mentioning float and int: https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#data-types-and-format I also find it interesting that https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/extended/#datatype says essentially data of type long is converted to an integer field in line protocol.

So without digging into the influxDB code too deeply, it seems that overall the documentation is extremely muddy and there is significant type name interchanging happening with longs and ints.

**Comment by imasonaz** [comment]
I think for now, I will bring this up as a docs issue to Influx and have switched my code to use getLong().

Thanks for the clarification here though, I much appreciate it.

**Comment by vlastahajek** [comment]
Well, yes. Types in the line protocol, Flux script, and annotated CVS are not aligned. But, it doesn't seem to be a doc issue, cause the doc describes the actual situation quite right. It is more an issue of their design and implementation differences.
