### ISSUE TITLE
Allow force write

### ISSUE THREAD

**Issue by gasagna** [tobiasschuerg/InfluxDB-Client-for-Arduino#213]
__Proposal:__
Add a function to force writing data to InfluxDB even if the batch is not complete.

__Current behavior:__
Points are written only when the batch is complete.

__Desired behavior:__
A function that forces a write to the InfluxDB database.

__Alternatives considered:__
None.

__Use case:__
I have an IoT application where i'd like to write to my influxdb database once every ten points (using the batch feature) OR every minute, whichever comes first. The first scenario occurs when many nodes send data to my gateway and the batch feature enables writing this data efficiently to the database (instead of connecting for every datapoint). The second scenario is a low data rate case, where only few nodes talk, but I want this data to reach the InfluxDB database within a given time. I'd like to have a function, for instance named `forceWrite()` or similar that I can call every, e.g., 60 seconds to write whatever data I have to the database.

Thanks.

**Comment by gasagna** [comment]
I am happy to prepare a PR if this is something that would be useful to have.

**Comment by vlastahajek** [comment]
@gasagna,  that's what [InfluxDBClient::flushBuffer()](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/src/InfluxDbClient.h#L141) is for. Doesn't it work for you?

**Comment by gasagna** [comment]
Apologies! did not see it.
