### ISSUE TITLE
you can delete it now ;-)

### ISSUE THREAD

**Issue by homonto** [tobiasschuerg/InfluxDB-Client-for-Arduino#222]
Hi there,

I am using your library for more than a year already THANK YOU

**Comment by vlastahajek** [comment]
Hi @homonto , thanks for using the library. 
I saw your original nice detailed description of your problem in email.
Great, congratulations, you found the solution!
  would like to ask you to keep the original message and to add the solution, so someone else can learn what to do if stuck at the same problem.

**Comment by homonto** [comment]
I deleted it because I realised this has to be problem on my side - nginx proxy or my firewall
actually I still did not find the final solution but the fact that sometimes it works and sometimes it does not, points me to the domain/firewall/routing etc. because when I use locally both http and https, the library works, and the influxdb works

but still, thank you for your amazing job ;-)
