### ISSUE TITLE
macro "min" passed 3 arguments, but takes just 2

### ISSUE THREAD

**Issue by franklevis** [tobiasschuerg/InfluxDB-Client-for-Arduino#28]
I always recive this error when just try to compile the example:

I don't know how to fix it

c:\users\frank\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2

     min(const _Tp& __a, const _Tp& __b, _Compare __comp)

                                                        ^

c:\users\frank\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2

     max(const _Tp& __a, const _Tp& __b, _Compare __comp)

**Comment by tobiasschuerg** [comment]
Seems like there is something misconfigured in you project/setup.
Are you using the correct architecture/board?

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
