### ISSUE TITLE
validateConnection() is checking the right status code?

### ISSUE THREAD

**Issue by alexbn71** [tobiasschuerg/InfluxDB-Client-for-Arduino#33]
validateConnection() function expect a return code of 200 but the correct return code of a /ping it should be 204... as described here: https://docs.influxdata.com/influxdb/v1.7/tools/api/#ping-http-endpoint. And in my case is what happen, my influxdb instance return 204 at the /ping endpoint so the  validateConnection() return always "false" despite the connection is working.

**Comment by tobiasschuerg** [comment]
Good find @alexbn71.

There seems to be a discrepancy between version 1 and version 2:

> V1: By default, the /ping HTTP endpoint returns a simple HTTP 204 status response to let the client know that the server is running. 

> V2: 200 The instance is ready

So the verbose flag needs to be set to have the same behavior.

> When verbose option is set to true (/ping?verbose=true), an HTTP 200 status is returned.

**Comment by tobiasschuerg** [comment]
@alexbn71 please check #34
