### ISSUE TITLE
Question: Is it possible to do bi-directional communication to InfluxDB?

### ISSUE THREAD

**Issue by metcalfepete** [tobiasschuerg/InfluxDB-Client-for-Arduino#37]
Hi,
You did an awesome job on Arduino InfluxDB client. Thanks.

I wonder if I could trouble you with a question? InfluxDB is a fantastic historical storage system, but can it manage commands? For example an Arduino is monitoring temperatures, and it's also connected to an on/off fan. The fan control is manual and a user would send a command to turn it on/off remotely. Would the ON/OFF command need to be done in MQTT or REDIS, or is it possible  to do it in InfluxDB ? If so how would you read the command in the Arduino ?

Again, thanks for all your good work.
Cheers
Pete

**Comment by vlastahajek** [comment]
@metcalfepete, as InfluxDB is a database (even it is a specific database for time series data) it could be used theoretically used as a command source.  It depends on how exactly you would like to do it. E. g. would you like to update back command which has been executed? Or delete?
It also depends on the InfluxDB version, you are using. I assume that you are using InfluxDB 1.7.
Still, there are two issues:
 - This library doesn't currently support querying, so you cannot read anything from the database.
 - InfluxDB doesn't support classical SQL CRUD operations. It is possible to delete and update, but slightly a different way. For InfluxDB 1 this requires querying capability, for InfluxDB 2 even a different API

**Comment by metcalfepete** [comment]
Hi,
Thanks for getting back to me, I really appreciate it.

If the library doesn't support querying then I'll need to look at an alternate approach.

Again thanks for your feedback.

Regards
Pete

________________________________

**Comment by vlastahajek** [comment]
The problem of querying is, that you can easily get out of RAM.  ESP8266 has 80KB RAM. Afer fresh start, depending on your code and libraries you are using,  you have around 50KB, probably less. TLS connection eats another ~20KB.  You need to be very careful about composing a query to return one or a few lines. InfluxDB 1 returns JSON, InfluxDB 2 returns CSV. That needs to be parsed..
If you will be using InfluxDB 2, send an email I can point you to my experimental version of this library with the query capability.

**Comment by metcalfepete** [comment]
Hi,
Thanks for the feedback. Unfortunately I'm using InfluxDB 1.7.9. not version 2.

I was looking at doing a REST GET request in Arduino to get user commands (like start a FAN). However I realized that putting commands into InfluxDB/Grafana isn't probably the cleanest approach for a few reasons:

  *   a subscription mechanism would be better than polling and doing a REST API GET
  *   adding a push button command faceplate in Grafana is possible but the presentation isn't the best

For my applications probably an InfluxDB/NodeRed combination would be better. NodeRed is designed for a Smart Phone screen layout and it directly supports pushbuttons and trend charts.

So for the commands they could go directly from Arduino to Node-Red via MQTT or sockets.

Again thanks for looking into this question for me.

Regards
Pete

________________________________
