### ISSUE TITLE
Selfsigned certificate issue on ESP8266

### ISSUE THREAD

**Issue by geertsbe** [tobiasschuerg/InfluxDB-Client-for-Arduino#39]
Hi Tobias,

First off awesome job on the library here. However I can't seem to get the library working with a selfsigned cert over SSL. I tried enabling line 30 in the InfluxDBclient.cpp which gave me following output on the monitor:

23:54:59.966 -> [D] Validating connection to https://192.168.0.3:8086/ping?verbose=true
23:55:00.170 -> [D] HTTP status code - -1
23:55:00.170 -> [E] Error - connection refused
23:55:00.170 -> InfluxDB connection failed: connection refused

My Influxdb is running on a raspberry pi, connecton is sucessfull:
- Without https, using the WemosD Mini ESP8266 controller
- With https on the raspberry itself wtith the connectin string client = InfluxDBClient(host='192.168.0.3', port=8086, database='test', username='Omitted', password='Omitted', ssl=True)

However using the code provided I can't seem to get it make a succesfull connection, the reponse is "connection refused". Further looking into the logs I get following error: apr 03 23:36:00 raspberrypi influxd[4730]: 2020/04/03 23:36:00 http: TLS handshake error from 192.168.0.130:62296: tls: oversized record received with length 21536. 

I was wondering, could this have something to do with the -unsafeSsl flag that is set in the "normal" selsigned connections to the database, (https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/)

I've included my sketch in attachment, do you have any idea whats going wrong as it does seem to work on your end?
[SensorToInflux.txt](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/files/4430072/SensorToInflux.txt)

**Comment by vlastahajek** [comment]
@geertsbe, could you, please, attach the configuration of your InfluxDBServer? 
Does it work for you, when you try accessing `https://192.168.0.3:8086/ping?verbose=true` from another computer using curl?

**Comment by geertsbe** [comment]
@vlastahajek I'm terribly sorry for the late response. Nevertheless below the curl output (ran from the pi), and once ran from my windows browser.

![afbeelding](https://user-images.githubusercontent.com/2683859/78692714-8fec3300-78fa-11ea-98db-99a7d0509042.png)
![afbeelding](https://user-images.githubusercontent.com/2683859/78692811-b9a55a00-78fa-11ea-95da-278f03e2162f.png)

Below you can find the influxdb.conf file, I also trie manipulatiting parameters:
-   max-concurrent-write-limit = 0
-   enqueued-write-timeout = 0

[influxdb.conf.txt](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/files/4445806/influxdb.conf.txt)

Next time I'll try to respond faster :-)

**Comment by vlastahajek** [comment]
No problem for the time of replying, it is your issue :)
Well, I don't see anything wrong on both sides. The error on the server side, `tls: oversized record received with length 21536` is mostly caused by not using encryption on a client side (HTTP, instead of HTTPS), but you have correct URL.
 Could you, please, enable debug logging for SSL+TLS_MEM+HTTP_CLIENT and try it again?

**Comment by geertsbe** [comment]
Off course! Below is the output:
21:11:10.447 -> https://192.168.0.3:8086
21:11:15.433 -> [HTTP-Client][begin] url: https://192.168.0.3:8086/ping?verbose=true
21:11:15.433 -> [HTTP-Client][begin] host: 192.168.0.3 port: 8086 url: /ping?verbose=true
21:11:15.433 -> [HTTP-Client][sendRequest] type: 'GET' redirCount: 0
21:11:15.433 -> BSSL:_connectSSL: start connection
21:11:15.761 -> BSSL:_wait_for_handshake: failed
21:11:15.761 -> BSSL:Couldn't connect. Error = 'Certificate is expired or not yet valid.'
21:11:15.761 -> [HTTP-Client] failed connect to 192.168.0.3:8086
21:11:15.761 -> [HTTP-Client][returnError] error(-1): connection refused
21:11:15.761 -> [HTTP-Client][end] tcp is closed
21:11:15.761 -> InfluxDB connection failed: connection refused

This made me doubt about the certificate itself so I looked it up explicitly, sorry for the dutch but below is Validity(Geldigheid) of the cerftificate with the Not before(Niet voor) and Not after(Niet na):
![afbeelding](https://user-images.githubusercontent.com/2683859/78824529-c8653d00-79de-11ea-8047-290d3f2ab84c.png)

Obviously it is a self signed certificate, but I'm not sure this is the problem. I also looked up whether the ciphers could be of issue for the ESP8266 [here](https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/client-secure-class.html). Below the ciphers is used, I don't see any issue.
![afbeelding](https://user-images.githubusercontent.com/2683859/78825226-e2ebe600-79df-11ea-818b-2e9fd0f8d439.png)

**Comment by vlastahajek** [comment]
Of course, validity! To successfully validate the certificate you have to synchronize the time. Check the [SecureWrite Example](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/examples/SecureWrite/SecureWrite.ino#L54), please, how to that.

Another way to verify the server certificate, more suitable for self-signed certificates and without the necessity to synchronize time, is to use certificate fingerprint:
Just declare fingerprint variable: The fingerprint bellow is your certificate fingerprint, so you can copy it directly:
```cpp
const char ServerFingerPrint[] PROGMEM =  "16:0E:8D:FE:A4:1C:E0:63:FB:75:F5:BB:63:8F:1B:E3:3D:93:55:05";
```
and use it instead of certificate:

```cpp
Influx.setConnectionParamsV1(INFLUX_IP, INFLUX_DB_NAME, INFLUXDB_USER, INFLUXDB_PASSWORD, ServerFingerPrint);
```

**Comment by geertsbe** [comment]
"I don't need this synchronisation code", SMH. *delete*

I should've known this, thanks for the great amount of help. Nevertheless I Iearned this fingerprint trick which I didn't knew before.

Thanks a lot!
