### ISSUE TITLE
1.0 API is not functional on last version

### ISSUE THREAD

**Issue by sorriso93** [tobiasschuerg/InfluxDB-Client-for-Arduino#42]
Hello
I verified that api 1.0 is no more functional in last version.
Compilation is ok but then I get a reboot every time it the esp8266 tries to write on db. On 2.0 the code is ok

**Comment by vlastahajek** [comment]
Can you post your code, please? Basic code, as it was in the [Writing_single example](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/2.0.1/example/Writing_Single/Writing_Single.ino), works ok.

**Comment by balucio** [comment]
Hi, I have the same problem `write` call fail. Also enabling debug no Error is showed on `console`. In order to detect problem I had to call `Serial.println(influx.getLastErrorMessage());`. That showed me:
```
11:18:28.918 -> {"error":"unable to parse authentication credentials"}
```

**Comment by vlastahajek** [comment]
@balucio ,  could you, please, open a new issue? Your problem seem to be different. 
Include a relevant part of your sketch code and the debug output, please.

**Comment by vlastahajek** [comment]
@sorriso93, that has been several fixes since you posted this issue. Cold you, please, re-check this?
If the issue persists, attach your code.

**Comment by sorriso93** [comment]
Hello
I will try again. I basicallynused the example code of 1.0 in my code...

**Comment by sorriso93** [comment]
Hello, good news now it seems ok with version 3.1.2.
[The link to the project is here, thanks for your library](https://github.com/sorriso93/IOTroutertraffic)

**Comment by vlastahajek** [comment]
Nice project.
Thanks for the verification
