### ISSUE TITLE
Errores al probar la version 3.1.1

### ISSUE THREAD

**Issue by thinkUpRoger** [tobiasschuerg/InfluxDB-Client-for-Arduino#43]
compile el ejemplo 'BasicWrite'

este es el log de la compilacion

Visual studio code 1.44
PlatformIO Core 4.3.2a1  Home 3.1.1

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 1.12.0 > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESP8266 Influxdb 3.1.1
|   |-- HTTPClient 1.2
|   |   |-- WiFi 1.0
|   |   |-- WiFiClientSecure 1.0
|   |   |   |-- WiFi 1.0
|-- WiFi 1.0
Building in release mode
Compiling .pio\build\esp32doit-devkit-v1\src\main.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\libe0a\ESP8266 Influxdb_ID1639\InfluxDbClient.cpp.o
In file included from src\main.cpp:22:0:
.pio/libdeps/esp32doit-devkit-v1/ESP8266 Influxdb_ID1639/src/InfluxDbClient.h:44:19: warning: missing terminating ' character
 #error AxTLS doesn't work
                   ^
In file included from .pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:27:0:
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.h:44:19: warning: missing terminating ' character
 #error AxTLS doesn't work
                   ^
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-adc.c.o
In file included from .pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:27:0:
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.h: In constructor 'Point::Point(String)':
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.h:103:12: error: 'Point::_measurement' will be initialized after [-Werror=reorder]
     String _measurement;
            ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.h:101:12: error:   'String Point::_tags' [-Werror=reorder]        
     String _tags;
            ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:75:1: error:   when initialized here [-Werror=reorder]        
 Point::Point(String measurement):
 ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp: In member function 'void Point::setTime(WritePrecision)':    
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:119:58: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
              sprintf(buff, "%06d000",  micros()%1000000uL);
                                                          ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:119:58: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:123:55: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
              sprintf(buff, "%06d",  micros()%1000000uL);
                                                       ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:123:55: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:127:51: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
              sprintf(buff, "%03d",  millis()%1000u);
                                                   ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:127:51: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp: In member function 'bool InfluxDBClient::flushBuffer()':     
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:376:35: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
     while(data = prepareBatch(size)) {
                                   ^
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-bt.c.o
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-cpu.c.o
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp: At global scope:
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:58:15: warning: 'String escapeJSONString(String&)' declared 'static' but never defined [-Wunused-function]
 static String escapeJSONString(String &value);
               ^
.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.cpp:597:15: warning: 'String escapeTagValue(const char*)' defined 
but not used [-Wunused-function]
 static String escapeTagValue(const char *value) {
               ^
cc1plus.exe: some warnings being treated as errors
*** [.pio\build\esp32doit-devkit-v1\libe0a\ESP8266 Influxdb_ID1639\InfluxDbClient.cpp.o] Error 1
========================================================= [FAILED] Took 5.77 seconds =========================================================

**Comment by vlastahajek** [comment]
@thinkUpRoger, thanks for reporting. The actual errors are not dangerous, cause members don't depend on themselves. 
If you haven't already fixed it yourself,  the quick workaround is to edit `.pio\libdeps\esp32doit-devkit-v1\ESP8266 Influxdb_ID1639\src\InfluxDbClient.h` and change lines 101-104:
```cpp
    String _measurement;
    String _tags;
    String _fields;
    String _timestamp; 
```

**Comment by thinkUpRoger** [comment]
I continued testing version 3.1.1
(I don't know if another thread should be opened)
write a point with **precision in microseconds** not work correctly

Description
![image](https://user-images.githubusercontent.com/45951967/79494452-0838af80-7ff1-11ea-90cc-db627343fc2d.png)

this write a point in 1970
![image](https://user-images.githubusercontent.com/45951967/79494969-e2f87100-7ff1-11ea-9dbb-497fe35b075c.png)

Fix in  InfluxDBClient.cpp file
![image](https://user-images.githubusercontent.com/45951967/79495386-877ab300-7ff2-11ea-8631-157d2bcd22ba.png)

![image](https://user-images.githubusercontent.com/45951967/79495720-066feb80-7ff3-11ea-872b-eb056f354dab.png)
Write correctly date
![image](https://user-images.githubusercontent.com/45951967/79496738-92cede00-7ff4-11ea-94c2-9e1686a9cc4e.png)

**Comment by vlastahajek** [comment]
@thinkUpRoger, please create a new issue for this.

**Comment by thinkUpRoger** [comment]
ok thanks 
issue created
https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/issues/49
