### ISSUE TITLE
error: 'X509List' in namespace 'BearSSL' does not name a type

### ISSUE THREAD

**Issue by Shane-Hanson** [tobiasschuerg/InfluxDB-Client-for-Arduino#44]
When compiling for both Generic ESP2866 and Wemos D1 I receive the following error...

In file included from C:\Users\Shane\Documents\Arduino\libraries\ESP8266_Influxdb\src/InfluxData.h:27:0,

                 from C:\Users\Shane\Documents\Arduino\libraries\ESP8266_Influxdb\src/InfluxDb.h:27,

                 from C:\Users\Shane\Documents\Arduino\influx_basic_test_13_04_2020\influx_basic_test_13_04_2020.ino:3:

C:\Users\Shane\Documents\Arduino\libraries\ESP8266_Influxdb\src/InfluxDbClient.h:243:3: error: 'X509List' in namespace 'BearSSL' does not name a type

   BearSSL::X509List *_cert = nullptr;   

   ^

Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Shane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi 
Using library ESP8266_Influxdb at version 3.1.1 in folder: C:\Users\Shane\Documents\Arduino\libraries\ESP8266_Influxdb 
Using library ESP8266HTTPClient at version 1.1 in folder: C:\Users\Shane\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266HTTPClient 
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by vlastahajek** [comment]
Hard to say what's wrong without seeing your sketch.  
Examples from the versions before 3.x.x still work.

**Comment by Shane-Hanson** [comment]
Sketch is identical to your basic test, see below..

`#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <InfluxDb.h>

#define INFLUXDB_HOST "http://<redacted>:8086"
#define WIFI_SSID "<redacted>"
#define WIFI_PASS "<redacted>"

ESP8266WiFiMulti WiFiMulti;
Influxdb influx(INFLUXDB_HOST);

void setup() {
  Serial.begin(9600);
  Serial.println(" ### Hello ###");

  WiFiMulti.addAP(WIFI_SSID, WIFI_PASS);
  Serial.print("Connecting to WIFI");
  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(100);
  }
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  influx.setDb("test");
// Uncomment the following lines to use the v2.0 InfluxDB
// influx.setVersion(2);
// influx.setOrg("myOrganization");
// influx.setBucket("myBucket");
// influx.setToken("myToken");
  Serial.println("Setup done");
}


int loopCount = 0;

void loop() {
  loopCount++;

  InfluxData row("temperature");
  row.addTag("device", "alpha");
  row.addTag("sensor", "one");
  row.addTag("mode", "pwm");
  row.addValue("loopCount", loopCount);
  row.addValue("value", random(10, 40));

  influx.write(row);

  delay(5000);
}`

Thanks

Shane

**Comment by vlastahajek** [comment]
@Shane-Hanson, thanks for the quick reply. I actually found the problem in the version of the ESP8266 Arduino platform you are using. The actual version is 2.6.3. Yours 2.4.2 is quite obsolete, and in the 2.5.0 there was introduced BearSSL SSL/TLS API.
If you upgrade the ESP8266 board in the board manager it will fix the problem.

**Comment by Shane-Hanson** [comment]
oh wow! thanks for you help! I'll do that immediately!! :-)

Shane
