### ISSUE TITLE
error “This library currently supports only ESP8266 and ESP32.”

### ISSUE THREAD

**Issue by Davidffry** [tobiasschuerg/InfluxDB-Client-for-Arduino#46]
"error “This library currently supports only ESP8266 and ESP32.”" 

This is explicitly message but how I workarround this problem?
in fact I have a MKR 1010 and I need to send data in my InfluxDB v1 for now.

any help?

**Comment by vlastahajek** [comment]
@Davidffry, when looking at MKR 1010 WiFi library [WiFiNINA](https://www.arduino.cc/en/Reference/WiFiNINA), I see, it doesn't support HTTP Client API, which makes it difficult to add support to his library.

However, you can construct HTTP post with the help of a number of examples there and create a call to [InfluxDB Write API](https://docs.influxdata.com/influxdb/v1.8/guides/write_data/), which is quite simple.
