### ISSUE TITLE
Can't get this working!

### ISSUE THREAD

**Issue by alphabeta279** [tobiasschuerg/InfluxDB-Client-for-Arduino#48]
Hi there,

Doing something completely daft I'm sure, but I've had a temp sensor working on an ESP 8266 fine posting to Thingspeak, I'm wanting to now also write to my local NAS to an InfluxDB.... cue this awesome library...!

Turned on debugging, but it doesn't seem to produce anything useful here's the relevant part - it's booting a fail error, but can't see why!

Any help much appreciated!

`22:50:43.328 -> Wifi Connection Successful
22:50:43.361 -> The IP Address of the Sensor is:192.168.1.35
22:50:43.361 -> [D] Validating connection to 192.168.1.5:8086/ping?verbose=true
22:50:43.361 -> [E] begin failed
22:50:43.361 -> InfluxDB connection failed: 
22:50:43.361 -> 192.168.1.5:8086
22:50:43.361 -> Exiting DB Connection
`

Here's my full code (with just sensitive passes/apis removed):
`
// v2 Temp sensor
// Attempting to connect to home database to log data rather than Thingspeak

#include <DHT.h>
#include <ESP8266WiFi.h>
#include <ESP8266HTTPClient.h>
#include <InfluxDbClient.h>

#define SSID "XXX" //your network name
#define PASS "XXX" //your network password
#define API "XXX" //api string

// Temp Sensor 1 api - XXX
// Temp Sensor 2 api - XXX
// Temp Sensor 3 api - XXX
// Temp Sensor 4 api - XXX

// Connection Parameters for Jupiter InfluxDB
#define INFLUXDB_URL "192.168.1.5:8086"
#define INFLUXDB_DB_NAME "home_assistant"
#define INFLUXDB_USER "XXX"
#define INFLUXDB_PASSWORD "XXX"

// Single InfluxDB instance
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);
// Define data point with measurement name 'device_status`
Point sensor("wifi_status");

#define IP "api.thingspeak.com" // thingspeak.com
#define PORT 80
#define DHTPIN 4     // what pin the DHT sensor is connected to
#define DHTTYPE DHT22   // Change to DHT22 if that's what you have
#define BAUD_RATE 115200 //Another common value is 9600
#define DELAY_TIME 900000 //time in ms between posting data to Home Server

DHT dht(DHTPIN, DHTTYPE);

//this runs once
void setup()
{
  Serial.begin(BAUD_RATE);

  // Connect to WIFI
  WiFi.begin(SSID, PASS);
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(500);
    Serial.print("*");
  }
  Serial.println("");
  Serial.println("Wifi Connection Successful");
  Serial.print("The IP Address of the Sensor is:");
  Serial.println(WiFi.localIP());

  //initalize DHT sensor
  dht.begin();

// set InfluxDB database connection parameters
 client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME, INFLUXDB_USER, INFLUXDB_PASSWORD);

 // Add constant tags - only once
  sensor.addTag("device", "1111");
  sensor.addTag("SSID", "2222");

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
    } else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
    Serial.println(client.getServerUrl());
    Serial.println("Exiting DB Connection");
  
  }
  
}

//this runs over and over
void loop() {
  float h = dht.readHumidity();
  Serial.print("Humidity: ");
  Serial.println(h);
  // Read temperature as Fahrenheit (isFahrenheit = true)
  float c = dht.readTemperature();
  Serial.print("Temperature: ");
  Serial.println(c);

  // Check if any reads failed and exit early (to try again).
  if (isnan(h) || isnan(c)) {
    Serial.println("Reading DHT22 Failed, exiting");
    return;
  }

  //update ThingSpeak channel with new values
  updateTemp(c, h);

  // Update Influx DB
  sensor.addField("rssi", "3333");

  //wait for delay time before attempting to post again 
  delay(DELAY_TIME);
}

bool updateTemp(float tempC, float humid) {

  WiFiClient client;    // Create a WiFiClient to for TCP connection

  if (!client.connect(IP, PORT)) {
    Serial.println("HTTP connection failed");
    return false;
  }

  Serial.println("Sending data to server");
  if (client.connected()) {

    
    // Then write to Thingspeak
    client.print("GET /update?api_key="); client.print(API);
    client.print("&field1="); client.print(String(tempC));
    client.print("&field2="); client.print(String(humid));
    client.println(" HTTP/1.1");
    client.print("Host: "); client.println(IP);
    client.println("Connection: close");
    client.println();    //extra "\r\n" as per HTTP protocol
  }

  // wait for data to be available
  unsigned long timeout = millis();
  while (client.available() == 0) {
    if (millis() - timeout > 5000) {
      Serial.println("HTTP Client Timeout !");
      client.stop();
      return false;
    }
  }

  Serial.println("Receiving HTTP response");
  while (client.available()) {
    char ch = static_cast<char>(client.read());
    Serial.print(ch);
  }
  Serial.println();

  Serial.println("Closing TCP connection");
  client.stop();
  return true;
}
`

**Comment by vlastahajek** [comment]
@alphabeta279 , InfluxDB url must start with protocol, mostly `http://`.

**Comment by alphabeta279** [comment]
Thanks vlastahajek - that's worked a treat! <faceplant>

**Comment by alphabeta279** [comment]
Sorry showing my lack of experience of InfluxDB - should this string not create a measurement in the database?: 

Writing to InfluxDB: DaveTest,device=1111,SSID=2222 rssi="3333"

Can't see anything obvious wrong with it and no errors returning, just can't find this data in chronograf anywhere - do I need to create the measurements somehow in InfluxDB first? (I've created the database already)

**Comment by vlastahajek** [comment]
I don't see anything wrong with the line protocol.  However, I don't see any write int the previous sketch (please use markdown preformat syntax for complete source code).
Assuming that you've written the data, DataExplorer in Chronograf easily displays just numbers by default.  As your field `rssi` is type string (I would advise you to keep it as an integer, as returned from `WiFi.RSSI()`, but as you've already written string into such field, you will have to either rename the field or drop complete measurement).
It applies the `mean` function by default and it is not valid for string fields. It should give you a warning. Also, it shows the line chart by default and it cannot display string values here. It should offer you switching to the table view.
IMHO, the easiest way to test whether your data is written is by use of the `influx` command-line tool. Here you can (after select db by command `use <your-db>`) write simple, SQL-like, select:
`select * from DaveTest`. If you have a lot of points you can restrict it:
 - by time, data from last hour: `select * from DaveTest where time > now()-1h`
- by number of recent records: `select * from DaveTest order by time desc limit 10`

**Comment by alphabeta279** [comment]
Ah useful, does this line not add data to a field?

sensor.addField("rssi", "3333");

I 'thought' this would add the value 3333 as a test, but I could be completely wrong!

**Comment by vlastahajek** [comment]
That line is fine. It adds a field to the point.
But the point must be written to the DB:
```
client.writePoint(sensor);
```
Check example again, please: [BasicWrite](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/examples/BasicWrite/BasicWrite.ino)

**Comment by alphabeta279** [comment]
Ah, daft sorry - must've dropped that out in attempting to debug - all working perfectly now!
