### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by farthinder** [tobiasschuerg/InfluxDB-Client-for-Arduino#5]
Hi!

I needed TLS and ESP32 support in this otherwise excellent library, so I have hacked that in to a branch in a forked version of your library.

I'm more of a Java-dev/Sysadmin my self if you are wondering why I've butchered your library. 

https://github.com/farthinder/ESP32_Secure_Influx_DB/tree/ESP32-Secure

If you are interested in my findings I´d be more than happy if you added them to your version of the library.

**Comment by jardous** [comment]
I would also appreciate the ESP32 support

**Comment by farthinder** [comment]
@jardous have a look at my branch.

**Comment by jardous** [comment]
@farthinder thanks, I already have.
I do not need it secure so it is easier for me to just add support for ESP32 to the original library.

**Comment by tobiasschuerg** [comment]
@farthinder I looked at you code, hoping that I could just merge your changes, but you really "butchered" it ;-)

As I don't have time right now, nor the required set up, this will stay open.

PR welcome!

**Comment by tobiasschuerg** [comment]
The library got completely rewitten to also support InfluxDb 2 with tls etc., please check out [version 3](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/latest).
If your issue still remains, please open a new issue.
