### ISSUE TITLE
When a point not have tags the database reply with a error message

### ISSUE THREAD

**Issue by thinkUpRoger** [tobiasschuerg/InfluxDB-Client-for-Arduino#50]
The device send a point
`adc1_ch1, value=1.905,count=16i 1586936036015835`

Database response:
`[D] Response:
{"error":"unable to parse 'adc1_ch1, value=1.905,count=16i 1586936036015835': missing tag key\nunable to parse 'adc1_ch1, value=1.902,count=17i 1586936038015642': missing tag key\nunable to parse 'adc1_ch1, value=1.902,count=18i 1586936040015650': missing tag key"}
`
Cause:
The library does not generate a point with the correct protocol:

`<measurement>[,<tag-key>=<tag-value>...] <field-key>=<field-value>[,<field2-key>=<field2-value>...] [unix-nano-timestamp]`

![image](https://user-images.githubusercontent.com/45951967/79532830-54f9a600-8044-11ea-83fd-ec55a214b091.png)

FIX:
![image](https://user-images.githubusercontent.com/45951967/79533040-e701ae80-8044-11ea-9095-1ced537d781a.png)

The database write the point without tags
![image](https://user-images.githubusercontent.com/45951967/79533084-0a2c5e00-8045-11ea-8c13-8abb3f051d39.png)

**Comment by vlastahajek** [comment]
@thinkUpRoger, good catch, thanks for reporting it.
