### ISSUE TITLE
Reading data from InfluxDB

### ISSUE THREAD

**Issue by HaViGit** [tobiasschuerg/InfluxDB-Client-for-Arduino#52]
Hi,

I'm sure your solution does the job and writes to InfluxDB ;-) My question is not about writing but reading from an Influx database and I understand your solution is not intended to do so. Wondering if you can advice me about software to read from my database on a Raspberry Pi and display a value from it on a display connected to an ESP8266.

Regards, 

Hans.

**Comment by tobiasschuerg** [comment]
You can [query data easily via http](https://docs.influxdata.com/influxdb/v1.8/guides/query_data/).

**Comment by HaViGit** [comment]
Thanks Tobius, knowing this must be possible I know what to search for.

**Comment by vlastahajek** [comment]
Release [3.2.0](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/releases/tag/3.2.0) added Flux query support. Usable also for InfluxDB 1.7+.
