### ISSUE TITLE
InfluxDBClient::validateConnection fails for v1.x DBs

### ISSUE THREAD

**Issue by ossfm** [tobiasschuerg/InfluxDB-Client-for-Arduino#58]
Hello, Thank you for creating and maintaining this library. I recently used version 3.1.2 to connect a ESP8266 to InfluxDB 1.6.4 running on a Raspberry Pi 3B+. I found a bug in the function InfluxDBClient::validateConnection().

When calling the validateConnection() function, an error is given which prevents connecting to the DB. The issue is that the expected return status is hard coded to 200 no matter the DB version 1 or 2. The comment on line 478 in src/InfluxDbClient.cpp gives a hint. Version 1.x DBs have a return code of 204, with or without the verbose option. 

`// on version 1.x /ping will by default return status code 204, without verbose`

I modified my installed file src/InfluxDbClient.cpp to add a local variable (_expectedStatusCode). This variable is dependent on the DB version. See the modifications below. The modifications work well on my application. 

Insert between lines 479 and 480:
`int _expectedStatusCode = _dbVersion==2?200:204;`

Line 492 modification:
`postRequest(_expectedStatusCode);`

Line 497 modification:
`return _lastStatusCode == _expectedStatusCode;`

**Comment by vlastahajek** [comment]
@ossfm, a similar issue was fixed with #34 and released in v3.1.0 and it surely works with InfluxDB 1.7+. Your InfluxDB server version is more than 18 months old, so I strongly advise you to upgrade to the recent 1.8. Upgrading is just a matter of new deb installation, no migration, or what so ever.

**Comment by ossfm** [comment]
Thank you for the hint. I hadn't looked at the age of the raspbian package. I'll try the upgrade.
