### ISSUE TITLE
Error compiling  BatchWrite example on Adafruit ESP32 Feather

### ISSUE THREAD

**Issue by kmf909** [tobiasschuerg/InfluxDB-Client-for-Arduino#71]
hi. i try to use batch write. first step i try to run the default code up until wifi connected and comment the rest. the eror as below. i use ubuntu 18 with arduino ide 1.8.11

/Arduino/libraries/InfluxDB-Client-for-Arduino-master/src/InfluxDbClient.cpp:27:26: fatal error: core_version.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Adafruit ESP32 Feather.

could you assist.

**Comment by vlastahajek** [comment]
@kmf909, do you have ESP32 Arduino SDK installed?  Can you locate that file among the SDK files?

**Comment by kmf909** [comment]
silly me, multiple library causing the issue. @vlastahajek
