### ISSUE TITLE
ESP8266 BasicWrite compile error

### ISSUE THREAD

**Issue by schober-stl** [tobiasschuerg/InfluxDB-Client-for-Arduino#72]
When compiling BasicWrite for Adafruit Feather HUZZAH with ESP8266, receive the following error:
___________________________________________________________
C:\Users\joschob\Documents\Arduino\libraries\InfluxDB-Client-for-Arduino-master\src\util\helpers.cpp: In function 'void timeSync(const char*, const char*, const char*, const char*)':

C:\Users\joschob\Documents\Arduino\libraries\InfluxDB-Client-for-Arduino-master\src\util\helpers.cpp:32:57: error: 'configTzTime' was not declared in this scope

   configTzTime(tzInfo,ntpServer1, ntpServer2, ntpServer3);

                                                         ^

exit status 1
Error compiling for board Adafruit Feather HUZZAH ESP8266.
_______________________________________________________________

**Comment by vlastahajek** [comment]
@schober-stl, make sure you have ESP8266 SDK 2.7..

**Comment by schober-stl** [comment]
In Arduino IDE, installed ESP8266 version 2.7.1 by ESP8266 Community.
Compile now successful.

thank you.
