### ISSUE TITLE
ESP8266 SecureBatchWrite compile error

### ISSUE THREAD

**Issue by schober-stl** [tobiasschuerg/InfluxDB-Client-for-Arduino#73]
When compiling SecureBatchWrite example code for Adafruit Feather HUZZAH with ESP8266, receive the following error (SecureWrite example code compile successful)-

----------------------------------------------
C:\Users\joschob\AppData\Local\Temp\arduino_modified_sketch_336161\SecureBatchWrite.ino: In function 'void loop()':

SecureBatchWrite:99:14: error: too few arguments to function 'void timeSync(const char*, const char*, const char*, const char*)'

     timeSync();

              ^

In file included from C:\Users\joschob\Documents\Arduino\libraries\InfluxDB-Client-for-Arduino-master\src/InfluxDbClient.h:34:0,

                 from C:\Users\joschob\AppData\Local\Temp\arduino_modified_sketch_336161\SecureBatchWrite.ino:25:

C:\Users\joschob\Documents\Arduino\libraries\InfluxDB-Client-for-Arduino-master\src/util/helpers.h:35:6: note: declared here

 void timeSync(const char *tzInfo, const char* ntpServer1, const char* ntpServer2 = nullptr, const char* ntpServer3 = nullptr);

      ^

exit status 1
too few arguments to function 'void timeSync(const char*, const char*, const char*, const char*)'
----------------------------------------------

**Comment by vlastahajek** [comment]
@schober-stl, thanks for reporting this issue. Just copy timeSync call from line 81 to line 99 and it should be ok.

**Comment by schober-stl** [comment]
> @schober-stl, thanks for reporting this issue. Just copy timeSync call from line 81 to line 99 and it should be ok.

thank you, compiling SecureBatchWrite example code for Adafruit Feather HUZZAH with ESP8266 now successful.

**Comment by vlastahajek** [comment]
Reopen as this issue must be fixed globally
