### ISSUE TITLE
Query error with InfluxDB v1.8.0

### ISSUE THREAD

**Issue by Wally-rc3** [tobiasschuerg/InfluxDB-Client-for-Arduino#74]
I'm trying to query an InfluxDb database (**v1.8.0**) with the use of ESP8266 but during this process the query fails and I get the following error: `404 page not found`

I also tested the Flux query with Cronograph and it seems to work without any problems, while importing this string into the code it doesn't seem to work anymore.

for information purpose I leave my current code:

```
#include <ESP8266WiFiMulti.h>
ESP8266WiFiMulti wifiMulti;



#include <InfluxDbClient.h>
#include <InfluxDbCloud.h>

// WiFi AP SSID
#define WIFI_SSID         "WIFI_SSID"
// WiFi password
#define WIFI_PASSWORD     "WIFI_PASSWORD"

#define INFLUXDB_URL      "http://192.168.5.125:8086"
#define INFLUXDB_DB_NAME  "database_name"
#define INFLUXDB_USER     "user"
#define INFLUXDB_PASSWORD "passwd"


#define TZ_INFO "CET-1CEST,M3.5.0,M10.5.0/3"

InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);



//--SETUP--
void setup() {
  Serial.begin(9600);

  // Setup wifi
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);

  Serial.print("Connecting to wifi");
  while (wifiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME, INFLUXDB_USER, INFLUXDB_PASSWORD);
  
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.print(WiFi.localIP());

  Serial.println();
  
  Serial.print("Singnal strength:");
  Serial.print(WiFi.RSSI());
  Serial.print("dBm");
  
  Serial.println();

  
  timeSync(TZ_INFO, "pool.ntp.org", "time.nis.gov");

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  } 
  else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }

  Serial.println();
}



//--LOOP--
void loop() {

  VALUE();

  Serial.println("Wait 10s");
  delay(10000);
}



//--VALUE1--
void VALUE() {
  
  String query = "from(bucket: \"database_name/autogen\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"measurement_name\" and (r._field == \"value_name\")) |> bottom(n:1)";

  // Print composed query
  Serial.print("Querying with: ");
  Serial.println(query);

  // Send query to the server and get result
  FluxQueryResult result = client.query(query);

  while (result.next()) {
  long value = result.getValueByName("_value").getLong();
  Serial.print(value);

  Serial.println();

  }    

  if(result.getError() != "") {
    Serial.print("Query result error: ");
    Serial.println(result.getError());
    }
    
  result.close();
}
```

**Comment by vlastahajek** [comment]
@Wally-rc3, querying InfluxDB 1.8 with V1 client approach was not tested. It works using the [forward compatibility APIs](https://docs.influxdata.com/influxdb/latest/tools/api/#influxdb-2-0-api-compatibility-endpoints).
Use the client as for InfluxDB 2, but change the authentication token to the format: `<username>:<password>`, or leave empty, if there is no authentication on the server. However, in this way, you cannot use the `validateConnection`, as it uses InfuxDB 2 `/ready` endpoint, which is not available on InfluxDB 1`. In the next version of this lib, we will use a different compatible status endpoint and the 
`validateConnection` will work in all the ways.

If you want to stay with the V1 approach, there is a small change in the lib sources:  After the [line 297 in the src/InfluxDBClient.cpp](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/src/InfluxDbClient.cpp#L297) add this: `_queryUrl += "?"`. It should look:
```cpp
    _writeUrl += auth;  
    _queryUrl += "?";
    _queryUrl += auth;
```

**Comment by Wally-rc3** [comment]
First of all, thank you for the very quick response given to me.
However, I'm afraid but I don't fully understand the issue.
So to define username and password I have to set in the code only the `TOKEN` 

defined as 
`#define INFLUXDB_TOKEN "admin: adminpasswd"` 

and do not put:
```
#define INFLUXDB_USER "admin"
#define INFLUXDB_PASSOWRD "adminpasswd"
``` 

since these writings are refered to the original API's.
Correct?

**Comment by vlastahajek** [comment]
You have to either:
1. Set autheticaton token: `#define INFLUXDB_TOKEN "admin:adminpasswd"` - without the separating space
1. Use different setter for params: `client.setConnectionParams(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_DB_NAME, INFLUXDB_TOKEN)` - set `INFLUXDB_ORG` to empty string (`#define INFLUXDB_ORG ""`)
1. Comment out the call: `client.validateConnection()`

or
1. Edit  [src/InfluxDBClient.cpp](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/src/InfluxDbClient.cpp#L297)
1. add line: `_queryUrl += "?";` behind the line 297.

**Comment by Wally-rc3** [comment]
Okay, now I understand a little better.
In my case works like a charm the following configuration:
```
#define INFLUXDB_TOKEN "admin: adminpasswd"
client.setConnectionParamsV1 (INFLUXDB_URL, INFLUXDB_DB_NAME, INFLUXDB_TOKEN);
```

While through the steps you recommend you (setter parms as V2) I always find the same error.
So I will keep the code as shown below because it is the only configuration that works for me. 


```
#include <ESP8266WiFiMulti.h>
ESP8266WiFiMulti wifiMulti;



#include <InfluxDbClient.h>
#include <InfluxDbCloud.h>

// WiFi AP SSID
#define WIFI_SSID             "WIFI_SSID"
// WiFi password
#define WIFI_PASSWORD     "WIFI_PSW"

#define INFLUXDB_URL      	"INFLUXDB_URL"
#define INFLUXDB_DB_NAME      "INFLUXDB_DB_NAME"
#define INFLUXDB_TOKEN          "INFLUXDB_USER:INFLUXDB_PSW"


#define TZ_INFO "CET-1CEST,M3.5.0,M10.5.0/3"

InfluxDBClient client(INFLUXDB_URL, INFLUXDB_DB_NAME);



//--SETUP--
void setup() {
  Serial.begin(9600);

  // Setup wifi
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP(WIFI_SSID, WIFI_PASSWORD);

  Serial.print("Connecting to wifi");
  while (wifiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  client.setConnectionParamsV1(INFLUXDB_URL, INFLUXDB_DB_NAME,  INFLUXDB_TOKEN);
 
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.print(WiFi.localIP());

  Serial.println();
 
  Serial.print("Singnal strength:");
  Serial.print(WiFi.RSSI());
  Serial.print("dBm");
 
  Serial.println();

 
  timeSync(TZ_INFO, "pool.ntp.org", "time.nis.gov");

  // Check server connection
  if (client.validateConnection()) {
    Serial.print("Connected to InfluxDB: ");
    Serial.println(client.getServerUrl());
  }
  else {
    Serial.print("InfluxDB connection failed: ");
    Serial.println(client.getLastErrorMessage());
  }
}



//--LOOP--
void loop() {

  VALUE();

  Serial.println("Wait 10s");
  delay(10000);
}



//--VALUE1--
void VALUE() {
 
  String query = "from(bucket: \"INFLUXDB_DB_NAME/autogen\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"INFLUXDB_DB_MEASUREMNET\" and (r._field == \"INFLUXDB_FIELD\")) |> bottom(n:1)";

 
  // Print composed query
  Serial.print("Querying with: ");
  Serial.println(query);

  // Send query to the server and get result
  FluxQueryResult result = client.query(query);

  while (result.next()) {
  double value = result.getValueByName("_value").getDouble();
  Serial.print(value);
  Serial.println();
  }   

  if(result.getError() != "") {
    Serial.print("Query result error: ");
    Serial.println(result.getError());
    }
   
  result.close();
}


```

**Comment by vlastahajek** [comment]
Well, I supposed you have a server requiring authentication. 
In the case of an unauthenticated server, it works without a problem.

In case of using V2 API, it will return 404 not found only to `validateConnection()`

**Comment by Wally-rc3** [comment]
Yes, my server requires authentication


In that case then the solution would be to comment on the `validateConnection()` function as you suggested before.

Thank you very much for helping
