### ISSUE TITLE
vector: no such file or directory

### ISSUE THREAD

**Issue by jpmorris** [tobiasschuerg/InfluxDB-Client-for-Arduino#79]
On linux (arch), installing latest arduino download from website.  I get the following error:

```
In file included from /home/jmorris/Arduino/libraries/ESP8266_Influxdb/src/InfluxDbClient.h:33:0,
                 from /home/jmorris/commonDrive/CloudStation/docs/Arduino/influx_write/influx_write.ino:28:
/home/jmorris/Arduino/libraries/ESP8266_Influxdb/src/query/FluxParser.h:30:10: fatal error: vector: No such file or directory
 #include <vector>
          ^~~~~~~~
compilation terminated.
```
I've tried installing libaries 'Vector', 'ArduinoSTL' and others.  Nothing enables vector support that this library uses. 

Granted im a newbie and may be making a dumb mistake, but the instructions should say at  least SOMETHING about installing vector support for people who start with vanilla install.

**Comment by vlastahajek** [comment]
@jpmorris, For which device are you trying to compile sketch? This library supports just ESP8266  (and its clones) and  ESP32.
Both SDKs include STL.

**Comment by jpmorris** [comment]
I'm using an Arduino Uno Wifi V2 which I thought had a ESP32

https://www.arduino.cc/en/Guide/ArduinoUnoWiFiRev2

**Comment by vlastahajek** [comment]
Unfortunately, this device uses ESP32 as a peripheral for WiFi connection, not as the main chip. 
So, the main WiFi library for your device is [WIFININA](https://www.arduino.cc/en/Reference/WiFiNINA), which is not supported yet.
See #66.

**Comment by jpmorris** [comment]
Ok Sorry for the noise.  If you see this confusion more often than me, you probably should mention this weird case in the Readme.
