### ISSUE TITLE
send header failed

### ISSUE THREAD

**Issue by WalterHolland** [tobiasschuerg/InfluxDB-Client-for-Arduino#80]
I used the SecureWrite example on an ESP32, but get connection fail and write fail.
I searched but can not find anything on this.
I uncommented the debug line in InfluxDbClient.cpp but that did not give any extra info.
I use the influx db free cloud server this on this server:

// InfluxDB v2 server url, e.g. https://eu-central-1-1.aws.cloud2.influxdata.com (Use: InfluxDB UI -> Load Data -> Client Libraries)
#define INFLUXDB_URL "https://westeurope-1.azure.cloud2.influxdata.com"

Of course checked all tokens and ID's.

This my serial monitor output:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:8740
load:0x40080400,len:5788
entry 0x4008069c
Connecting to wifi
Syncing time.
Synchronized time: Sun Jul  5 21:49:22 2020

InfluxDB connection failed: send header failed
Writing: wifi_status,device=ESP32,SSID=Ziggo251E1B9 rssi=-82i
InfluxDB write failed: send header failed
Wait 10s

Can anyone help on this issue

**Comment by vlastahajek** [comment]
@WalterHolland, do you have the latest ESP32 Arduino SDK 1.0.4?

**Comment by WalterHolland** [comment]
No, I did not, I had SDK 1.0.3. Updated tot SDK 1.0.4 and it worked but  only after I requested a new bucket and new token. Thanks.
