### ISSUE TITLE
Help needed: Arduino Uno (clone) with ESP-01 to send sensor data to local InfluxDB instance

### ISSUE THREAD

**Issue by ig-perez** [tobiasschuerg/InfluxDB-Client-for-Arduino#81]
Hi all, first of all sorry If I'm asking a very basic question, a newbie here. I have this setup:
- Arduino UNO clone
- ESP-01 (ESP8266 chip)
- Water sensor data

All connected together using a breadboard. My intention is to send water sensor data to my localhost InfluxDB instance through the ESP-01 module, but I'm unable to upload the code to the Arduino One, when doing it I have `esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header` 

I have already installed the `esp8266 board` v. 2.7.2 and selected `Arduino` from `ESP8266 Boards` in the `Tools -> Boards` menu from the IDE. I have tested with all models (Primo, Star OTTO, and Uno WIFI) same error in all of them. Also, I get the same error when selecting `Generic ESP8266 Module`:
![image](https://user-images.githubusercontent.com/33359427/87492583-7a308d00-c610-11ea-93a5-c20ad66d533a.png)

I have been able to upload other sketches to my Arduino Uno before without a problem with the default Arduino Uno, but when trying to use the influx DB client I get the `This library currently supports only ESP8266 and ESP32` / `FluxParser.h:30:10: fatal error: vector: No such file or directory` error.
![image](https://user-images.githubusercontent.com/33359427/87492490-46edfe00-c610-11ea-857b-1f3897c586b6.png)

I'm an Ubuntu 18.04 user and the Arduino is located on `/dev/ttyACM0`. What I'm doing wrong?

I'll really appreciate some guidance here, thanks!

**Comment by vlastahajek** [comment]
@ig-perez, this library supports deployment when you are directly programming an ESP* device, not an AVR or SAMD Arduino board.
I  guess you use ESP-01 as wifi peripheral, while ESP-01 runs AT command based firmware. This is not supported.

**Comment by ig-perez** [comment]
I see, yes, I'm using the ESP-01 as a peripheral. Ok. Thanks, and sorry for the confusion. I will send the data using the AT commands then.
