### ISSUE TITLE
Error compiling with VSCode and PlatformIO extension

### ISSUE THREAD

**Issue by jlboygenius** [tobiasschuerg/InfluxDB-Client-for-Arduino#83]
There's probably a way to do this, maybe install the G++ compiler for VSCode, but it seems easier to just update the InfluxDB library for most users.

Seems like the Microsoft C++ compiler doesn't have some features that the Arduino compiler does. I get a few errors when Trying to include the InfluxDB library in my project in VSCode, but everything is OK in the Arduino IDE.

All errors are related to the way For Loops are setup.
lib\ESP8266 Influxdb\src\InfluxDbClient.cpp:663:18: error: 'begin' was not declared in this scope
     for (char c: value)

\lib\ESP8266 Influxdb\src\InfluxDbClient.cpp:663:18: error: 'end' was not declared in this scope
     for (char c: value)

\lib\ESP8266 Influxdb\src\query\CsvReader.cpp:68:19: error: 'begin' was not declared in this scope
     for (char c : line) {

\lib\ESP8266 Influxdb\src\query\CsvReader.cpp:68:19: error: 'end' was not declared in this scope
     for (char c : line) {

\lib\ESP8266 Influxdb\src\util\helpers.cpp:81:18: error: 'begin' was not declared in this scope
     for (char c: key)

\lib\ESP8266 Influxdb\src\util\helpers.cpp:81:18: error: 'end' was not declared in this scope
     for (char c: key)

**Comment by jlboygenius** [comment]
Changed my local copy to use normal boring loops like this:
for (int x;x<line.length();x++)
    {
        char c = line[1];

to resolve the compile issue

**Comment by vlastahajek** [comment]
@jlboygenius, this library is being developed in VSCode on Windows 10. The compiler always comes with the device SDK.  This library is targeted for ESP32 and ESP8266. 
You haven't mentioned for which device you are trying to compile that.

**Comment by jlboygenius** [comment]
ESP32. 

[env:esp32dev]
platform = espressif32@1.7.0
board = esp32dev
framework = arduino

**Comment by vlastahajek** [comment]
So, what extension are you using? This doesn't seem to be the Arduino extension.

**Comment by jlboygenius** [comment]
I'm still just beginning the switch to VSCode, so bear with me.

Extensions: I have PlatformIO IDE(1.10.0), and C/C++ by microsoft (v0.29.0)

In PlatformIO libraries, I installed the ESP8266 Influxdb library (which is listed twice, but they seem to be the same).

Compile, it fails with that error. I've used this library on a few projects with Particle and the Arduino IDE and it's worked great.  I tried my same code in the Arduino IDE and it worked. VSCode fails. Doesn't seem to like the For loops that are basically a foreach statement. 

I went into the libraries directory and re-wrote the for loops like my previous comment and it works great now.

**Comment by vlastahajek** [comment]
> ESP32.
> 
> [env:esp32dev]
> platform = espressif32@1.7.0
> board = esp32dev
> framework = arduino

PlatformIO espressif32 1.7.0 seems quite old. Try to update the platform, please.  The same problem was in ESP32 Arduino SDK 1.0.2. Required `begin()` and `end()` were added in 1.0.3

**Comment by jlboygenius** [comment]
Wow, strange, you're right. both 1.7 and the latest were installed. Removed the @1.7.0 and it worked without the changes I made to the library.. Uninstalled 1.7.

Thanks!
