### ISSUE TITLE
configTzTime not found for ESP8266

### ISSUE THREAD

**Issue by heinduplessis** [tobiasschuerg/InfluxDB-Client-for-Arduino#85]
I'm using a NodeMCU ESP8266 and when I compile I get an error reporting that the function configTzTime is not found in helpers.cpp. I've had to comment out the timeSync funtion in helpers.cpp and sync time using another library. I'm pretty sure the fault is on my side, but I can't see where I've gone wrong, so maybe extending the read.me a bit might be good. I'm using the example arduino code.

**Comment by vlastahajek** [comment]
@heinduplessis, you most probably need to upgrade ESP8266 Arduino SDK.  Since version 3.2.0 this library requires  ESP8266 Arduino SDK >=2.7.0.

**Comment by heinduplessis** [comment]
That is it! Works now!! Thanks!
