### ISSUE TITLE
Connection refused with InfluxDB 1.8.1 behind https apache reverse proxy with let's encrypt certificate

### ISSUE THREAD

**Issue by rercek** [tobiasschuerg/InfluxDB-Client-for-Arduino#88]
Hi,

Thank you for this great arduino lib that I'm currently using to prepare a small project. I use influxDB 1.8.1 behind an apache reverse proxy (http + https with letsencrypt certicate). Everything is working fine with http but, even after the connection is validated, I have a connection refused, see logs below (ESP32 arduino lib version 1.0.4).
Do you have any idea what could be the problem ? I use the chain certificate and I aslo timesync.

Thank you in advance,
Rudy

```
Init
  Server url: https://influx.example.com
  Org: 
  Bucket: rudy
  Token: 
  DB version: 1
setUrls
  writeUrl: https://influx.example.com/write?db=rudy&u=rudy&p=password
  queryUrl: https://influx.example.com/api/v2/query?&u=rudy&p=password
[D] Validating connection to https://influx.example.com/ping?verbose=true
[D] HTTP status code - 200
Connected to InfluxDB: https://influx.example.com
setUrls
  writeUrl: https://influx.example.com/write?db=rudy&u=rudy&p=password
  queryUrl: https://influx.example.com/api/v2/query?&u=rudy&p=password
  writeUrl: https://influx.example.com/write?db=rudy&u=rudy&p=password&precision=s

[D] Prepare batch: bufferPointer: 1, batchPointer: 0, ceiling 1
[D] Prepare batch size 1
[D] Writing batch, size 1
[D] Writing to https://influx.example.com/write?db=rudy&u=rudy&p=password&precision=s
[D] Sending:
wifi,deviceID=4C:11:AE:74:E4:24,SSID=wifirud rssi=-79i 1597241548

[D] HTTP status code - -1
[E] Error - connection refused
[D] Leaving data in buffer for retry
InfluxDB flush failed: connection refused
Full buffer: No
[D] Prepare batch: bufferPointer: 1, batchPointer: 0, ceiling 1
[D] Prepare batch size 1
[D] Writing batch, size 1
[D] Writing to https://influx.example.com/write?db=rudy&u=rudy&p=password&precision=s
[D] Sending:
wifi,deviceID=4C:11:AE:74:E4:24,SSID=wifirud rssi=-79i 1597241548

[D] HTTP status code - -1
[E] Error - connection refused
[D] Leaving data in buffer for retry
InfluxDB flush failed: connection refused
Full buffer: No
[D] Prepare batch: bufferPointer: 1, batchPointer: 0, ceiling 1
[D] Prepare batch size 1
[D] Writing batch, size 1
[D] Writing to https://influx.example.com/write?db=rudy&u=rudy&p=password&precision=s
[D] Sending:
wifi,deviceID=4C:11:AE:74:E4:24,SSID=wifirud rssi=-79i 1597241548


```

**Comment by vlastahajek** [comment]
@rercek, thanks for the detailed description. 
Can you check, if you able to go through using other tools, e.g. curl?
`curl -XPOST "https://influx.example.com/write?db=rudy&u=rudy&p=password&precision=s" --data-raw "wifi,deviceID=4C:11:AE:74:E4:24,SSID=wifirud rssi=-79i 1597241548"`.

If yes, try to enable core debug for SSL on your board config, please.

**Comment by rercek** [comment]
@vlastahajek Thank you very much for your reply.
Everything is working fine with curl and even with python (influxdb lib). I will have a look to the core debug for SSL and will come back to you as soon as I have more information. 

Thank you again,

**Comment by rercek** [comment]
@vlastahajek It seems to be a problem with the memory allocation for ssl (see below)
Since I first developed my code using http (not https), my current code probably uses too much ram memory. I will check this with a basic code.

```
[D][HTTPClient.cpp:276] beginInternal(): host: influx.example.com port: 443 url: /ping?verbose=true
[D][HTTPClient.cpp:1025] connect():  connected to influx.example.com:443
[D][HTTPClient.cpp:1158] handleHeaderResponse(): code: 200
[D][HTTPClient.cpp:1161] handleHeaderResponse(): size: 19
[D][HTTPClient.cpp:361] disconnect(): still data in buffer (19), clean up.

[D][HTTPClient.cpp:370] disconnect(): tcp stop

[D][HTTPClient.cpp:276] beginInternal(): host: influx.example.com port: 443 url: /write?db=rudy&u=rudy&p=password&precision=s
[D][BLEClient.cpp:458] handleGAPEvent(): BLEClient ... handling GAP event!
[E][ssl_client.cpp:33] _handle_error(): [start_ssl_client():199]: (-10368) X509 - Allocation of memory failed
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -10368
[D][HTTPClient.cpp:1018] connect(): failed connect to influx.example.com:443
[W][HTTPClient.cpp:1318] returnError(): error(-1): connection refused
[D][HTTPClient.cpp:383] disconnect(): tcp is closed

```

**Comment by vlastahajek** [comment]
ESP32 SDK doesn't validate certs. You could save RAM by removing setting trusted server cert.

**Comment by rercek** [comment]
@vlastahajek It didn't change anything. Since I need to use the BLE library, it seems there is not enough memory to load the certs. I even manage to adapt a part of my code in micropython but I have the same problem when I use the urequest library with https and the bluetooth module loaded. My only solution would be to use an esp32 with psram. I bought one to check this but it will take time to arrive. For the moment, I will continue to use http since it works. Thank you again for you help. I will close this issue in a few days if some other people may have a solution. (NB: free heap size 70k and with micropython 60k)
