### ISSUE TITLE
Batch write

### ISSUE THREAD

**Issue by samaliftech** [tobiasschuerg/InfluxDB-Client-for-Arduino#94]
Help me to write batch 10 data for every 1 second. Very important!

**Comment by vlastahajek** [comment]
Could you, please, tell us more about your issue? Have you read the [Writing in Batches paragraf in Readme](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/tree/3.3.0#writing-in-batches). What doesn't work?

**Comment by samaliftech** [comment]
What I understand from the example code is data will be batch write for every one hour. So, I want to batch the data for every 10 second.

**Comment by vlastahajek** [comment]
Data are written, when one of following conditions is met:
- when a batch is  finalized 
- when flush interval runs out. Default **60s**

You can anytime force writing by calling `flushBuffer()`. If you want to write frequently (e.g. one per 5s), set also `preserveConnection = true` to avoid establishing connection each time
