### ISSUE TITLE
Too early request

### ISSUE THREAD

**Issue by samaliftech** [tobiasschuerg/InfluxDB-Client-for-Arduino#96]
I set delay to 100ms and it says 'Write failed to InfluxDB. too early request'. Then the delay change automatically to 2-3 second to upload the data to InfluxDB Cloud

**Comment by samaliftech** [comment]
Please answer as soon possible!!! It is important

**Comment by vlastahajek** [comment]
@samaliftech, InfluxDB cloud has a [write rate limit](https://docs.influxdata.com/influxdb/v2.0/account-management/pricing-plans/#free-plan-rate-limits). InfluxDB server in response specifies how long the client should wait before sending another request.

**Comment by vlastahajek** [comment]
I will add `canWrite()`, or so, a method  later to check whether there is a good time to write data.
