### ISSUE TITLE
Querring Influxdb 1.8.2 API v2

### ISSUE THREAD

**Issue by Herreropl** [tobiasschuerg/InfluxDB-Client-for-Arduino#97]
I have got the problem with querring InfluxdB v1.8.2. The problem is with:
`#define INFLUXDB_ORG ""`
In the example the is information that in case of v1.8.2 it should be empty, but it doesn't work. The output is:
`Init
Server url: http://XXXXXX.com:5086
Org: 
Bucket: starbase
Token: XXXXX:XXXXX
DB version: 2
[E] Invalid parameters
InfluxDB connection failed: Unconfigured instance`

If I put the space char to the _ORG string is better:
`Init
Server url: http://XXXXX.com:5086
Org:  
Bucket: starbase
Token: XXXXX:XXXXX
DB version: 2
setUrls
writeUrl: http://XXXXXX.com:5086/api/v2/write?org= &bucket=starbase
queryUrl: http://XXXXX.com:5086/api/v2/query?org= 
[D] Validating connection to http://herrero-net.com:5086/health
[D] HTTP status code - 200
Connected to InfluxDB: http://XXXXXX.com:5086`

The problem is with adding to query "org= ". 

I have modified librarry and remove this form sources and now works well, but I think this should be corrected.

To be sure I initialized client this way:
`InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN, InfluxDbCloud2CACert);`

**Comment by vlastahajek** [comment]
@Herreropl, code
```cpp
InfluxDBClient client(INFLUXDB_URL, INFLUXDB_ORG, INFLUXDB_BUCKET, INFLUXDB_TOKEN, InfluxDbCloud2CACert);
```
initialises client primarily for connecting to InfluxDB 2. InfluxDB 2 requires non-empty _org_ parameter and this the reason why you are getting the _Unconfigured instance_ error. InfluxDB 1.8.x support forward compatibility API, which allows writing data and querying with Flux using v2 approach. In this way you have to set ORG to any string to be non-empty.

You can use another constructor to leverage InfluxDB 1.x specific write API:
```cpp
InfluxDBClient client(const char *serverUrl, const char *db);
```
or
```cpp
client.setConnectionParamsV1(const char *serverUrl, const char *db, const char *user = nullptr, const char *password = nullptr, const char *certInfo = nullptr);
```
